# 01 · Coleta de Dados (DataSUS)

**Objetivo:** Baixar arquivos `.dbc` diretamente do servidor FTP público do DataSUS e convertê-los para `.csv`, alimentando as etapas seguintes do projeto.

**Inputs:** Nenhum (acesso direto ao FTP do DataSUS via internet).

**Outputs gerados:**
- `data/raw/SIH/` — arquivos `.dbc` brutos do Sistema de Informações Hospitalares
- `data/raw/CNES/` — arquivos `.dbc` brutos do Cadastro Nacional de Estabelecimentos
- `data/input/SIH/` — arquivos `.csv` convertidos do SIH
- `data/input/CNES/` — arquivos `.csv` convertidos do CNES

**Sistemas do DATASUS utilizados:**

| Sigla | Nome completo |
|-------|---------------|
| `SIH`  | Sistema de Informações Hospitalares |
| `CNES` | Cadastro Nacional de Estabelecimentos de Saúde |

<br/>

> **Nota:** O `SIM` (Sistema de Informação sobre Mortalidade) está disponível nos utilitários mas não é utilizado neste projeto.

## 0. Configuração do Ambiente

In [1]:
import sys
import os
import pandas as pd
from pathlib import Path

In [2]:
# Garante que a raiz do projeto está no sys.path para importar src/
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

print(f"Raiz do projeto: {ROOT}")

Raiz do projeto: /home/carolina/Documents/TCC Documentos/TCC

In [3]:
# Importa utilitários do projeto
from src.utils.download_data_from_datasus import download_data, download_dicionarios
from src.utils.converter_dbc_para_csv import converter_dbc_para_csv_lote

print("Utilitários importados")

Utilitários importados

## 1. Coleta do SIH (Sistema de Informações Hospitalares)

Baixamos os registros de AIH (Autorização de Internação Hospitalar) para o estado e ano definidos abaixo.
O fluxo é:
1. Download do `.dbc` do FTP do DataSUS → `data/raw/SIH/`
2. Conversão `.dbc → .csv` → `data/input/SIH/`

In [7]:
# ── Parâmetros de coleta ─────────────────────────────────────────────
ESTADOS_SIH = ["SP"]    # lista de UFs a baixar
ANOS_SIH    = [2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025]    # anos de referência
MESES_SIH    = [1,2,3,4,5,6,7,8,9,10,12]    # meses de referência
SISTEMA_SIH = "SIH"     # identificador do sistema DataSUS

# ── Diretórios ───────────────────────────────────────────────────────
PASTA_RAW_SIH   = Path(ROOT, "data", "raw",   SISTEMA_SIH)
PASTA_INPUT_SIH = Path(ROOT, "data", "input", SISTEMA_SIH)

PASTA_RAW_SIH.mkdir(parents=True, exist_ok=True)
PASTA_INPUT_SIH.mkdir(parents=True, exist_ok=True)

print(f"RAW   : {PASTA_RAW_SIH}")
print(f"INPUT : {PASTA_INPUT_SIH}")

RAW   : /home/carolina/Documents/TCC Documentos/TCC/data/raw/SIH
INPUT : /home/carolina/Documents/TCC Documentos/TCC/data/input/SIH

In [8]:
# Download dos arquivos .dbc do SIH
print("Iniciando download do SIH...")
download_data(
    estados=ESTADOS_SIH,
    anos=ANOS_SIH,
    meses=MESES_SIH,
    sistema=SISTEMA_SIH,
    download_path=str(PASTA_RAW_SIH),
)
print("Download concluído.")

Iniciando download do SIH...
Conectando ao FTP: ftp.datasus.gov.br
Baixando: RDSP1501.dbc
Sucesso: RDSP1501.dbc
Baixando: RDSP1502.dbc
Sucesso: RDSP1502.dbc
Baixando: RDSP1503.dbc
Sucesso: RDSP1503.dbc
Baixando: RDSP1504.dbc
Sucesso: RDSP1504.dbc
Baixando: RDSP1505.dbc
Sucesso: RDSP1505.dbc
Baixando: RDSP1506.dbc
Sucesso: RDSP1506.dbc
Baixando: RDSP1507.dbc
Sucesso: RDSP1507.dbc
Baixando: RDSP1508.dbc
Sucesso: RDSP1508.dbc
Baixando: RDSP1509.dbc
Sucesso: RDSP1509.dbc
Baixando: RDSP1510.dbc
Sucesso: RDSP1510.dbc
Baixando: RDSP1512.dbc
Sucesso: RDSP1512.dbc
Baixando: RDSP1601.dbc
Sucesso: RDSP1601.dbc
Baixando: RDSP1602.dbc
Sucesso: RDSP1602.dbc
Baixando: RDSP1603.dbc
Sucesso: RDSP1603.dbc
Baixando: RDSP1604.dbc
Sucesso: RDSP1604.dbc
Baixando: RDSP1605.dbc
Sucesso: RDSP1605.dbc
Baixando: RDSP1606.dbc
Sucesso: RDSP1606.dbc
Baixando: RDSP1607.dbc
Sucesso: RDSP1607.dbc
Baixando: RDSP1608.dbc
Sucesso: RDSP1608.dbc
Baixando: RDSP1609.dbc
Sucesso: RDSP1609.dbc
Baixando: RDSP1610.dbc
Sucesso: RDSP1610.dbc
Baixando: RDSP1612.dbc
Sucesso: RDSP1612.dbc
Baixando: RDSP1701.dbc
Sucesso: RDSP1701.dbc
Baixando: RDSP1702.dbc
Sucesso: RDSP1702.dbc
Baixando: RDSP1703.dbc
Sucesso: RDSP1703.dbc
Baixando: RDSP1704.dbc
Sucesso: RDSP1704.dbc
Baixando: RDSP1705.dbc
Sucesso: RDSP1705.dbc
Baixando: RDSP1706.dbc
Sucesso: RDSP1706.dbc
Baixando: RDSP1707.dbc
Sucesso: RDSP1707.dbc
Baixando: RDSP1708.dbc
Sucesso: RDSP1708.dbc
Baixando: RDSP1709.dbc
Sucesso: RDSP1709.dbc
Baixando: RDSP1710.dbc
Sucesso: RDSP1710.dbc
Baixando: RDSP1712.dbc
Sucesso: RDSP1712.dbc
Baixando: RDSP1801.dbc
Sucesso: RDSP1801.dbc
Baixando: RDSP1802.dbc
Sucesso: RDSP1802.dbc
Baixando: RDSP1803.dbc
Sucesso: RDSP1803.dbc
Baixando: RDSP1804.dbc
Sucesso: RDSP1804.dbc
Baixando: RDSP1805.dbc
Sucesso: RDSP1805.dbc
Baixando: RDSP1806.dbc
Sucesso: RDSP1806.dbc
Baixando: RDSP1807.dbc
Sucesso: RDSP1807.dbc
Baixando: RDSP1808.dbc
Sucesso: RDSP1808.dbc
Baixando: RDSP1809.dbc
Sucesso: RDSP1809.dbc
Baixando: RDSP1810.dbc
Sucesso: RDSP1810.dbc
Baixando: RDSP1812.dbc
Sucesso: RDSP1812.dbc
Baixando: RDSP1901.dbc
Sucesso: RDSP1901.dbc
Baixando: RDSP1902.dbc
Sucesso: RDSP1902.dbc
Baixando: RDSP1903.dbc
Sucesso: RDSP1903.dbc
Baixando: RDSP1904.dbc
Sucesso: RDSP1904.dbc
Baixando: RDSP1905.dbc
Sucesso: RDSP1905.dbc
Baixando: RDSP1906.dbc
Sucesso: RDSP1906.dbc
Baixando: RDSP1907.dbc
Sucesso: RDSP1907.dbc
Baixando: RDSP1908.dbc
Sucesso: RDSP1908.dbc
Baixando: RDSP1909.dbc
Sucesso: RDSP1909.dbc
Baixando: RDSP1910.dbc
Sucesso: RDSP1910.dbc
Baixando: RDSP1912.dbc
Sucesso: RDSP1912.dbc
Baixando: RDSP2001.dbc
Sucesso: RDSP2001.dbc
Baixando: RDSP2002.dbc
Sucesso: RDSP2002.dbc
Baixando: RDSP2003.dbc
Sucesso: RDSP2003.dbc
Baixando: RDSP2004.dbc
Sucesso: RDSP2004.dbc
Baixando: RDSP2005.dbc
Sucesso: RDSP2005.dbc
Baixando: RDSP2006.dbc
Sucesso: RDSP2006.dbc
Baixando: RDSP2007.dbc
Sucesso: RDSP2007.dbc
Baixando: RDSP2008.dbc
Sucesso: RDSP2008.dbc
Baixando: RDSP2009.dbc
Sucesso: RDSP2009.dbc
Baixando: RDSP2010.dbc
Sucesso: RDSP2010.dbc
Baixando: RDSP2012.dbc
Sucesso: RDSP2012.dbc
Baixando: RDSP2101.dbc
Sucesso: RDSP2101.dbc
Baixando: RDSP2102.dbc
Sucesso: RDSP2102.dbc
Baixando: RDSP2103.dbc
Sucesso: RDSP2103.dbc
Baixando: RDSP2104.dbc
Sucesso: RDSP2104.dbc
Baixando: RDSP2105.dbc
Sucesso: RDSP2105.dbc
Baixando: RDSP2106.dbc
Sucesso: RDSP2106.dbc
Baixando: RDSP2107.dbc
Sucesso: RDSP2107.dbc
Baixando: RDSP2108.dbc
Sucesso: RDSP2108.dbc
Baixando: RDSP2109.dbc
Sucesso: RDSP2109.dbc
Baixando: RDSP2110.dbc
Sucesso: RDSP2110.dbc
Baixando: RDSP2112.dbc
Sucesso: RDSP2112.dbc
Baixando: RDSP2201.dbc
Sucesso: RDSP2201.dbc
Baixando: RDSP2202.dbc
Sucesso: RDSP2202.dbc
Baixando: RDSP2203.dbc
Sucesso: RDSP2203.dbc
Baixando: RDSP2204.dbc
Sucesso: RDSP2204.dbc
Baixando: RDSP2205.dbc
Sucesso: RDSP2205.dbc
Baixando: RDSP2206.dbc
Sucesso: RDSP2206.dbc
Baixando: RDSP2207.dbc
Sucesso: RDSP2207.dbc
Baixando: RDSP2208.dbc
Sucesso: RDSP2208.dbc
Baixando: RDSP2209.dbc
Sucesso: RDSP2209.dbc
Baixando: RDSP2210.dbc
Sucesso: RDSP2210.dbc
Baixando: RDSP2212.dbc
Sucesso: RDSP2212.dbc
Baixando: RDSP2301.dbc
Sucesso: RDSP2301.dbc
Baixando: RDSP2302.dbc
Sucesso: RDSP2302.dbc
Baixando: RDSP2303.dbc
Sucesso: RDSP2303.dbc
Baixando: RDSP2304.dbc
Sucesso: RDSP2304.dbc
Baixando: RDSP2305.dbc
Sucesso: RDSP2305.dbc
Baixando: RDSP2306.dbc
Sucesso: RDSP2306.dbc
Baixando: RDSP2307.dbc
Sucesso: RDSP2307.dbc
Baixando: RDSP2308.dbc
Sucesso: RDSP2308.dbc
Baixando: RDSP2309.dbc
Sucesso: RDSP2309.dbc
Baixando: RDSP2310.dbc
Sucesso: RDSP2310.dbc
Baixando: RDSP2312.dbc
Sucesso: RDSP2312.dbc
Baixando: RDSP2401.dbc
Sucesso: RDSP2401.dbc
Baixando: RDSP2402.dbc
Sucesso: RDSP2402.dbc
Baixando: RDSP2403.dbc
Sucesso: RDSP2403.dbc
Baixando: RDSP2404.dbc
Sucesso: RDSP2404.dbc
Baixando: RDSP2405.dbc
Sucesso: RDSP2405.dbc
Baixando: RDSP2406.dbc
Sucesso: RDSP2406.dbc
Baixando: RDSP2407.dbc
Sucesso: RDSP2407.dbc
Baixando: RDSP2408.dbc
Sucesso: RDSP2408.dbc
Baixando: RDSP2409.dbc
Sucesso: RDSP2409.dbc
Baixando: RDSP2410.dbc
Sucesso: RDSP2410.dbc
Baixando: RDSP2412.dbc
Sucesso: RDSP2412.dbc
Baixando: RDSP2501.dbc
Sucesso: RDSP2501.dbc
Baixando: RDSP2502.dbc
Sucesso: RDSP2502.dbc
Baixando: RDSP2503.dbc
Sucesso: RDSP2503.dbc
Baixando: RDSP2504.dbc
Sucesso: RDSP2504.dbc
Baixando: RDSP2505.dbc
Sucesso: RDSP2505.dbc
Baixando: RDSP2506.dbc
Sucesso: RDSP2506.dbc
Baixando: RDSP2507.dbc
Sucesso: RDSP2507.dbc
Baixando: RDSP2508.dbc
Sucesso: RDSP2508.dbc
Baixando: RDSP2509.dbc
Sucesso: RDSP2509.dbc
Baixando: RDSP2510.dbc
Sucesso: RDSP2510.dbc
Baixando: RDSP2512.dbc
Sucesso: RDSP2512.dbc

Download finalizado!
Arquivos salvos em: /home/carolina/Documents/TCC Documentos/TCC/data/raw/SIH
Download concluído.

In [9]:
# Conversão .dbc → .csv
print("Convertendo arquivos SIH de .dbc para .csv...")
converter_dbc_para_csv_lote(str(PASTA_RAW_SIH), str(PASTA_INPUT_SIH))

Convertendo arquivos SIH de .dbc para .csv...
Processando: RDSP2106.dbc
Concluído: rdsp2106.csv
Processando: RDSP1505.dbc
Concluído: rdsp1505.csv
Processando: RDSP1509.dbc
Concluído: rdsp1509.csv
Processando: RDSP2306.dbc
Concluído: rdsp2306.csv
Processando: RDSP1908.dbc
Concluído: rdsp1908.csv
Processando: RDSP2307.dbc
Concluído: rdsp2307.csv
Processando: RDSP1608.dbc
Concluído: rdsp1608.csv
Processando: RDSP1905.dbc
Concluído: rdsp1905.csv
Processando: RDSP1901.dbc
Concluído: rdsp1901.csv
Processando: RDSP2303.dbc
Concluído: rdsp2303.csv
Processando: RDSP2110.dbc
Concluído: rdsp2110.csv
Processando: RDSP2007.dbc
Concluído: rdsp2007.csv
Processando: RDSP1903.dbc
Concluído: rdsp1903.csv
Processando: RDSP1804.dbc
Concluído: rdsp1804.csv
Processando: RDSP2009.dbc
Concluído: rdsp2009.csv
Processando: RDSP2005.dbc
Concluído: rdsp2005.csv
Processando: RDSP1705.dbc
Concluído: rdsp1705.csv
Processando: RDSP1712.dbc
Concluído: rdsp1712.csv
Processando: RDSP2507.dbc
Concluído: rdsp2507.csv
Processando: RDSP2112.dbc
Concluído: rdsp2112.csv
Processando: RDSP1810.dbc
Concluído: rdsp1810.csv
Processando: RDSP2201.dbc
Concluído: rdsp2201.csv
Processando: RDSP2405.dbc
Concluído: rdsp2405.csv
Processando: RDSP2512.dbc
Concluído: rdsp2512.csv
Processando: RDSP1801.dbc
Concluído: rdsp1801.csv
Processando: RDSP2508.dbc
Concluído: rdsp2508.csv
Processando: RDSP2206.dbc
Concluído: rdsp2206.csv
Processando: RDSP2012.dbc
Concluído: rdsp2012.csv
Processando: RDSP1910.dbc
Concluído: rdsp1910.csv
Processando: RDSP2506.dbc
Concluído: rdsp2506.csv
Processando: RDSP1808.dbc
Concluído: rdsp1808.csv
Processando: RDSP2404.dbc
Concluído: rdsp2404.csv
Processando: RDSP1904.dbc
Concluído: rdsp1904.csv
Processando: RDSP1507.dbc
Concluído: rdsp1507.csv
Processando: RDSP1807.dbc
Concluído: rdsp1807.csv
Processando: RDSP2502.dbc
Concluído: rdsp2502.csv
Processando: RDSP1709.dbc
Concluído: rdsp1709.csv
Processando: RDSP1502.dbc
Concluído: rdsp1502.csv
Processando: RDSP2301.dbc
Concluído: rdsp2301.csv
Processando: RDSP1506.dbc
Concluído: rdsp1506.csv
Processando: RDSP1710.dbc
Concluído: rdsp1710.csv
Processando: RDSP2203.dbc
Concluído: rdsp2203.csv
Processando: RDSP1707.dbc
Concluído: rdsp1707.csv
Processando: RDSP1607.dbc
Concluído: rdsp1607.csv
Processando: RDSP2304.dbc
Concluído: rdsp2304.csv
Processando: RDSP1902.dbc
Concluído: rdsp1902.csv
Processando: RDSP2004.dbc
Concluído: rdsp2004.csv
Processando: RDSP2401.dbc
Concluído: rdsp2401.csv
Processando: RDSP2403.dbc
Concluído: rdsp2403.csv
Processando: RDSP2103.dbc
Concluído: rdsp2103.csv
Processando: RDSP2410.dbc
Concluído: rdsp2410.csv
Processando: RDSP1605.dbc
Concluído: rdsp1605.csv
Processando: RDSP2003.dbc
Concluído: rdsp2003.csv
Processando: RDSP2107.dbc
Concluído: rdsp2107.csv
Processando: RDSP2510.dbc
Concluído: rdsp2510.csv
Processando: RDSP1703.dbc
Concluído: rdsp1703.csv
Processando: RDSP2302.dbc
Concluído: rdsp2302.csv
Processando: RDSP1809.dbc
Concluído: rdsp1809.csv
Processando: RDSP2108.dbc
Concluído: rdsp2108.csv
Processando: RDSP1510.dbc
Concluído: rdsp1510.csv
Processando: RDSP2312.dbc
Concluído: rdsp2312.csv
Processando: RDSP2408.dbc
Concluído: rdsp2408.csv
Processando: RDSP2505.dbc
Concluído: rdsp2505.csv
Processando: RDSP2105.dbc
Concluído: rdsp2105.csv
Processando: RDSP1512.dbc
Concluído: rdsp1512.csv
Processando: RDSP1606.dbc
Concluído: rdsp1606.csv
Processando: RDSP2008.dbc
Concluído: rdsp2008.csv
Processando: RDSP2002.dbc
Concluído: rdsp2002.csv
Processando: RDSP1503.dbc
Concluído: rdsp1503.csv
Processando: RDSP2109.dbc
Concluído: rdsp2109.csv
Processando: RDSP2409.dbc
Concluído: rdsp2409.csv
Processando: RDSP2208.dbc
Concluído: rdsp2208.csv
Processando: RDSP1701.dbc
Concluído: rdsp1701.csv
Processando: RDSP1704.dbc
Concluído: rdsp1704.csv
Processando: RDSP2412.dbc
Concluído: rdsp2412.csv
Processando: RDSP2207.dbc
Concluído: rdsp2207.csv
Processando: RDSP1508.dbc
Concluído: rdsp1508.csv
Processando: RDSP1604.dbc
Concluído: rdsp1604.csv
Processando: RDSP1706.dbc
Concluído: rdsp1706.csv
Processando: RDSP2310.dbc
Concluído: rdsp2310.csv
Processando: RDSP2212.dbc
Concluído: rdsp2212.csv
Processando: RDSP1708.dbc
Concluído: rdsp1708.csv
Processando: RDSP2001.dbc
Concluído: rdsp2001.csv
Processando: RDSP1603.dbc
Concluído: rdsp1603.csv
Processando: RDSP2102.dbc
Concluído: rdsp2102.csv
Processando: RDSP2010.dbc
Concluído: rdsp2010.csv
Processando: RDSP2504.dbc
Concluído: rdsp2504.csv
Processando: RDSP2309.dbc
Concluído: rdsp2309.csv
Processando: RDSP2407.dbc
Concluído: rdsp2407.csv
Processando: RDSP1504.dbc
Concluído: rdsp1504.csv
Processando: RDSP2209.dbc
Concluído: rdsp2209.csv
Processando: RDSP1907.dbc
Concluído: rdsp1907.csv
Processando: RDSP2509.dbc
Concluído: rdsp2509.csv
Processando: RDSP2402.dbc
Concluído: rdsp2402.csv
Processando: RDSP1602.dbc
Concluído: rdsp1602.csv
Processando: RDSP2503.dbc
Concluído: rdsp2503.csv
Processando: RDSP1906.dbc
Concluído: rdsp1906.csv
Processando: RDSP1803.dbc
Concluído: rdsp1803.csv
Processando: RDSP1601.dbc
Concluído: rdsp1601.csv
Processando: RDSP1812.dbc
Concluído: rdsp1812.csv
Processando: RDSP2104.dbc
Concluído: rdsp2104.csv
Processando: RDSP2308.dbc
Concluído: rdsp2308.csv
Processando: RDSP2101.dbc
Concluído: rdsp2101.csv
Processando: RDSP2202.dbc
Concluído: rdsp2202.csv
Processando: RDSP1806.dbc
Concluído: rdsp1806.csv
Processando: RDSP2205.dbc
Concluído: rdsp2205.csv
Processando: RDSP2305.dbc
Concluído: rdsp2305.csv
Processando: RDSP1912.dbc
Concluído: rdsp1912.csv
Processando: RDSP2210.dbc
Concluído: rdsp2210.csv
Processando: RDSP1909.dbc
Concluído: rdsp1909.csv
Processando: RDSP2204.dbc
Concluído: rdsp2204.csv
Processando: RDSP1501.dbc
Concluído: rdsp1501.csv
Processando: RDSP1610.dbc
Concluído: rdsp1610.csv
Processando: RDSP1805.dbc
Concluído: rdsp1805.csv
Processando: RDSP1702.dbc
Concluído: rdsp1702.csv
Processando: RDSP2006.dbc
Concluído: rdsp2006.csv
Processando: RDSP2406.dbc
Concluído: rdsp2406.csv
Processando: RDSP1609.dbc
Concluído: rdsp1609.csv
Processando: RDSP1612.dbc
Concluído: rdsp1612.csv
Processando: RDSP1802.dbc
Concluído: rdsp1802.csv
Processando: RDSP2501.dbc
Concluído: rdsp2501.csv

In [10]:
# Validação: lista arquivos gerados
csvs_sih = sorted(PASTA_INPUT_SIH.glob("*.csv"))
print(f"\nArquivos CSV gerados ({len(csvs_sih)}):")
for f in csvs_sih:
    print(f"  {f.name}  ({f.stat().st_size / 1024:.0f} KB)")

Arquivos CSV gerados (121):
  rdsp1501.csv  (89555 KB)
  rdsp1502.csv  (87418 KB)
  rdsp1503.csv  (95731 KB)
  rdsp1504.csv  (95761 KB)
  rdsp1505.csv  (96402 KB)
  rdsp1506.csv  (95211 KB)
  rdsp1507.csv  (95879 KB)
  rdsp1508.csv  (94421 KB)
  rdsp1509.csv  (92502 KB)
  rdsp1510.csv  (92434 KB)
  rdsp1512.csv  (89346 KB)
  rdsp1601.csv  (86450 KB)
  rdsp1602.csv  (88197 KB)
  rdsp1603.csv  (95574 KB)
  rdsp1604.csv  (94907 KB)
  rdsp1605.csv  (95643 KB)
  rdsp1606.csv  (97955 KB)
  rdsp1607.csv  (95790 KB)
  rdsp1608.csv  (95483 KB)
  rdsp1609.csv  (92489 KB)
  rdsp1610.csv  (90377 KB)
  rdsp1612.csv  (89061 KB)
  rdsp1701.csv  (86818 KB)
  rdsp1702.csv  (84319 KB)
  rdsp1703.csv  (97483 KB)
  rdsp1704.csv  (89634 KB)
  rdsp1705.csv  (98912 KB)
  rdsp1706.csv  (94337 KB)
  rdsp1707.csv  (94321 KB)
  rdsp1708.csv  (98067 KB)
  rdsp1709.csv  (93206 KB)
  rdsp1710.csv  (94423 KB)
  rdsp1712.csv  (91371 KB)
  rdsp1801.csv  (91666 KB)
  rdsp1802.csv  (88804 KB)
  rdsp1803.csv  (97083 KB)
  rdsp1804.csv  (96674 KB)
  rdsp1805.csv  (97727 KB)
  rdsp1806.csv  (94319 KB)
  rdsp1807.csv  (95518 KB)
  rdsp1808.csv  (97640 KB)
  rdsp1809.csv  (93359 KB)
  rdsp1810.csv  (97449 KB)
  rdsp1812.csv  (90955 KB)
  rdsp1901.csv  (94476 KB)
  rdsp1902.csv  (90939 KB)
  rdsp1903.csv  (97131 KB)
  rdsp1904.csv  (99043 KB)
  rdsp1905.csv  (101553 KB)
  rdsp1906.csv  (96648 KB)
  rdsp1907.csv  (98985 KB)
  rdsp1908.csv  (101459 KB)
  rdsp1909.csv  (97088 KB)
  rdsp1910.csv  (101029 KB)
  rdsp1912.csv  (91328 KB)
  rdsp2001.csv  (96386 KB)
  rdsp2002.csv  (91784 KB)
  rdsp2003.csv  (93218 KB)
  rdsp2004.csv  (70591 KB)
  rdsp2005.csv  (72842 KB)
  rdsp2006.csv  (76866 KB)
  rdsp2007.csv  (83468 KB)
  rdsp2008.csv  (82458 KB)
  rdsp2009.csv  (85372 KB)
  rdsp2010.csv  (87625 KB)
  rdsp2012.csv  (84062 KB)
  rdsp2101.csv  (87537 KB)
  rdsp2102.csv  (85374 KB)
  rdsp2103.csv  (89158 KB)
  rdsp2104.csv  (86019 KB)
  rdsp2105.csv  (90263 KB)
  rdsp2106.csv  (89837 KB)
  rdsp2107.csv  (89647 KB)
  rdsp2108.csv  (89950 KB)
  rdsp2109.csv  (87966 KB)
  rdsp2110.csv  (87175 KB)
  rdsp2112.csv  (90792 KB)
  rdsp2201.csv  (88925 KB)
  rdsp2202.csv  (85650 KB)
  rdsp2203.csv  (96008 KB)
  rdsp2204.csv  (91796 KB)
  rdsp2205.csv  (92038 KB)
  rdsp2206.csv  (94116 KB)
  rdsp2207.csv  (98473 KB)
  rdsp2208.csv  (98440 KB)
  rdsp2209.csv  (98901 KB)
  rdsp2210.csv  (98431 KB)
  rdsp2212.csv  (94622 KB)
  rdsp2301.csv  (93922 KB)
  rdsp2302.csv  (90461 KB)
  rdsp2303.csv  (104408 KB)
  rdsp2304.csv  (97449 KB)
  rdsp2305.csv  (102496 KB)
  rdsp2306.csv  (103841 KB)
  rdsp2307.csv  (101541 KB)
  rdsp2308.csv  (106198 KB)
  rdsp2309.csv  (99912 KB)
  rdsp2310.csv  (100364 KB)
  rdsp2312.csv  (97176 KB)
  rdsp2401.csv  (99677 KB)
  rdsp2402.csv  (98950 KB)
  rdsp2403.csv  (108208 KB)
  rdsp2404.csv  (109534 KB)
  rdsp2405.csv  (110276 KB)
  rdsp2406.csv  (107640 KB)
  rdsp2407.csv  (108059 KB)
  rdsp2408.csv  (110186 KB)
  rdsp2409.csv  (107430 KB)
  rdsp2410.csv  (111958 KB)
  rdsp2412.csv  (100974 KB)
  rdsp2501.csv  (106533 KB)
  rdsp2502.csv  (103466 KB)
  rdsp2503.csv  (110689 KB)
  rdsp2504.csv  (110343 KB)
  rdsp2505.csv  (116755 KB)
  rdsp2506.csv  (110543 KB)
  rdsp2507.csv  (114809 KB)
  rdsp2508.csv  (114003 KB)
  rdsp2509.csv  (113086 KB)
  rdsp2510.csv  (115622 KB)
  rdsp2512.csv  (103864 KB)

## 2. Coleta do CNES (Cadastro Nacional de Estabelecimentos de Saúde)

Baixamos os arquivos das tabelas auxiliares do CNES:
- **ST** — Estabelecimentos (tabela principal)
- **LT** — Leitos
- **EQ** — Equipamentos
- **SR** — Serviços Especializados
- **HB** — Habilitações

Esses dados serão integrados com o SIH no notebook `02_eda.ipynb`.

In [11]:
# ── Parâmetros de coleta ─────────────────────────────────────────────
ESTADOS_CNES = ["SP"]   # lista de UFs a baixar
ANOS_CNES    = [2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025]   # anos de referência
MESES_CNES = [1,2,3,4,5,6,7,8,9,10,12]
BASES_CNES = ["ST","LT", "EQ", "HB", "SR"]
SISTEMA_CNES = "CNES"   # identificador do sistema DataSUS

# ── Diretórios ───────────────────────────────────────────────────────
PASTA_RAW_CNES   = Path(ROOT, "data", "raw",   SISTEMA_CNES)
PASTA_INPUT_CNES = Path(ROOT, "data", "input", SISTEMA_CNES)

PASTA_RAW_CNES.mkdir(parents=True, exist_ok=True)
PASTA_INPUT_CNES.mkdir(parents=True, exist_ok=True)

print(f"RAW   : {PASTA_RAW_CNES}")
print(f"INPUT : {PASTA_INPUT_CNES}")

RAW   : /home/carolina/Documents/TCC Documentos/TCC/data/raw/CNES
INPUT : /home/carolina/Documents/TCC Documentos/TCC/data/input/CNES

In [12]:
# Download dos arquivos .dbc do CNES
print("Iniciando download do CNES...")
download_data(
    estados=ESTADOS_CNES,
    anos=ANOS_CNES,
    meses=MESES_CNES,
    sistema=SISTEMA_CNES,
    bases_cnes=BASES_CNES,
    download_path=str(PASTA_RAW_CNES),
)
print("Download concluído.")

Iniciando download do CNES...
Conectando ao FTP: ftp.datasus.gov.br
Baixando: STSP1501.dbc
Sucesso: STSP1501.dbc
Baixando: STSP1502.dbc
Sucesso: STSP1502.dbc
Baixando: STSP1503.dbc
Sucesso: STSP1503.dbc
Baixando: STSP1504.dbc
Sucesso: STSP1504.dbc
Baixando: STSP1505.dbc
Sucesso: STSP1505.dbc
Baixando: STSP1506.dbc
Sucesso: STSP1506.dbc
Baixando: STSP1507.dbc
Sucesso: STSP1507.dbc
Baixando: STSP1508.dbc
Sucesso: STSP1508.dbc
Baixando: STSP1509.dbc
Sucesso: STSP1509.dbc
Baixando: STSP1510.dbc
Sucesso: STSP1510.dbc
Baixando: STSP1512.dbc
Sucesso: STSP1512.dbc
Baixando: STSP1601.dbc
Sucesso: STSP1601.dbc
Baixando: STSP1602.dbc
Sucesso: STSP1602.dbc
Baixando: STSP1603.dbc
Sucesso: STSP1603.dbc
Baixando: STSP1604.dbc
Sucesso: STSP1604.dbc
Baixando: STSP1605.dbc
Sucesso: STSP1605.dbc
Baixando: STSP1606.dbc
Sucesso: STSP1606.dbc
Baixando: STSP1607.dbc
Sucesso: STSP1607.dbc
Baixando: STSP1608.dbc
Sucesso: STSP1608.dbc
Baixando: STSP1609.dbc
Sucesso: STSP1609.dbc
Baixando: STSP1610.dbc
Sucesso: STSP1610.dbc
Baixando: STSP1612.dbc
Sucesso: STSP1612.dbc
Baixando: STSP1701.dbc
Sucesso: STSP1701.dbc
Baixando: STSP1702.dbc
Sucesso: STSP1702.dbc
Baixando: STSP1703.dbc
Sucesso: STSP1703.dbc
Baixando: STSP1704.dbc
Sucesso: STSP1704.dbc
Baixando: STSP1705.dbc
Sucesso: STSP1705.dbc
Baixando: STSP1706.dbc
Sucesso: STSP1706.dbc
Baixando: STSP1707.dbc
Sucesso: STSP1707.dbc
Baixando: STSP1708.dbc
Sucesso: STSP1708.dbc
Baixando: STSP1709.dbc
Sucesso: STSP1709.dbc
Baixando: STSP1710.dbc
Sucesso: STSP1710.dbc
Baixando: STSP1712.dbc
Sucesso: STSP1712.dbc
Baixando: STSP1801.dbc
Sucesso: STSP1801.dbc
Baixando: STSP1802.dbc
Sucesso: STSP1802.dbc
Baixando: STSP1803.dbc
Sucesso: STSP1803.dbc
Baixando: STSP1804.dbc
Sucesso: STSP1804.dbc
Baixando: STSP1805.dbc
Sucesso: STSP1805.dbc
Baixando: STSP1806.dbc
Sucesso: STSP1806.dbc
Baixando: STSP1807.dbc
Sucesso: STSP1807.dbc
Baixando: STSP1808.dbc
Sucesso: STSP1808.dbc
Baixando: STSP1809.dbc
Sucesso: STSP1809.dbc
Baixando: STSP1810.dbc
Sucesso: STSP1810.dbc
Baixando: STSP1812.dbc
Sucesso: STSP1812.dbc
Baixando: STSP1901.dbc
Sucesso: STSP1901.dbc
Baixando: STSP1902.dbc
Sucesso: STSP1902.dbc
Baixando: STSP1903.dbc
Sucesso: STSP1903.dbc
Baixando: STSP1904.dbc
Sucesso: STSP1904.dbc
Baixando: STSP1905.dbc
Sucesso: STSP1905.dbc
Baixando: STSP1906.dbc
Sucesso: STSP1906.dbc
Baixando: STSP1907.dbc
Sucesso: STSP1907.dbc
Baixando: STSP1908.dbc
Sucesso: STSP1908.dbc
Baixando: STSP1909.dbc
Sucesso: STSP1909.dbc
Baixando: STSP1910.dbc
Sucesso: STSP1910.dbc
Baixando: STSP1912.dbc
Sucesso: STSP1912.dbc
Baixando: STSP2001.dbc
Sucesso: STSP2001.dbc
Baixando: STSP2002.dbc
Sucesso: STSP2002.dbc
Baixando: STSP2003.dbc
Sucesso: STSP2003.dbc
Baixando: STSP2004.dbc
Sucesso: STSP2004.dbc
Baixando: STSP2005.dbc
Sucesso: STSP2005.dbc
Baixando: STSP2006.dbc
Sucesso: STSP2006.dbc
Baixando: STSP2007.dbc
Sucesso: STSP2007.dbc
Baixando: STSP2008.dbc
Sucesso: STSP2008.dbc
Baixando: STSP2009.dbc
Sucesso: STSP2009.dbc
Baixando: STSP2010.dbc
Sucesso: STSP2010.dbc
Baixando: STSP2012.dbc
Sucesso: STSP2012.dbc
Baixando: STSP2101.dbc
Sucesso: STSP2101.dbc
Baixando: STSP2102.dbc
Sucesso: STSP2102.dbc
Baixando: STSP2103.dbc
Sucesso: STSP2103.dbc
Baixando: STSP2104.dbc
Sucesso: STSP2104.dbc
Baixando: STSP2105.dbc
Sucesso: STSP2105.dbc
Baixando: STSP2106.dbc
Sucesso: STSP2106.dbc
Baixando: STSP2107.dbc
Sucesso: STSP2107.dbc
Baixando: STSP2108.dbc
Sucesso: STSP2108.dbc
Baixando: STSP2109.dbc
Sucesso: STSP2109.dbc
Baixando: STSP2110.dbc
Sucesso: STSP2110.dbc
Baixando: STSP2112.dbc
Sucesso: STSP2112.dbc
Baixando: STSP2201.dbc
Sucesso: STSP2201.dbc
Baixando: STSP2202.dbc
Sucesso: STSP2202.dbc
Baixando: STSP2203.dbc
Sucesso: STSP2203.dbc
Baixando: STSP2204.dbc
Sucesso: STSP2204.dbc
Baixando: STSP2205.dbc
Sucesso: STSP2205.dbc
Baixando: STSP2206.dbc
Sucesso: STSP2206.dbc
Baixando: STSP2207.dbc
Sucesso: STSP2207.dbc
Baixando: STSP2208.dbc
Sucesso: STSP2208.dbc
Baixando: STSP2209.dbc
Sucesso: STSP2209.dbc
Baixando: STSP2210.dbc
Sucesso: STSP2210.dbc
Baixando: STSP2212.dbc
Sucesso: STSP2212.dbc
Baixando: STSP2301.dbc
Sucesso: STSP2301.dbc
Baixando: STSP2302.dbc
Sucesso: STSP2302.dbc
Baixando: STSP2303.dbc
Sucesso: STSP2303.dbc
Baixando: STSP2304.dbc
Sucesso: STSP2304.dbc
Baixando: STSP2305.dbc
Sucesso: STSP2305.dbc
Baixando: STSP2306.dbc
Sucesso: STSP2306.dbc
Baixando: STSP2307.dbc
Sucesso: STSP2307.dbc
Baixando: STSP2308.dbc
Sucesso: STSP2308.dbc
Baixando: STSP2309.dbc
Sucesso: STSP2309.dbc
Baixando: STSP2310.dbc
Sucesso: STSP2310.dbc
Baixando: STSP2312.dbc
Sucesso: STSP2312.dbc
Baixando: STSP2401.dbc
Sucesso: STSP2401.dbc
Baixando: STSP2402.dbc
Sucesso: STSP2402.dbc
Baixando: STSP2403.dbc
Sucesso: STSP2403.dbc
Baixando: STSP2404.dbc
Sucesso: STSP2404.dbc
Baixando: STSP2405.dbc
Sucesso: STSP2405.dbc
Baixando: STSP2406.dbc
Sucesso: STSP2406.dbc
Baixando: STSP2407.dbc
Sucesso: STSP2407.dbc
Baixando: STSP2408.dbc
Sucesso: STSP2408.dbc
Baixando: STSP2409.dbc
Sucesso: STSP2409.dbc
Baixando: STSP2410.dbc
Sucesso: STSP2410.dbc
Baixando: STSP2412.dbc
Sucesso: STSP2412.dbc
Baixando: STSP2501.dbc
Sucesso: STSP2501.dbc
Baixando: STSP2502.dbc
Sucesso: STSP2502.dbc
Baixando: STSP2503.dbc
Sucesso: STSP2503.dbc
Baixando: STSP2504.dbc
Sucesso: STSP2504.dbc
Baixando: STSP2505.dbc
Sucesso: STSP2505.dbc
Baixando: STSP2506.dbc
Sucesso: STSP2506.dbc
Baixando: STSP2507.dbc
Sucesso: STSP2507.dbc
Baixando: STSP2508.dbc
Sucesso: STSP2508.dbc
Baixando: STSP2509.dbc
Sucesso: STSP2509.dbc
Baixando: STSP2510.dbc
Sucesso: STSP2510.dbc
Baixando: STSP2512.dbc
Sucesso: STSP2512.dbc
Baixando: LTSP1501.dbc
Sucesso: LTSP1501.dbc
Baixando: LTSP1502.dbc
Sucesso: LTSP1502.dbc
Baixando: LTSP1503.dbc
Sucesso: LTSP1503.dbc
Baixando: LTSP1504.dbc
Sucesso: LTSP1504.dbc
Baixando: LTSP1505.dbc
Sucesso: LTSP1505.dbc
Baixando: LTSP1506.dbc
Sucesso: LTSP1506.dbc
Baixando: LTSP1507.dbc
Sucesso: LTSP1507.dbc
Baixando: LTSP1508.dbc
Sucesso: LTSP1508.dbc
Baixando: LTSP1509.dbc
Sucesso: LTSP1509.dbc
Baixando: LTSP1510.dbc
Sucesso: LTSP1510.dbc
Baixando: LTSP1512.dbc
Sucesso: LTSP1512.dbc
Baixando: LTSP1601.dbc
Sucesso: LTSP1601.dbc
Baixando: LTSP1602.dbc
Sucesso: LTSP1602.dbc
Baixando: LTSP1603.dbc
Sucesso: LTSP1603.dbc
Baixando: LTSP1604.dbc
Sucesso: LTSP1604.dbc
Baixando: LTSP1605.dbc
Sucesso: LTSP1605.dbc
Baixando: LTSP1606.dbc
Sucesso: LTSP1606.dbc
Baixando: LTSP1607.dbc
Sucesso: LTSP1607.dbc
Baixando: LTSP1608.dbc
Sucesso: LTSP1608.dbc
Baixando: LTSP1609.dbc
Sucesso: LTSP1609.dbc
Baixando: LTSP1610.dbc
Sucesso: LTSP1610.dbc
Baixando: LTSP1612.dbc
Sucesso: LTSP1612.dbc
Baixando: LTSP1701.dbc
Sucesso: LTSP1701.dbc
Baixando: LTSP1702.dbc
Sucesso: LTSP1702.dbc
Baixando: LTSP1703.dbc
Sucesso: LTSP1703.dbc
Baixando: LTSP1704.dbc
Sucesso: LTSP1704.dbc
Baixando: LTSP1705.dbc
Sucesso: LTSP1705.dbc
Baixando: LTSP1706.dbc
Sucesso: LTSP1706.dbc
Baixando: LTSP1707.dbc
Sucesso: LTSP1707.dbc
Baixando: LTSP1708.dbc
Sucesso: LTSP1708.dbc
Baixando: LTSP1709.dbc
Sucesso: LTSP1709.dbc
Baixando: LTSP1710.dbc
Sucesso: LTSP1710.dbc
Baixando: LTSP1712.dbc
Sucesso: LTSP1712.dbc
Baixando: LTSP1801.dbc
Sucesso: LTSP1801.dbc
Baixando: LTSP1802.dbc
Sucesso: LTSP1802.dbc
Baixando: LTSP1803.dbc
Sucesso: LTSP1803.dbc
Baixando: LTSP1804.dbc
Sucesso: LTSP1804.dbc
Baixando: LTSP1805.dbc
Sucesso: LTSP1805.dbc
Baixando: LTSP1806.dbc
Sucesso: LTSP1806.dbc
Baixando: LTSP1807.dbc
Sucesso: LTSP1807.dbc
Baixando: LTSP1808.dbc
Sucesso: LTSP1808.dbc
Baixando: LTSP1809.dbc
Sucesso: LTSP1809.dbc
Baixando: LTSP1810.dbc
Sucesso: LTSP1810.dbc
Baixando: LTSP1812.dbc
Sucesso: LTSP1812.dbc
Baixando: LTSP1901.dbc
Sucesso: LTSP1901.dbc
Baixando: LTSP1902.dbc
Sucesso: LTSP1902.dbc
Baixando: LTSP1903.dbc
Sucesso: LTSP1903.dbc
Baixando: LTSP1904.dbc
Sucesso: LTSP1904.dbc
Baixando: LTSP1905.dbc
Sucesso: LTSP1905.dbc
Baixando: LTSP1906.dbc
Sucesso: LTSP1906.dbc
Baixando: LTSP1907.dbc
Sucesso: LTSP1907.dbc
Baixando: LTSP1908.dbc
Sucesso: LTSP1908.dbc
Baixando: LTSP1909.dbc
Sucesso: LTSP1909.dbc
Baixando: LTSP1910.dbc
Sucesso: LTSP1910.dbc
Baixando: LTSP1912.dbc
Sucesso: LTSP1912.dbc
Baixando: LTSP2001.dbc
Sucesso: LTSP2001.dbc
Baixando: LTSP2002.dbc
Sucesso: LTSP2002.dbc
Baixando: LTSP2003.dbc
Sucesso: LTSP2003.dbc
Baixando: LTSP2004.dbc
Sucesso: LTSP2004.dbc
Baixando: LTSP2005.dbc
Sucesso: LTSP2005.dbc
Baixando: LTSP2006.dbc
Sucesso: LTSP2006.dbc
Baixando: LTSP2007.dbc
Sucesso: LTSP2007.dbc
Baixando: LTSP2008.dbc
Sucesso: LTSP2008.dbc
Baixando: LTSP2009.dbc
Sucesso: LTSP2009.dbc
Baixando: LTSP2010.dbc
Sucesso: LTSP2010.dbc
Baixando: LTSP2012.dbc
Sucesso: LTSP2012.dbc
Baixando: LTSP2101.dbc
Sucesso: LTSP2101.dbc
Baixando: LTSP2102.dbc
Sucesso: LTSP2102.dbc
Baixando: LTSP2103.dbc
Sucesso: LTSP2103.dbc
Baixando: LTSP2104.dbc
Sucesso: LTSP2104.dbc
Baixando: LTSP2105.dbc
Sucesso: LTSP2105.dbc
Baixando: LTSP2106.dbc
Sucesso: LTSP2106.dbc
Baixando: LTSP2107.dbc
Sucesso: LTSP2107.dbc
Baixando: LTSP2108.dbc
Sucesso: LTSP2108.dbc
Baixando: LTSP2109.dbc
Sucesso: LTSP2109.dbc
Baixando: LTSP2110.dbc
Sucesso: LTSP2110.dbc
Baixando: LTSP2112.dbc
Sucesso: LTSP2112.dbc
Baixando: LTSP2201.dbc
Sucesso: LTSP2201.dbc
Baixando: LTSP2202.dbc
Sucesso: LTSP2202.dbc
Baixando: LTSP2203.dbc
Sucesso: LTSP2203.dbc
Baixando: LTSP2204.dbc
Sucesso: LTSP2204.dbc
Baixando: LTSP2205.dbc
Sucesso: LTSP2205.dbc
Baixando: LTSP2206.dbc
Sucesso: LTSP2206.dbc
Baixando: LTSP2207.dbc
Sucesso: LTSP2207.dbc
Baixando: LTSP2208.dbc
Sucesso: LTSP2208.dbc
Baixando: LTSP2209.dbc
Sucesso: LTSP2209.dbc
Baixando: LTSP2210.dbc
Sucesso: LTSP2210.dbc
Baixando: LTSP2212.dbc
Sucesso: LTSP2212.dbc
Baixando: LTSP2301.dbc
Sucesso: LTSP2301.dbc
Baixando: LTSP2302.dbc
Sucesso: LTSP2302.dbc
Baixando: LTSP2303.dbc
Sucesso: LTSP2303.dbc
Baixando: LTSP2304.dbc
Sucesso: LTSP2304.dbc
Baixando: LTSP2305.dbc
Sucesso: LTSP2305.dbc
Baixando: LTSP2306.dbc
Sucesso: LTSP2306.dbc
Baixando: LTSP2307.dbc
Sucesso: LTSP2307.dbc
Baixando: LTSP2308.dbc
Sucesso: LTSP2308.dbc
Baixando: LTSP2309.dbc
Sucesso: LTSP2309.dbc
Baixando: LTSP2310.dbc
Sucesso: LTSP2310.dbc
Baixando: LTSP2312.dbc
Sucesso: LTSP2312.dbc
Baixando: LTSP2401.dbc
Sucesso: LTSP2401.dbc
Baixando: LTSP2402.dbc
Sucesso: LTSP2402.dbc
Baixando: LTSP2403.dbc
Sucesso: LTSP2403.dbc
Baixando: LTSP2404.dbc
Sucesso: LTSP2404.dbc
Baixando: LTSP2405.dbc
Sucesso: LTSP2405.dbc
Baixando: LTSP2406.dbc
Sucesso: LTSP2406.dbc
Baixando: LTSP2407.dbc
Sucesso: LTSP2407.dbc
Baixando: LTSP2408.dbc
Sucesso: LTSP2408.dbc
Baixando: LTSP2409.dbc
Sucesso: LTSP2409.dbc
Baixando: LTSP2410.dbc
Sucesso: LTSP2410.dbc
Baixando: LTSP2412.dbc
Sucesso: LTSP2412.dbc
Baixando: LTSP2501.dbc
Sucesso: LTSP2501.dbc
Baixando: LTSP2502.dbc
Sucesso: LTSP2502.dbc
Baixando: LTSP2503.dbc
Sucesso: LTSP2503.dbc
Baixando: LTSP2504.dbc
Sucesso: LTSP2504.dbc
Baixando: LTSP2505.dbc
Sucesso: LTSP2505.dbc
Baixando: LTSP2506.dbc
Sucesso: LTSP2506.dbc
Baixando: LTSP2507.dbc
Sucesso: LTSP2507.dbc
Baixando: LTSP2508.dbc
Sucesso: LTSP2508.dbc
Baixando: LTSP2509.dbc
Sucesso: LTSP2509.dbc
Baixando: LTSP2510.dbc
Sucesso: LTSP2510.dbc
Baixando: LTSP2512.dbc
Sucesso: LTSP2512.dbc
Baixando: EQSP1501.dbc
Sucesso: EQSP1501.dbc
Baixando: EQSP1502.dbc
Sucesso: EQSP1502.dbc
Baixando: EQSP1503.dbc
Sucesso: EQSP1503.dbc
Baixando: EQSP1504.dbc
Sucesso: EQSP1504.dbc
Baixando: EQSP1505.dbc
Sucesso: EQSP1505.dbc
Baixando: EQSP1506.dbc
Sucesso: EQSP1506.dbc
Baixando: EQSP1507.dbc
Sucesso: EQSP1507.dbc
Baixando: EQSP1508.dbc
Sucesso: EQSP1508.dbc
Baixando: EQSP1509.dbc
Sucesso: EQSP1509.dbc
Baixando: EQSP1510.dbc
Sucesso: EQSP1510.dbc
Baixando: EQSP1512.dbc
Sucesso: EQSP1512.dbc
Baixando: EQSP1601.dbc
Sucesso: EQSP1601.dbc
Baixando: EQSP1602.dbc
Sucesso: EQSP1602.dbc
Baixando: EQSP1603.dbc
Sucesso: EQSP1603.dbc
Baixando: EQSP1604.dbc
Sucesso: EQSP1604.dbc
Baixando: EQSP1605.dbc
Sucesso: EQSP1605.dbc
Baixando: EQSP1606.dbc
Sucesso: EQSP1606.dbc
Baixando: EQSP1607.dbc
Sucesso: EQSP1607.dbc
Baixando: EQSP1608.dbc
Sucesso: EQSP1608.dbc
Baixando: EQSP1609.dbc
Sucesso: EQSP1609.dbc
Baixando: EQSP1610.dbc
Sucesso: EQSP1610.dbc
Baixando: EQSP1612.dbc
Sucesso: EQSP1612.dbc
Baixando: EQSP1701.dbc
Sucesso: EQSP1701.dbc
Baixando: EQSP1702.dbc
Sucesso: EQSP1702.dbc
Baixando: EQSP1703.dbc
Sucesso: EQSP1703.dbc
Baixando: EQSP1704.dbc
Sucesso: EQSP1704.dbc
Baixando: EQSP1705.dbc
Sucesso: EQSP1705.dbc
Baixando: EQSP1706.dbc
Sucesso: EQSP1706.dbc
Baixando: EQSP1707.dbc
Sucesso: EQSP1707.dbc
Baixando: EQSP1708.dbc
Sucesso: EQSP1708.dbc
Baixando: EQSP1709.dbc
Sucesso: EQSP1709.dbc
Baixando: EQSP1710.dbc
Sucesso: EQSP1710.dbc
Baixando: EQSP1712.dbc
Sucesso: EQSP1712.dbc
Baixando: EQSP1801.dbc
Sucesso: EQSP1801.dbc
Baixando: EQSP1802.dbc
Sucesso: EQSP1802.dbc
Baixando: EQSP1803.dbc
Sucesso: EQSP1803.dbc
Baixando: EQSP1804.dbc
Sucesso: EQSP1804.dbc
Baixando: EQSP1805.dbc
Sucesso: EQSP1805.dbc
Baixando: EQSP1806.dbc
Sucesso: EQSP1806.dbc
Baixando: EQSP1807.dbc
Sucesso: EQSP1807.dbc
Baixando: EQSP1808.dbc
Sucesso: EQSP1808.dbc
Baixando: EQSP1809.dbc
Sucesso: EQSP1809.dbc
Baixando: EQSP1810.dbc
Sucesso: EQSP1810.dbc
Baixando: EQSP1812.dbc
Sucesso: EQSP1812.dbc
Baixando: EQSP1901.dbc
Sucesso: EQSP1901.dbc
Baixando: EQSP1902.dbc
Sucesso: EQSP1902.dbc
Baixando: EQSP1903.dbc
Sucesso: EQSP1903.dbc
Baixando: EQSP1904.dbc
Sucesso: EQSP1904.dbc
Baixando: EQSP1905.dbc
Sucesso: EQSP1905.dbc
Baixando: EQSP1906.dbc
Sucesso: EQSP1906.dbc
Baixando: EQSP1907.dbc
Sucesso: EQSP1907.dbc
Baixando: EQSP1908.dbc
Sucesso: EQSP1908.dbc
Baixando: EQSP1909.dbc
Sucesso: EQSP1909.dbc
Baixando: EQSP1910.dbc
Sucesso: EQSP1910.dbc
Baixando: EQSP1912.dbc
Sucesso: EQSP1912.dbc
Baixando: EQSP2001.dbc
Sucesso: EQSP2001.dbc
Baixando: EQSP2002.dbc
Sucesso: EQSP2002.dbc
Baixando: EQSP2003.dbc
Sucesso: EQSP2003.dbc
Baixando: EQSP2004.dbc
Sucesso: EQSP2004.dbc
Baixando: EQSP2005.dbc
Sucesso: EQSP2005.dbc
Baixando: EQSP2006.dbc
Sucesso: EQSP2006.dbc
Baixando: EQSP2007.dbc
Sucesso: EQSP2007.dbc
Baixando: EQSP2008.dbc
Sucesso: EQSP2008.dbc
Baixando: EQSP2009.dbc
Sucesso: EQSP2009.dbc
Baixando: EQSP2010.dbc
Sucesso: EQSP2010.dbc
Baixando: EQSP2012.dbc
Sucesso: EQSP2012.dbc
Baixando: EQSP2101.dbc
Sucesso: EQSP2101.dbc
Baixando: EQSP2102.dbc
Sucesso: EQSP2102.dbc
Baixando: EQSP2103.dbc
Sucesso: EQSP2103.dbc
Baixando: EQSP2104.dbc
Sucesso: EQSP2104.dbc
Baixando: EQSP2105.dbc
Sucesso: EQSP2105.dbc
Baixando: EQSP2106.dbc
Sucesso: EQSP2106.dbc
Baixando: EQSP2107.dbc
Sucesso: EQSP2107.dbc
Baixando: EQSP2108.dbc
Sucesso: EQSP2108.dbc
Baixando: EQSP2109.dbc
Sucesso: EQSP2109.dbc
Baixando: EQSP2110.dbc
Sucesso: EQSP2110.dbc
Baixando: EQSP2112.dbc
Sucesso: EQSP2112.dbc
Baixando: EQSP2201.dbc
Sucesso: EQSP2201.dbc
Baixando: EQSP2202.dbc
Sucesso: EQSP2202.dbc
Baixando: EQSP2203.dbc
Sucesso: EQSP2203.dbc
Baixando: EQSP2204.dbc
Sucesso: EQSP2204.dbc
Baixando: EQSP2205.dbc
Sucesso: EQSP2205.dbc
Baixando: EQSP2206.dbc
Sucesso: EQSP2206.dbc
Baixando: EQSP2207.dbc
Sucesso: EQSP2207.dbc
Baixando: EQSP2208.dbc
Sucesso: EQSP2208.dbc
Baixando: EQSP2209.dbc
Sucesso: EQSP2209.dbc
Baixando: EQSP2210.dbc
Sucesso: EQSP2210.dbc
Baixando: EQSP2212.dbc
Sucesso: EQSP2212.dbc
Baixando: EQSP2301.dbc
Sucesso: EQSP2301.dbc
Baixando: EQSP2302.dbc
Sucesso: EQSP2302.dbc
Baixando: EQSP2303.dbc
Sucesso: EQSP2303.dbc
Baixando: EQSP2304.dbc
Sucesso: EQSP2304.dbc
Baixando: EQSP2305.dbc
Sucesso: EQSP2305.dbc
Baixando: EQSP2306.dbc
Sucesso: EQSP2306.dbc
Baixando: EQSP2307.dbc
Sucesso: EQSP2307.dbc
Baixando: EQSP2308.dbc
Sucesso: EQSP2308.dbc
Baixando: EQSP2309.dbc
Sucesso: EQSP2309.dbc
Baixando: EQSP2310.dbc
Sucesso: EQSP2310.dbc
Baixando: EQSP2312.dbc
Sucesso: EQSP2312.dbc
Baixando: EQSP2401.dbc
Sucesso: EQSP2401.dbc
Baixando: EQSP2402.dbc
Sucesso: EQSP2402.dbc
Baixando: EQSP2403.dbc
Sucesso: EQSP2403.dbc
Baixando: EQSP2404.dbc
Sucesso: EQSP2404.dbc
Baixando: EQSP2405.dbc
Sucesso: EQSP2405.dbc
Baixando: EQSP2406.dbc
Sucesso: EQSP2406.dbc
Baixando: EQSP2407.dbc
Sucesso: EQSP2407.dbc
Baixando: EQSP2408.dbc
Sucesso: EQSP2408.dbc
Baixando: EQSP2409.dbc
Sucesso: EQSP2409.dbc
Baixando: EQSP2410.dbc
Sucesso: EQSP2410.dbc
Baixando: EQSP2412.dbc
Sucesso: EQSP2412.dbc
Baixando: EQSP2501.dbc
Sucesso: EQSP2501.dbc
Baixando: EQSP2502.dbc
Sucesso: EQSP2502.dbc
Baixando: EQSP2503.dbc
Sucesso: EQSP2503.dbc
Baixando: EQSP2504.dbc
Sucesso: EQSP2504.dbc
Baixando: EQSP2505.dbc
Sucesso: EQSP2505.dbc
Baixando: EQSP2506.dbc
Sucesso: EQSP2506.dbc
Baixando: EQSP2507.dbc
Sucesso: EQSP2507.dbc
Baixando: EQSP2508.dbc
Sucesso: EQSP2508.dbc
Baixando: EQSP2509.dbc
Sucesso: EQSP2509.dbc
Baixando: EQSP2510.dbc
Sucesso: EQSP2510.dbc
Baixando: EQSP2512.dbc
Sucesso: EQSP2512.dbc
Baixando: HBSP1501.dbc
Sucesso: HBSP1501.dbc
Baixando: HBSP1502.dbc
Sucesso: HBSP1502.dbc
Baixando: HBSP1503.dbc
Sucesso: HBSP1503.dbc
Baixando: HBSP1504.dbc
Sucesso: HBSP1504.dbc
Baixando: HBSP1505.dbc
Sucesso: HBSP1505.dbc
Baixando: HBSP1506.dbc
Sucesso: HBSP1506.dbc
Baixando: HBSP1507.dbc
Sucesso: HBSP1507.dbc
Baixando: HBSP1508.dbc
Sucesso: HBSP1508.dbc
Baixando: HBSP1509.dbc
Sucesso: HBSP1509.dbc
Baixando: HBSP1510.dbc
Sucesso: HBSP1510.dbc
Baixando: HBSP1512.dbc
Sucesso: HBSP1512.dbc
Baixando: HBSP1601.dbc
Sucesso: HBSP1601.dbc
Baixando: HBSP1602.dbc
Sucesso: HBSP1602.dbc
Baixando: HBSP1603.dbc
Sucesso: HBSP1603.dbc
Baixando: HBSP1604.dbc
Sucesso: HBSP1604.dbc
Baixando: HBSP1605.dbc
Sucesso: HBSP1605.dbc
Baixando: HBSP1606.dbc
Sucesso: HBSP1606.dbc
Baixando: HBSP1607.dbc
Sucesso: HBSP1607.dbc
Baixando: HBSP1608.dbc
Sucesso: HBSP1608.dbc
Baixando: HBSP1609.dbc
Sucesso: HBSP1609.dbc
Baixando: HBSP1610.dbc
Sucesso: HBSP1610.dbc
Baixando: HBSP1612.dbc
Sucesso: HBSP1612.dbc
Baixando: HBSP1701.dbc
Sucesso: HBSP1701.dbc
Baixando: HBSP1702.dbc
Sucesso: HBSP1702.dbc
Baixando: HBSP1703.dbc
Sucesso: HBSP1703.dbc
Baixando: HBSP1704.dbc
Sucesso: HBSP1704.dbc
Baixando: HBSP1705.dbc
Sucesso: HBSP1705.dbc
Baixando: HBSP1706.dbc
Sucesso: HBSP1706.dbc
Baixando: HBSP1707.dbc
Sucesso: HBSP1707.dbc
Baixando: HBSP1708.dbc
Sucesso: HBSP1708.dbc
Baixando: HBSP1709.dbc
Sucesso: HBSP1709.dbc
Baixando: HBSP1710.dbc
Sucesso: HBSP1710.dbc
Baixando: HBSP1712.dbc
Sucesso: HBSP1712.dbc
Baixando: HBSP1801.dbc
Sucesso: HBSP1801.dbc
Baixando: HBSP1802.dbc
Sucesso: HBSP1802.dbc
Baixando: HBSP1803.dbc
Sucesso: HBSP1803.dbc
Baixando: HBSP1804.dbc
Sucesso: HBSP1804.dbc
Baixando: HBSP1805.dbc
Sucesso: HBSP1805.dbc
Baixando: HBSP1806.dbc
Sucesso: HBSP1806.dbc
Baixando: HBSP1807.dbc
Sucesso: HBSP1807.dbc
Baixando: HBSP1808.dbc
Sucesso: HBSP1808.dbc
Baixando: HBSP1809.dbc
Sucesso: HBSP1809.dbc
Baixando: HBSP1810.dbc
Sucesso: HBSP1810.dbc
Baixando: HBSP1812.dbc
Sucesso: HBSP1812.dbc
Baixando: HBSP1901.dbc
Sucesso: HBSP1901.dbc
Baixando: HBSP1902.dbc
Sucesso: HBSP1902.dbc
Baixando: HBSP1903.dbc
Sucesso: HBSP1903.dbc
Baixando: HBSP1904.dbc
Sucesso: HBSP1904.dbc
Baixando: HBSP1905.dbc
Sucesso: HBSP1905.dbc
Baixando: HBSP1906.dbc
Sucesso: HBSP1906.dbc
Baixando: HBSP1907.dbc
Sucesso: HBSP1907.dbc
Baixando: HBSP1908.dbc
Sucesso: HBSP1908.dbc
Baixando: HBSP1909.dbc
Sucesso: HBSP1909.dbc
Baixando: HBSP1910.dbc
Sucesso: HBSP1910.dbc
Baixando: HBSP1912.dbc
Sucesso: HBSP1912.dbc
Baixando: HBSP2001.dbc
Sucesso: HBSP2001.dbc
Baixando: HBSP2002.dbc
Sucesso: HBSP2002.dbc
Baixando: HBSP2003.dbc
Sucesso: HBSP2003.dbc
Baixando: HBSP2004.dbc
Sucesso: HBSP2004.dbc
Baixando: HBSP2005.dbc
Sucesso: HBSP2005.dbc
Baixando: HBSP2006.dbc
Sucesso: HBSP2006.dbc
Baixando: HBSP2007.dbc
Sucesso: HBSP2007.dbc
Baixando: HBSP2008.dbc
Sucesso: HBSP2008.dbc
Baixando: HBSP2009.dbc
Sucesso: HBSP2009.dbc
Baixando: HBSP2010.dbc
Sucesso: HBSP2010.dbc
Baixando: HBSP2012.dbc
Sucesso: HBSP2012.dbc
Baixando: HBSP2101.dbc
Sucesso: HBSP2101.dbc
Baixando: HBSP2102.dbc
Sucesso: HBSP2102.dbc
Baixando: HBSP2103.dbc
Sucesso: HBSP2103.dbc
Baixando: HBSP2104.dbc
Sucesso: HBSP2104.dbc
Baixando: HBSP2105.dbc
Sucesso: HBSP2105.dbc
Baixando: HBSP2106.dbc
Sucesso: HBSP2106.dbc
Baixando: HBSP2107.dbc
Sucesso: HBSP2107.dbc
Baixando: HBSP2108.dbc
Sucesso: HBSP2108.dbc
Baixando: HBSP2109.dbc
Sucesso: HBSP2109.dbc
Baixando: HBSP2110.dbc
Sucesso: HBSP2110.dbc
Baixando: HBSP2112.dbc
Sucesso: HBSP2112.dbc
Baixando: HBSP2201.dbc
Sucesso: HBSP2201.dbc
Baixando: HBSP2202.dbc
Sucesso: HBSP2202.dbc
Baixando: HBSP2203.dbc

In [13]:
# Conversão .dbc → .csv
print("Convertendo arquivos CNES de .dbc para .csv...")
converter_dbc_para_csv_lote(str(PASTA_RAW_CNES), str(PASTA_INPUT_CNES))

Convertendo arquivos CNES de .dbc para .csv...
Processando: STSP1810.dbc
Concluído: stsp1810.csv
Processando: SRSP1807.dbc
Concluído: srsp1807.csv
Processando: EQSP2404.dbc
Concluído: eqsp2404.csv
Processando: HBSP1504.dbc
Concluído: hbsp1504.csv
Processando: EQSP1907.dbc
Concluído: eqsp1907.csv
Processando: EQSP1504.dbc
Concluído: eqsp1504.csv
Processando: LTSP1709.dbc
Concluído: ltsp1709.csv
Processando: HBSP2201.dbc
Concluído: hbsp2201.csv
Processando: STSP2212.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2212.csv
Processando: HBSP2402.dbc
Concluído: hbsp2402.csv
Processando: LTSP2206.dbc
Concluído: ltsp2206.csv
Processando: EQSP2208.dbc
Concluído: eqsp2208.csv
Processando: STSP2505.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2505.csv
Processando: LTSP2108.dbc
Concluído: ltsp2108.csv
Processando: EQSP1804.dbc
Concluído: eqsp1804.csv
Processando: STSP2004.dbc
Erro na conversão: Unknown field type: ' '
Concluído: stsp2004.csv
Processando: HBSP1706.dbc
Concluído: hbsp1706.csv
Processando: HBSP2104.dbc
Concluído: hbsp2104.csv
Processando: EQSP2412.dbc
Concluído: eqsp2412.csv
Processando: LTSP2008.dbc
Concluído: ltsp2008.csv
Processando: HBSP2205.dbc
Concluído: hbsp2205.csv
Processando: STSP1705.dbc
Concluído: stsp1705.csv
Processando: LTSP2103.dbc
Concluído: ltsp2103.csv
Processando: STSP2507.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2507.csv
Processando: HBSP2212.dbc
Concluído: hbsp2212.csv
Processando: HBSP2410.dbc
Concluído: hbsp2410.csv
Processando: HBSP2407.dbc
Concluído: hbsp2407.csv
Processando: HBSP2408.dbc
Concluído: hbsp2408.csv
Processando: HBSP2208.dbc
Concluído: hbsp2208.csv
Processando: HBSP2508.dbc
Concluído: hbsp2508.csv
Processando: HBSP2008.dbc
Concluído: hbsp2008.csv
Processando: STSP1512.dbc
Concluído: stsp1512.csv
Processando: HBSP2306.dbc
Concluído: hbsp2306.csv
Processando: EQSP2509.dbc
Concluído: eqsp2509.csv
Processando: STSP1909.dbc
Concluído: stsp1909.csv
Processando: STSP2501.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2501.csv
Processando: HBSP1602.dbc
Concluído: hbsp1602.csv
Processando: SRSP2109.dbc
Concluído: srsp2109.csv
Processando: EQSP2408.dbc
Concluído: eqsp2408.csv
Processando: SRSP2009.dbc
Concluído: srsp2009.csv
Processando: HBSP1912.dbc
Concluído: hbsp1912.csv
Processando: HBSP1601.dbc
Concluído: hbsp1601.csv
Processando: STSP1908.dbc
Concluído: stsp1908.csv
Processando: SRSP1802.dbc
Concluído: srsp1802.csv
Processando: STSP2101.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2101.csv
Processando: LTSP1710.dbc
Concluído: ltsp1710.csv
Processando: EQSP2501.dbc
Concluído: eqsp2501.csv
Processando: SRSP2008.dbc
Concluído: srsp2008.csv
Processando: SRSP2003.dbc
Concluído: srsp2003.csv
Processando: LTSP2003.dbc
Concluído: ltsp2003.csv
Processando: LTSP2009.dbc
Concluído: ltsp2009.csv
Processando: EQSP1707.dbc
Concluído: eqsp1707.csv
Processando: LTSP2106.dbc
Concluído: ltsp2106.csv
Processando: SRSP2306.dbc
Concluído: srsp2306.csv
Processando: HBSP2504.dbc
Concluído: hbsp2504.csv
Processando: SRSP2103.dbc
Concluído: srsp2103.csv
Processando: STSP2102.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2102.csv
Processando: SRSP1708.dbc
Concluído: srsp1708.csv
Processando: SRSP2404.dbc
Concluído: srsp2404.csv
Processando: EQSP2508.dbc
Concluído: eqsp2508.csv
Processando: LTSP2407.dbc
Concluído: ltsp2407.csv
Processando: STSP2509.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2509.csv
Processando: EQSP1601.dbc
Concluído: eqsp1601.csv
Processando: STSP2103.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2103.csv
Processando: EQSP1706.dbc
Concluído: eqsp1706.csv
Processando: SRSP2204.dbc
Concluído: srsp2204.csv
Processando: EQSP2006.dbc
Concluído: eqsp2006.csv
Processando: EQSP1605.dbc
Concluído: eqsp1605.csv
Processando: SRSP1608.dbc
Concluído: srsp1608.csv
Processando: EQSP2007.dbc
Concluído: eqsp2007.csv
Processando: STSP1501.dbc
Concluído: stsp1501.csv
Processando: STSP1707.dbc
Concluído: stsp1707.csv
Processando: EQSP1609.dbc
Concluído: eqsp1609.csv
Processando: SRSP2309.dbc
Concluído: srsp2309.csv
Processando: STSP1804.dbc
Concluído: stsp1804.csv
Processando: SRSP1703.dbc
Concluído: srsp1703.csv
Processando: STSP1709.dbc
Concluído: stsp1709.csv
Processando: HBSP1607.dbc
Concluído: hbsp1607.csv
Processando: EQSP1508.dbc
Concluído: eqsp1508.csv
Processando: LTSP1509.dbc
Concluído: ltsp1509.csv
Processando: SRSP2202.dbc
Concluído: srsp2202.csv
Processando: HBSP2409.dbc
Concluído: hbsp2409.csv
Processando: EQSP1806.dbc
Concluído: eqsp1806.csv
Processando: STSP2110.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2110.csv
Processando: SRSP1909.dbc
Concluído: srsp1909.csv
Processando: LTSP1504.dbc
Concluído: ltsp1504.csv
Processando: HBSP2503.dbc
Concluído: hbsp2503.csv
Processando: EQSP1912.dbc
Concluído: eqsp1912.csv
Processando: SRSP2102.dbc
Concluído: srsp2102.csv
Processando: HBSP1812.dbc
Concluído: hbsp1812.csv
Processando: EQSP1910.dbc
Concluído: eqsp1910.csv
Processando: LTSP1706.dbc
Concluído: ltsp1706.csv
Processando: HBSP1606.dbc
Concluído: hbsp1606.csv
Processando: LTSP2104.dbc
Concluído: ltsp2104.csv
Processando: HBSP2507.dbc
Concluído: hbsp2507.csv
Processando: LTSP1501.dbc
Concluído: ltsp1501.csv
Processando: LTSP1803.dbc
Concluído: ltsp1803.csv
Processando: STSP1907.dbc
Concluído: stsp1907.csv
Processando: SRSP1712.dbc
Concluído: srsp1712.csv
Processando: EQSP1505.dbc
Concluído: eqsp1505.csv
Processando: HBSP2002.dbc
Concluído: hbsp2002.csv
Processando: STSP2303.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2303.csv
Processando: LTSP1602.dbc
Concluído: ltsp1602.csv
Processando: STSP1504.dbc
Concluído: stsp1504.csv
Processando: EQSP1809.dbc
Concluído: eqsp1809.csv
Processando: EQSP2310.dbc
Concluído: eqsp2310.csv
Processando: HBSP1901.dbc
Concluído: hbsp1901.csv
Processando: HBSP2206.dbc
Concluído: hbsp2206.csv
Processando: STSP1610.dbc
Concluído: stsp1610.csv
Processando: EQSP1807.dbc
Concluído: eqsp1807.csv
Processando: EQSP2005.dbc
Concluído: eqsp2005.csv
Processando: HBSP1902.dbc
Concluído: hbsp1902.csv
Processando: STSP2310.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2310.csv
Processando: EQSP2410.dbc
Concluído: eqsp2410.csv
Processando: STSP2409.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2409.csv
Processando: HBSP1710.dbc
Concluído: hbsp1710.csv
Processando: LTSP1712.dbc
Concluído: ltsp1712.csv
Processando: LTSP2202.dbc
Concluído: ltsp2202.csv
Processando: SRSP2212.dbc
Concluído: srsp2212.csv
Processando: SRSP1812.dbc
Concluído: srsp1812.csv
Processando: EQSP1705.dbc
Concluído: eqsp1705.csv
Processando: STSP2506.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2506.csv
Processando: SRSP2206.dbc
Concluído: srsp2206.csv
Processando: HBSP1804.dbc
Concluído: hbsp1804.csv
Processando: LTSP1508.dbc
Concluído: ltsp1508.csv
Processando: LTSP1608.dbc
Concluído: ltsp1608.csv
Processando: EQSP2002.dbc
Concluído: eqsp2002.csv
Processando: LTSP2109.dbc
Concluído: ltsp2109.csv
Processando: STSP1612.dbc
Concluído: stsp1612.csv
Processando: EQSP1802.dbc
Concluído: eqsp1802.csv
Processando: STSP2007.dbc
Erro na conversão: Unknown field type: ' '
Concluído: stsp2007.csv
Processando: HBSP2302.dbc
Concluído: hbsp2302.csv
Processando: LTSP2001.dbc
Concluído: ltsp2001.csv
Processando: EQSP1709.dbc
Concluído: eqsp1709.csv
Processando: HBSP2103.dbc
Concluído: hbsp2103.csv
Processando: STSP2307.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2307.csv
Processando: HBSP2102.dbc
Concluído: hbsp2102.csv
Processando: EQSP1902.dbc
Concluído: eqsp1902.csv
Processando: EQSP2203.dbc
Concluído: eqsp2203.csv
Processando: LTSP2006.dbc
Concluído: ltsp2006.csv
Processando: EQSP2301.dbc
Concluído: eqsp2301.csv
Processando: EQSP2010.dbc
Concluído: eqsp2010.csv
Processando: SRSP1604.dbc
Concluído: srsp1604.csv
Processando: LTSP2305.dbc
Concluído: ltsp2305.csv
Processando: EQSP1903.dbc
Concluído: eqsp1903.csv
Processando: LTSP1704.dbc
Concluído: ltsp1704.csv
Processando: SRSP1805.dbc
Concluído: srsp1805.csv
Processando: LTSP1808.dbc
Concluído: ltsp1808.csv
Processando: SRSP1902.dbc
Concluído: srsp1902.csv
Processando: LTSP1703.dbc
Concluído: ltsp1703.csv
Processando: EQSP2309.dbc
Concluído: eqsp2309.csv
Processando: EQSP2303.dbc
Concluído: eqsp2303.csv
Processando: EQSP2209.dbc
Concluído: eqsp2209.csv
Processando: LTSP1502.dbc
Concluído: ltsp1502.csv
Processando: STSP2112.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2112.csv
Processando: EQSP2506.dbc
Concluído: eqsp2506.csv
Processando: HBSP1806.dbc
Concluído: hbsp1806.csv
Processando: SRSP2310.dbc
Concluído: srsp2310.csv
Processando: SRSP2110.dbc
Concluído: srsp2110.csv
Processando: SRSP2305.dbc
Concluído: srsp2305.csv
Processando: LTSP2501.dbc
Concluído: ltsp2501.csv
Processando: LTSP1903.dbc
Concluído: ltsp1903.csv
Processando: STSP2010.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2010.csv
Processando: STSP1704.dbc
Concluído: stsp1704.csv
Processando: EQSP1510.dbc
Concluído: eqsp1510.csv
Processando: SRSP2210.dbc
Concluído: srsp2210.csv
Processando: HBSP1809.dbc
Concluído: hbsp1809.csv
Processando: LTSP2403.dbc
Concluído: ltsp2403.csv
Processando: LTSP2404.dbc
Concluído: ltsp2404.csv
Processando: STSP1904.dbc
Concluído: stsp1904.csv
Processando: LTSP2402.dbc
Concluído: ltsp2402.csv
Processando: LTSP1503.dbc
Concluído: ltsp1503.csv
Processando: HBSP2101.dbc
Concluído: hbsp2101.csv
Processando: LTSP2105.dbc
Concluído: ltsp2105.csv
Processando: SRSP2205.dbc
Concluído: srsp2205.csv
Processando: LTSP1506.dbc
Concluído: ltsp1506.csv
Processando: LTSP2508.dbc
Concluído: ltsp2508.csv
Processando: LTSP2005.dbc
Concluído: ltsp2005.csv
Processando: HBSP1802.dbc
Concluído: hbsp1802.csv
Processando: LTSP1505.dbc
Concluído: ltsp1505.csv
Processando: LTSP1912.dbc
Concluído: ltsp1912.csv
Processando: EQSP2101.dbc
Concluído: eqsp2101.csv
Processando: EQSP2505.dbc
Concluído: eqsp2505.csv
Processando: LTSP1701.dbc
Concluído: ltsp1701.csv
Processando: STSP2312.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2312.csv
Processando: HBSP1612.dbc
Concluído: hbsp1612.csv
Processando: SRSP1512.dbc
Concluído: srsp1512.csv
Processando: SRSP1705.dbc
Concluído: srsp1705.csv
Processando: HBSP1808.dbc
Concluído: hbsp1808.csv
Processando: SRSP2007.dbc
Concluído: srsp2007.csv
Processando: HBSP2004.dbc
Concluído: hbsp2004.csv
Processando: STSP1710.dbc
Concluído: stsp1710.csv
Processando: EQSP2504.dbc
Concluído: eqsp2504.csv
Processando: EQSP2306.dbc
Concluído: eqsp2306.csv
Processando: LTSP2408.dbc
Concluído: ltsp2408.csv
Processando: LTSP2110.dbc
Concluído: ltsp2110.csv
Processando: SRSP1901.dbc
Concluído: srsp1901.csv
Processando: EQSP2206.dbc
Concluído: eqsp2206.csv
Processando: LTSP2504.dbc
Concluído: ltsp2504.csv
Processando: SRSP2504.dbc
Concluído: srsp2504.csv
Processando: HBSP2001.dbc
Concluído: hbsp2001.csv
Processando: HBSP2501.dbc
Concluído: hbsp2501.csv
Processando: LTSP2208.dbc
Concluído: ltsp2208.csv
Processando: STSP2109.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2109.csv
Processando: HBSP1505.dbc
Concluído: hbsp1505.csv
Processando: SRSP1801.dbc
Concluído: srsp1801.csv
Processando: HBSP2005.dbc
Concluído: hbsp2005.csv
Processando: EQSP2012.dbc
Concluído: eqsp2012.csv
Processando: SRSP2407.dbc
Concluído: srsp2407.csv
Processando: STSP1502.dbc
Concluído: stsp1502.csv
Processando: SRSP1503.dbc
Concluído: srsp1503.csv
Processando: LTSP2401.dbc
Concluído: ltsp2401.csv
Processando: EQSP1909.dbc
Concluído: eqsp1909.csv
Processando: SRSP1702.dbc
Concluído: srsp1702.csv
Processando: STSP2009.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2009.csv
Processando: STSP2404.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2404.csv
Processando: HBSP1712.dbc
Concluído: hbsp1712.csv
Processando: SRSP1908.dbc
Concluído: srsp1908.csv
Processando: HBSP2106.dbc
Concluído: hbsp2106.csv
Processando: EQSP1608.dbc
Concluído: eqsp1608.csv
Processando: HBSP2003.dbc
Concluído: hbsp2003.csv
Processando: SRSP2302.dbc
Concluído: srsp2302.csv
Processando: EQSP2405.dbc
Concluído: eqsp2405.csv
Processando: EQSP1606.dbc
Concluído: eqsp1606.csv
Processando: HBSP1508.dbc
Concluído: hbsp1508.csv
Processando: STSP1905.dbc
Concluído: stsp1905.csv
Processando: HBSP1603.dbc
Concluído: hbsp1603.csv
Processando: HBSP2009.dbc
Concluído: hbsp2009.csv
Processando: SRSP2307.dbc
Concluído: srsp2307.csv
Processando: STSP1906.dbc
Concluído: stsp1906.csv
Processando: EQSP1702.dbc
Concluído: eqsp1702.csv
Processando: LTSP1607.dbc
Concluído: ltsp1607.csv
Processando: HBSP1903.dbc
Concluído: hbsp1903.csv
Processando: EQSP2302.dbc
Concluído: eqsp2302.csv
Processando: EQSP1908.dbc
Concluído: eqsp1908.csv
Processando: HBSP2204.dbc
Concluído: hbsp2204.csv
Processando: HBSP1512.dbc
Concluído: hbsp1512.csv
Processando: HBSP1908.dbc
Concluído: hbsp1908.csv
Processando: STSP2301.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2301.csv
Processando: LTSP2304.dbc
Concluído: ltsp2304.csv
Processando: EQSP1805.dbc
Concluído: eqsp1805.csv
Processando: LTSP1801.dbc
Concluído: ltsp1801.csv
Processando: HBSP1507.dbc
Concluído: hbsp1507.csv
Processando: EQSP2103.dbc
Concluído: eqsp2103.csv
Processando: STSP2205.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2205.csv
Processando: HBSP2203.dbc
Concluído: hbsp2203.csv
Processando: SRSP1612.dbc
Concluído: srsp1612.csv
Processando: STSP2002.dbc
Concluído: stsp2002.csv
Processando: LTSP1805.dbc
Concluído: ltsp1805.csv
Processando: SRSP2402.dbc
Concluído: srsp2402.csv
Processando: EQSP1502.dbc
Concluído: eqsp1502.csv
Processando: HBSP2202.dbc
Concluído: hbsp2202.csv
Processando: STSP2412.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2412.csv
Processando: SRSP1808.dbc
Concluído: srsp1808.csv
Processando: HBSP2509.dbc
Concluído: hbsp2509.csv
Processando: STSP2407.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2407.csv
Processando: LTSP1510.dbc
Concluído: ltsp1510.csv
Processando: HBSP2107.dbc
Concluído: hbsp2107.csv
Processando: EQSP1507.dbc
Concluído: eqsp1507.csv
Processando: LTSP1609.dbc
Concluído: ltsp1609.csv
Processando: LTSP1610.dbc
Concluído: ltsp1610.csv
Processando: HBSP2109.dbc
Concluído: hbsp2109.csv
Processando: HBSP1704.dbc
Concluído: hbsp1704.csv
Processando: SRSP2203.dbc
Concluído: srsp2203.csv
Processando: HBSP1502.dbc
Concluído: hbsp1502.csv
Processando: SRSP2101.dbc
Concluído: srsp2101.csv
Processando: SRSP2403.dbc
Concluído: srsp2403.csv
Processando: STSP2105.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2105.csv
Processando: HBSP1609.dbc
Concluído: hbsp1609.csv
Processando: EQSP1901.dbc
Concluído: eqsp1901.csv
Processando: LTSP2101.dbc
Concluído: ltsp2101.csv
Processando: HBSP2301.dbc
Concluído: hbsp2301.csv
Processando: EQSP2105.dbc
Concluído: eqsp2105.csv
Processando: STSP1608.dbc
Concluído: stsp1608.csv
Processando: EQSP1905.dbc
Concluído: eqsp1905.csv
Processando: EQSP2204.dbc
Concluído: eqsp2204.csv
Processando: HBSP2309.dbc
Concluído: hbsp2309.csv
Processando: LTSP2209.dbc
Concluído: ltsp2209.csv
Processando: STSP2210.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2210.csv
Processando: HBSP2401.dbc
Concluído: hbsp2401.csv
Processando: SRSP2502.dbc
Concluído: srsp2502.csv
Processando: EQSP2507.dbc
Concluído: eqsp2507.csv
Processando: STSP2108.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2108.csv
Processando: HBSP2405.dbc
Concluído: hbsp2405.csv
Processando: SRSP1906.dbc
Concluído: srsp1906.csv
Processando: SRSP1508.dbc
Concluído: srsp1508.csv
Processando: EQSP2205.dbc
Concluído: eqsp2205.csv
Processando: STSP1708.dbc
Concluído: stsp1708.csv
Processando: EQSP2503.dbc
Concluído: eqsp2503.csv
Processando: LTSP1707.dbc
Concluído: ltsp1707.csv
Processando: HBSP2110.dbc
Concluído: hbsp2110.csv
Processando: EQSP1503.dbc
Concluído: eqsp1503.csv
Processando: STSP2410.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2410.csv
Processando: STSP2006.dbc
Erro na conversão: Unknown field type: ' '
Concluído: stsp2006.csv
Processando: SRSP1601.dbc
Concluído: srsp1601.csv
Processando: LTSP1605.dbc
Concluído: ltsp1605.csv
Processando: EQSP2305.dbc
Concluído: eqsp2305.csv
Processando: HBSP1501.dbc
Concluído: hbsp1501.csv
Processando: HBSP2412.dbc
Concluído: hbsp2412.csv
Processando: SRSP2312.dbc
Concluído: srsp2312.csv
Processando: EQSP1710.dbc
Concluído: eqsp1710.csv
Processando: STSP1801.dbc
Concluído: stsp1801.csv
Processando: LTSP1606.dbc
Concluído: ltsp1606.csv
Processando: SRSP2408.dbc
Concluído: srsp2408.csv
Processando: EQSP2102.dbc
Concluído: eqsp2102.csv
Processando: EQSP1810.dbc
Concluído: eqsp1810.csv
Processando: HBSP2305.dbc
Concluído: hbsp2305.csv
Processando: LTSP2302.dbc
Concluído: ltsp2302.csv
Processando: EQSP2104.dbc
Concluído: eqsp2104.csv
Processando: SRSP1509.dbc
Concluído: srsp1509.csv
Processando: STSP1508.dbc
Concluído: stsp1508.csv
Processando: SRSP2510.dbc
Concluído: srsp2510.csv
Processando: LTSP2409.dbc
Concluído: ltsp2409.csv
Processando: STSP2203.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2203.csv
Processando: HBSP2012.dbc
Concluído: hbsp2012.csv
Processando: EQSP1509.dbc
Concluído: eqsp1509.csv
Processando: STSP2305.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2305.csv
Processando: SRSP2507.dbc
Concluído: srsp2507.csv
Processando: SRSP1501.dbc
Concluído: srsp1501.csv
Processando: SRSP1603.dbc
Concluído: srsp1603.csv
Processando: EQSP1512.dbc
Concluído: eqsp1512.csv
Processando: STSP1912.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp1912.csv
Processando: HBSP2510.dbc
Concluído: hbsp2510.csv
Processando: LTSP2312.dbc
Concluído: ltsp2312.csv
Processando: HBSP2112.dbc
Concluído: hbsp2112.csv
Processando: STSP2302.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2302.csv
Processando: STSP1802.dbc
Concluído: stsp1802.csv
Processando: SRSP1507.dbc
Concluído: srsp1507.csv
Processando: LTSP2303.dbc
Concluído: ltsp2303.csv
Processando: STSP1903.dbc
Concluído: stsp1903.csv
Processando: LTSP2410.dbc
Concluído: ltsp2410.csv
Processando: SRSP2209.dbc
Concluído: srsp2209.csv
Processando: EQSP1701.dbc
Concluído: eqsp1701.csv
Processando: SRSP1910.dbc
Concluído: srsp1910.csv
Processando: SRSP2005.dbc
Concluído: srsp2005.csv
Processando: LTSP1810.dbc
Concluído: ltsp1810.csv
Processando: EQSP2004.dbc
Concluído: eqsp2004.csv
Processando: SRSP2010.dbc
Concluído: srsp2010.csv
Processando: SRSP1605.dbc
Concluído: srsp1605.csv
Processando: EQSP2108.dbc
Concluído: eqsp2108.csv
Processando: EQSP1904.dbc
Concluído: eqsp1904.csv
Processando: SRSP1602.dbc
Concluído: srsp1602.csv
Processando: STSP2306.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2306.csv
Processando: LTSP2107.dbc
Concluído: ltsp2107.csv
Processando: HBSP1506.dbc
Concluído: hbsp1506.csv
Processando: STSP1606.dbc
Concluído: stsp1606.csv
Processando: LTSP2405.dbc
Concluído: ltsp2405.csv
Processando: SRSP2004.dbc
Concluído: srsp2004.csv
Processando: EQSP2212.dbc
Concluído: eqsp2212.csv
Processando: STSP2304.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2304.csv
Processando: LTSP1512.dbc
Concluído: ltsp1512.csv
Processando: LTSP1604.dbc
Concluído: ltsp1604.csv
Processando: SRSP1609.dbc
Concluído: srsp1609.csv
Processando: STSP2508.dbc
Erro na conversão: unpack requires a buffer of 32 bytes
Concluído: stsp2508.csv
Processando: LTSP2509.dbc
Concluído: ltsp2509.csv
Processando: SRSP2308.dbc
Concluído: srsp2308.csv
Processando: STSP2401.dbc

In [14]:
# Validação: lista arquivos gerados
csvs_cnes = sorted(PASTA_INPUT_CNES.glob("*.csv"))
print(f"\nArquivos CSV gerados ({len(csvs_cnes)}):")
for f in csvs_cnes:
    print(f"  {f.name}  ({f.stat().st_size / 1024:.0f} KB)")

Arquivos CSV gerados (540):
  eqsp1501.csv  (17377 KB)
  eqsp1502.csv  (17449 KB)
  eqsp1503.csv  (17590 KB)
  eqsp1504.csv  (17703 KB)
  eqsp1505.csv  (17784 KB)
  eqsp1506.csv  (17867 KB)
  eqsp1507.csv  (17997 KB)
  eqsp1508.csv  (18071 KB)
  eqsp1509.csv  (18154 KB)
  eqsp1510.csv  (18213 KB)
  eqsp1512.csv  (16864 KB)
  eqsp1601.csv  (16927 KB)
  eqsp1602.csv  (17023 KB)
  eqsp1603.csv  (17058 KB)
  eqsp1604.csv  (17152 KB)
  eqsp1605.csv  (17265 KB)
  eqsp1606.csv  (17406 KB)
  eqsp1607.csv  (17540 KB)
  eqsp1608.csv  (17659 KB)
  eqsp1609.csv  (17787 KB)
  eqsp1610.csv  (17904 KB)
  eqsp1612.csv  (18017 KB)
  eqsp1701.csv  (18104 KB)
  eqsp1702.csv  (18171 KB)
  eqsp1703.csv  (18285 KB)
  eqsp1704.csv  (18374 KB)
  eqsp1705.csv  (18489 KB)
  eqsp1706.csv  (18570 KB)
  eqsp1707.csv  (18687 KB)
  eqsp1708.csv  (18794 KB)
  eqsp1709.csv  (18879 KB)
  eqsp1710.csv  (18969 KB)
  eqsp1712.csv  (19113 KB)
  eqsp1801.csv  (19205 KB)
  eqsp1802.csv  (19289 KB)
  eqsp1803.csv  (19363 KB)
  eqsp1804.csv  (19475 KB)
  eqsp1805.csv  (19546 KB)
  eqsp1806.csv  (19647 KB)
  eqsp1807.csv  (19772 KB)
  eqsp1808.csv  (19880 KB)
  eqsp1809.csv  (19949 KB)
  eqsp1810.csv  (20031 KB)
  eqsp1812.csv  (20153 KB)
  eqsp1901.csv  (20251 KB)
  eqsp1902.csv  (20348 KB)
  eqsp1903.csv  (20456 KB)
  eqsp1904.csv  (20580 KB)
  eqsp1905.csv  (20674 KB)
  eqsp1906.csv  (20790 KB)
  eqsp1907.csv  (20887 KB)
  eqsp1908.csv  (20660 KB)
  eqsp1909.csv  (20804 KB)
  eqsp1910.csv  (20901 KB)
  eqsp1912.csv  (21018 KB)
  eqsp2001.csv  (19986 KB)
  eqsp2002.csv  (19768 KB)
  eqsp2003.csv  (17148 KB)
  eqsp2004.csv  (17281 KB)
  eqsp2005.csv  (17427 KB)
  eqsp2006.csv  (17460 KB)
  eqsp2007.csv  (17639 KB)
  eqsp2008.csv  (17792 KB)
  eqsp2009.csv  (17924 KB)
  eqsp2010.csv  (18075 KB)
  eqsp2012.csv  (18243 KB)
  eqsp2101.csv  (18388 KB)
  eqsp2102.csv  (18535 KB)
  eqsp2103.csv  (18632 KB)
  eqsp2104.csv  (18747 KB)
  eqsp2105.csv  (18853 KB)
  eqsp2106.csv  (18967 KB)
  eqsp2107.csv  (19154 KB)
  eqsp2108.csv  (19311 KB)
  eqsp2109.csv  (19426 KB)
  eqsp2110.csv  (19515 KB)
  eqsp2112.csv  (19669 KB)
  eqsp2201.csv  (19757 KB)
  eqsp2202.csv  (19847 KB)
  eqsp2203.csv  (19946 KB)
  eqsp2204.csv  (20008 KB)
  eqsp2205.csv  (20131 KB)
  eqsp2206.csv  (20201 KB)
  eqsp2207.csv  (20267 KB)
  eqsp2208.csv  (20391 KB)
  eqsp2209.csv  (20538 KB)
  eqsp2210.csv  (20656 KB)
  eqsp2212.csv  (20745 KB)
  eqsp2301.csv  (20810 KB)
  eqsp2302.csv  (20821 KB)
  eqsp2303.csv  (20864 KB)
  eqsp2304.csv  (20870 KB)
  eqsp2305.csv  (20960 KB)
  eqsp2306.csv  (21056 KB)
  eqsp2307.csv  (21187 KB)
  eqsp2308.csv  (21275 KB)
  eqsp2309.csv  (21352 KB)
  eqsp2310.csv  (21440 KB)
  eqsp2312.csv  (23589 KB)
  eqsp2401.csv  (23677 KB)
  eqsp2402.csv  (23748 KB)
  eqsp2403.csv  (23830 KB)
  eqsp2404.csv  (23912 KB)
  eqsp2405.csv  (24047 KB)
  eqsp2406.csv  (24240 KB)
  eqsp2407.csv  (24444 KB)
  eqsp2408.csv  (24614 KB)
  eqsp2409.csv  (24705 KB)
  eqsp2410.csv  (24799 KB)
  eqsp2412.csv  (24857 KB)
  eqsp2501.csv  (24949 KB)
  eqsp2502.csv  (25042 KB)
  eqsp2503.csv  (25157 KB)
  eqsp2504.csv  (25242 KB)
  eqsp2505.csv  (25385 KB)
  eqsp2506.csv  (25505 KB)
  eqsp2507.csv  (25653 KB)
  eqsp2508.csv  (26504 KB)
  eqsp2509.csv  (24052 KB)
  eqsp2510.csv  (24137 KB)
  eqsp2512.csv  (23958 KB)
  hbsp1501.csv  (708 KB)
  hbsp1502.csv  (707 KB)
  hbsp1503.csv  (708 KB)
  hbsp1504.csv  (709 KB)
  hbsp1505.csv  (709 KB)
  hbsp1506.csv  (710 KB)
  hbsp1507.csv  (711 KB)
  hbsp1508.csv  (712 KB)
  hbsp1509.csv  (718 KB)
  hbsp1510.csv  (718 KB)
  hbsp1512.csv  (682 KB)
  hbsp1601.csv  (675 KB)
  hbsp1602.csv  (677 KB)
  hbsp1603.csv  (677 KB)
  hbsp1604.csv  (677 KB)
  hbsp1605.csv  (680 KB)
  hbsp1606.csv  (683 KB)
  hbsp1607.csv  (672 KB)
  hbsp1608.csv  (672 KB)
  hbsp1609.csv  (677 KB)
  hbsp1610.csv  (679 KB)
  hbsp1612.csv  (693 KB)
  hbsp1701.csv  (693 KB)
  hbsp1702.csv  (694 KB)
  hbsp1703.csv  (694 KB)
  hbsp1704.csv  (694 KB)
  hbsp1705.csv  (696 KB)
  hbsp1706.csv  (697 KB)
  hbsp1707.csv  (697 KB)
  hbsp1708.csv  (697 KB)
  hbsp1709.csv  (699 KB)
  hbsp1710.csv  (701 KB)
  hbsp1712.csv  (705 KB)
  hbsp1801.csv  (701 KB)
  hbsp1802.csv  (701 KB)
  hbsp1803.csv  (704 KB)
  hbsp1804.csv  (675 KB)
  hbsp1805.csv  (697 KB)
  hbsp1806.csv  (698 KB)
  hbsp1807.csv  (678 KB)
  hbsp1808.csv  (680 KB)
  hbsp1809.csv  (678 KB)
  hbsp1810.csv  (678 KB)
  hbsp1812.csv  (705 KB)
  hbsp1901.csv  (705 KB)
  hbsp1902.csv  (705 KB)
  hbsp1903.csv  (705 KB)
  hbsp1904.csv  (706 KB)
  hbsp1905.csv  (708 KB)
  hbsp1906.csv  (709 KB)
  hbsp1907.csv  (712 KB)
  hbsp1908.csv  (715 KB)
  hbsp1909.csv  (716 KB)
  hbsp1910.csv  (717 KB)
  hbsp1912.csv  (728 KB)
  hbsp2001.csv  (726 KB)
  hbsp2002.csv  (727 KB)
  hbsp2003.csv  (734 KB)
  hbsp2004.csv  (741 KB)
  hbsp2005.csv  (748 KB)
  hbsp2006.csv  (749 KB)
  hbsp2007.csv  (754 KB)
  hbsp2008.csv  (757 KB)
  hbsp2009.csv  (757 KB)
  hbsp2010.csv  (761 KB)
  hbsp2012.csv  (768 KB)
  hbsp2101.csv  (765 KB)
  hbsp2102.csv  (769 KB)
  hbsp2103.csv  (780 KB)
  hbsp2104.csv  (787 KB)
  hbsp2105.csv  (790 KB)
  hbsp2106.csv  (791 KB)
  hbsp2107.csv  (796 KB)
  hbsp2108.csv  (797 KB)
  hbsp2109.csv  (791 KB)
  hbsp2110.csv  (788 KB)
  hbsp2112.csv  (784 KB)
  hbsp2201.csv  (773 KB)
  hbsp2202.csv  (773 KB)
  hbsp2203.csv  (756 KB)
  hbsp2204.csv  (757 KB)
  hbsp2205.csv  (759 KB)
  hbsp2206.csv  (759 KB)
  hbsp2207.csv  (759 KB)
  hbsp2208.csv  (760 KB)
  hbsp2209.csv  (767 KB)
  hbsp2210.csv  (766 KB)
  hbsp2212.csv  (773 KB)
  hbsp2301.csv  (775 KB)
  hbsp2302.csv  (903 KB)
  hbsp2303.csv  (906 KB)
  hbsp2304.csv  (915 KB)
  hbsp2305.csv  (918 KB)
  hbsp2306.csv  (921 KB)
  hbsp2307.csv  (934 KB)
  hbsp2308.csv  (937 KB)
  hbsp2309.csv  (964 KB)
  hbsp2310.csv  (969 KB)
  hbsp2312.csv  (804 KB)
  hbsp2401.csv  (807 KB)
  hbsp2402.csv  (805 KB)
  hbsp2403.csv  (808 KB)
  hbsp2404.csv  (811 KB)
  hbsp2405.csv  (816 KB)
  hbsp2406.csv  (817 KB)
  hbsp2407.csv  (826 KB)
  hbsp2408.csv  (826 KB)
  hbsp2409.csv  (827 KB)
  hbsp2410.csv  (831 KB)
  hbsp2412.csv  (842 KB)
  hbsp2501.csv  (872 KB)
  hbsp2502.csv  (885 KB)
  hbsp2503.csv  (902 KB)
  hbsp2504.csv  (918 KB)
  hbsp2505.csv  (936 KB)
  hbsp2506.csv  (949 KB)
  hbsp2507.csv  (976 KB)
  hbsp2508.csv  (986 KB)
  hbsp2509.csv  (1007 KB)
  hbsp2510.csv  (1016 KB)
  hbsp2512.csv  (1030 KB)
  ltsp1501.csv  (826 KB)
  ltsp1502.csv  (831 KB)
  ltsp1503.csv  (838 KB)
  ltsp1504.csv  (838 KB)
  ltsp1505.csv  (838 KB)
  ltsp1506.csv  (834 KB)
  ltsp1507.csv  (835 KB)
  ltsp1508.csv  (838 KB)
  ltsp1509.csv  (841 KB)
  ltsp1510.csv  (842 KB)
  ltsp1512.csv  (769 KB)
  ltsp1601.csv  (770 KB)
  ltsp1602.csv  (767 KB)
  ltsp1603.csv  (767 KB)
  ltsp1604.csv  (767 KB)
  ltsp1605.csv  (766 KB)
  ltsp1606.csv  (768 KB)
  ltsp1607.csv  (771 KB)
  ltsp1608.csv  (771 KB)
  ltsp1609.csv  (770 KB)
  ltsp1610.csv  (772 KB)
  ltsp1612.csv  (773 KB)
  ltsp1701.csv  (774 KB)
  ltsp1702.csv  (775 KB)
  ltsp1703.csv  (777 KB)
  ltsp1704.csv  (779 KB)
  ltsp1705.csv  (781 KB)
  ltsp1706.csv  (784 KB)
  ltsp1707.csv  (786 KB)
  ltsp1708.csv  (786 KB)
  ltsp1709.csv  (786 KB)
  ltsp1710.csv  (788 KB)
  ltsp1712.csv  (789 KB)
  ltsp1801.csv  (791 KB)
  ltsp1802.csv  (799 KB)
  ltsp1803.csv  (799 KB)
  ltsp1804.csv  (802 KB)
  ltsp1805.csv  (801 KB)
  ltsp1806.csv  (801 KB)
  ltsp1807.csv  (803 KB)
  ltsp1808.csv  (805 KB)
  ltsp1809.csv  (810 KB)
  ltsp1810.csv  (805 KB)
  ltsp1812.csv  (807 KB)
  ltsp1901.csv  (809 KB)
  ltsp1902.csv  (805 KB)
  ltsp1903.csv  (804 KB)
  ltsp1904.csv  (806 KB)
  ltsp1905.csv  (802 KB)
  ltsp1906.csv  (799 KB)
  ltsp1907.csv  (795 KB)
  ltsp1908.csv  (799 KB)
  ltsp1909.csv  (804 KB)
  ltsp1910.csv  (808 KB)
  ltsp1912.csv  (808 KB)
  ltsp2001.csv  (804 KB)
  ltsp2002.csv  (803 KB)
  ltsp2003.csv  (812 KB)
  ltsp2004.csv  (828 KB)
  ltsp2005.csv  (830 KB)
  ltsp2006.csv  (826 KB)
  ltsp2007.csv  (835 KB)
  ltsp2008.csv  (844 KB)
  ltsp2009.csv  (845 KB)
  ltsp2010.csv  (846 KB)
  ltsp2012.csv  (842 KB)
  ltsp2101.csv  (843 KB)
  ltsp2102.csv  (849 KB)
  ltsp2103.csv  (857 KB)
  ltsp2104.csv  (860 KB)
  ltsp2105.csv  (862 KB)
  ltsp2106.csv  (864 KB)
  ltsp2107.csv  (863 KB)
  ltsp2108.csv  (860 KB)
  ltsp2109.csv  (859 KB)
  ltsp2110.csv  (849 KB)
  ltsp2112.csv  (847 KB)
  ltsp2201.csv  (847 KB)
  ltsp2202.csv  (848 KB)
  ltsp2203.csv  (843 KB)
  ltsp2204.csv  (838 KB)
  ltsp2205.csv  (836 KB)
  ltsp2206.csv  (812 KB)
  ltsp2207.csv  (806 KB)
  ltsp2208.csv  (812 KB)
  ltsp2209.csv  (812 KB)
  ltsp2210.csv  (812 KB)
  ltsp2212.csv  (816 KB)
  ltsp2301.csv  (820 KB)
  ltsp2302.csv  (820 KB)
  ltsp2303.csv  (821 KB)
  ltsp2304.csv  (822 KB)
  ltsp2305.csv  (822 KB)
  ltsp2306.csv  (818 KB)
  ltsp2307.csv  (818 KB)
  ltsp2308.csv  (818 KB)
  ltsp2309.csv  (820 KB)
  ltsp2310.csv  (823 KB)
  ltsp2312.csv  (822 KB)
  ltsp2401.csv  (826 KB)
  ltsp2402.csv  (827 KB)
  ltsp2403.csv  (827 KB)
  ltsp2404.csv  (827 KB)
  ltsp2405.csv  (826 KB)
  ltsp2406.csv  (827 KB)
  ltsp2407.csv  (828 KB)
  ltsp2408.csv  (830 KB)
  ltsp2409.csv  (827 KB)
  ltsp2410.csv  (825 KB)
  ltsp2412.csv  (822 KB)
  ltsp2501.csv  (825 KB)
  ltsp2502.csv  (826 KB)
  ltsp2503.csv  (825 KB)
  ltsp2504.csv  (825 KB)
  ltsp2505.csv  (824 KB)
  ltsp2506.csv  (823 KB)
  ltsp2507.csv  (824 KB)
  ltsp2508.csv  (830 KB)
  ltsp2509.csv  (830 KB)
  ltsp2510.csv  (830 KB)
  ltsp2512.csv  (829 KB)
  srsp1501.csv  (12212 KB)
  srsp1502.csv  (12237 KB)
  srsp1503.csv  (12307 KB)
  srsp1504.csv  (12348 KB)
  srsp1505.csv  (12373 KB)
  srsp1506.csv  (12425 KB)
  srsp1507.csv  (12489 KB)
  srsp1508.csv  (12535 KB)
  srsp1509.csv  (12575 KB)
  srsp1510.csv  (12607 KB)
  srsp1512.csv  (11744 KB)
  srsp1601.csv  (11763 KB)
  srsp1602.csv  (11812 KB)
  srsp1603.csv  (11823 KB)
  srsp1604.csv  (11880 KB)
  srsp1605.csv  (11929 KB)
  srsp1606.csv  (12003 KB)
  srsp1607.csv  (12077 KB)
  srsp1608.csv  (12137 KB)
  srsp1609.csv  (12194 KB)
  srsp1610.csv  (12248 KB)
  srsp1612.csv  (12301 KB)
  srsp1701.csv  (12347 KB)
  srsp1702.csv  (12376 KB)
  srsp1703.csv  (12461 KB)
  srsp1704.csv  (12518 KB)
  srsp1705.csv  (12597 KB)
  srsp1706.csv  (12634 KB)
  srsp1707.csv  (12722 KB)
  srsp1708.csv  (12829 KB)
  srsp1709.csv  (12884 KB)
  srsp1710.csv  (12935 KB)
  srsp1712.csv  (13016 KB)
  srsp1801.csv  (13063 KB)
  srsp1802.csv  (13085 KB)
  srsp1803.csv  (13106 KB)
  srsp1804.csv  (13172 KB)
  srsp1805.csv  (13224 KB)
  srsp1806.csv  (13268 KB)
  srsp1807.csv  (13336 KB)
  srsp1808.csv  (13390 KB)
  srsp1809.csv  (13434 KB)
  srsp1810.csv  (13475 KB)
  srsp1812.csv  (13561 KB)
  srsp1901.csv  (13622 KB)
  srsp1902.csv  (13670 KB)
  srsp1903.csv  (13725 KB)
  srsp1904.csv  (13738 KB)
  srsp1905.csv  (13816 KB)
  srsp1906.csv  (13843 KB)
  srsp1907.csv  (13871 KB)
  srsp1908.csv  (13847 KB)
  srsp1909.csv  (13909 KB)
  srsp1910.csv  (13947 KB)
  srsp1912.csv  (13992 KB)
  srsp2001.csv  (13315 KB)
  srsp2002.csv  (13377 KB)
  srsp2003.csv  (12776 KB)
  srsp2004.csv  (12876 KB)
  srsp2005.csv  (13254 KB)
  srsp2006.csv  (13368 KB)
  srsp2007.csv  (13483 KB)
  srsp2008.csv  (13429 KB)
  srsp2009.csv  (13498 KB)
  srsp2010.csv  (13613 KB)
  srsp2012.csv  (14021 KB)
  srsp2101.csv  (14245 KB)
  srsp2102.csv  (14372 KB)
  srsp2103.csv  (14435 KB)
  srsp2104.csv  (14492 KB)
  srsp2105.csv  (14553 KB)
  srsp2106.csv  (14616 KB)
  srsp2107.csv  (14677 KB)
  srsp2108.csv  (14738 KB)
  srsp2109.csv  (14804 KB)
  srsp2110.csv  (14848 KB)
  srsp2112.csv  (14958 KB)
  srsp2201.csv  (15022 KB)
  srsp2202.csv  (15073 KB)
  srsp2203.csv  (15121 KB)
  srsp2204.csv  (15171 KB)
  srsp2205.csv  (15231 KB)
  srsp2206.csv  (15266 KB)
  srsp2207.csv  (15302 KB)
  srsp2208.csv  (15369 KB)
  srsp2209.csv  (15423 KB)
  srsp2210.csv  (15481 KB)
  srsp2212.csv  (15577 KB)
  srsp2301.csv  (15618 KB)
  srsp2302.csv  (15613 KB)
  srsp2303.csv  (15667 KB)
  srsp2304.csv  (15726 KB)
  srsp2305.csv  (15794 KB)
  srsp2306.csv  (15931 KB)
  srsp2307.csv  (16062 KB)
  srsp2308.csv  (16131 KB)
  srsp2309.csv  (16179 KB)
  srsp2310.csv  (16234 KB)
  srsp2312.csv  (16258 KB)
  srsp2401.csv  (16241 KB)
  srsp2402.csv  (16350 KB)
  srsp2403.csv  (16436 KB)
  srsp2404.csv  (16516 KB)
  srsp2405.csv  (16628 KB)
  srsp2406.csv  (17070 KB)
  srsp2407.csv  (17210 KB)
  srsp2408.csv  (17363 KB)
  srsp2409.csv  (17445 KB)
  srsp2410.csv  (17526 KB)
  srsp2412.csv  (17558 KB)
  srsp2501.csv  (17633 KB)
  srsp2502.csv  (17737 KB)
  srsp2503.csv  (17938 KB)
  srsp2504.csv  (18001 KB)
  srsp2505.csv  (18221 KB)
  srsp2506.csv  (18350 KB)
  srsp2507.csv  (18504 KB)
  srsp2508.csv  (18816 KB)
  srsp2509.csv  (18976 KB)
  srsp2510.csv  (19083 KB)
  srsp2512.csv  (19147 KB)
  stsp1501.csv  (30773 KB)
  stsp1502.csv  (30884 KB)
  stsp1503.csv  (31079 KB)
  stsp1504.csv  (31223 KB)
  stsp1505.csv  (31344 KB)
  stsp1506.csv  (31445 KB)
  stsp1507.csv  (31631 KB)
  stsp1508.csv  (31741 KB)
  stsp1509.csv  (31830 KB)
  stsp1510.csv  (31919 KB)
  stsp1512.csv  (31228 KB)
  stsp1601.csv  (31339 KB)
  stsp1602.csv  (31523 KB)
  stsp1603.csv  (31573 KB)
  stsp1604.csv  (31709 KB)
  stsp1605.csv  (31851 KB)
  stsp1606.csv  (32045 KB)
  stsp1607.csv  (32221 KB)
  stsp1608.csv  (32378 KB)
  stsp1609.csv  (32546 KB)
  stsp1610.csv  (32724 KB)
  stsp1612.csv  (32892 KB)
  stsp1701.csv  (33025 KB)
  stsp1702.csv  (33115 KB)
  stsp1703.csv  (33293 KB)
  stsp1704.csv  (33438 KB)
  stsp1705.csv  (33616 KB)
  stsp1706.csv  (33742 KB)
  stsp1707.csv  (33907 KB)
  stsp1708.csv  (34076 KB)
  stsp1709.csv  (34231 KB)
  stsp1710.csv  (34377 KB)
  stsp1712.csv  (34605 KB)
  stsp1801.csv  (34760 KB)
  stsp1802.csv  (34887 KB)
  stsp1803.csv  (35002 KB)
  stsp1804.csv  (35190 KB)
  stsp1805.csv  (35325 KB)
  stsp1806.csv  (35481 KB)
  stsp1807.csv  (35649 KB)
  stsp1808.csv  (35831 KB)
  stsp1809.csv  (35989 KB)
  stsp1810.csv  (36165 KB)
  stsp1812.csv  (36402 KB)
  stsp1901.csv  (36568 KB)
  stsp1902.csv  (36758 KB)
  stsp1903.csv  (36945 KB)
  stsp1904.csv  (37076 KB)
  stsp1905.csv  (37197 KB)
  stsp1906.csv  (37333 KB)
  stsp1907.csv  (37526 KB)
  stsp1908.csv  (37152 KB)
  stsp1909.csv  (37387 KB)
  stsp1910.csv  (37528 KB)
  stsp2001.csv  (35991 KB)
  stsp2002.csv  (35397 KB)

## 4. Tradução dos Códigos das Tabelas

O DataSUS armazena os dados como **códigos numéricos** (ex: `1`, `3`, `M`). Esta seção
traduz esses códigos para **descrições legíveis** usando os dicionários `.cnv` e as
instruções `.def` baixados do FTP do DataSUS.

**Como funciona:**
1. O arquivo `.def` indica quais colunas têm código e qual `.cnv` usar para cada uma
2. O arquivo `.cnv` contém o mapeamento `CÓDIGO → DESCRIÇÃO`
3. Para cada coluna com dicionário é criada uma coluna `COLUNA_DESC` com o texto traduzido

**Resultado:** arquivos salvos em `data/interim/` com colunas `_DESC` adicionadas.

### 4.0 Download dos dicionários (executar apenas uma vez)

Os dicionários `.def` e `.cnv` são baixados do FTP do DataSUS e salvos em `data/external/`.
Se os arquivos já existirem localmente este passo pode ser pulado.

In [15]:
# Pasta destino ancorada em ROOT para não depender do diretório de trabalho do notebook
PASTA_EXTERNAL_SIH = Path(ROOT, "data", "external", "SIH")
PASTA_EXTERNAL_CNES = Path(ROOT, "data", "external", "CNES")
PASTA_EXTERNAL_SIH.mkdir(parents=True, exist_ok=True)
PASTA_EXTERNAL_CNES.mkdir(parents=True, exist_ok=True)

In [16]:


# Dicionários do CNES
download_dicionarios("CNES", str(PASTA_EXTERNAL_CNES))

# Dicionários do SIH
download_dicionarios("SIH", str(PASTA_EXTERNAL_SIH))

print(f"\nDicionários salvos")

Conectando ao FTP para buscar tabelas de CNES: ftp.datasus.gov.br
Arquivo encontrado: TAB_CNES.zip. Baixando para a memória...
Extraindo dicionários (.cnv) e configurações (.def)...

Processo concluído! Arquivos salvos em: /home/carolina/Documents/TCC Documentos/TCC/data/external/CNES
Conectando ao FTP para buscar tabelas de SIH: ftp.datasus.gov.br
Arquivo encontrado: TAB_SIH.zip. Baixando para a memória...
Extraindo dicionários (.cnv) e configurações (.def)...

Processo concluído! Arquivos salvos em: /home/carolina/Documents/TCC Documentos/TCC/data/external/SIH

Dicionários salvos

### 4.1 Configuração dos caminhos e importação dos utilitários

In [17]:
from src.utils.information_translation import mapear_colunas_def, traduzir_csv_datasus

# Caminhos dos dicionários — separados por sistema (CNES e SIH)
PASTA_DEF_CNES  = PASTA_EXTERNAL_CNES                    # arquivos .def do CNES
PASTA_CNV_CNES  = PASTA_EXTERNAL_CNES / "CNV"            # arquivos .cnv do CNES
PASTA_DEF_SIH   = PASTA_EXTERNAL_SIH                     # arquivos .def do SIH
PASTA_CNV_SIH   = PASTA_EXTERNAL_SIH / "CNV"             # arquivos .cnv do SIH

# Pasta de saída dos CSVs traduzidos
PASTA_INTERIM = Path(ROOT, "data", "interim")
PASTA_INTERIM.mkdir(parents=True, exist_ok=True)

print(f"DEF CNES : {PASTA_DEF_CNES}")
print(f"CNV CNES : {PASTA_CNV_CNES}")
print(f"DEF SIH  : {PASTA_DEF_SIH}")
print(f"CNV SIH  : {PASTA_CNV_SIH}")
print(f"Saída    : {PASTA_INTERIM}")

DEF CNES : /home/carolina/Documents/TCC Documentos/TCC/data/external/CNES
CNV CNES : /home/carolina/Documents/TCC Documentos/TCC/data/external/CNES/CNV
DEF SIH  : /home/carolina/Documents/TCC Documentos/TCC/data/external/SIH
CNV SIH  : /home/carolina/Documents/TCC Documentos/TCC/data/external/SIH/CNV
Saída    : /home/carolina/Documents/TCC Documentos/TCC/data/interim

### 4.2 Tradução das tabelas CNES

Cada base do CNES tem seu próprio `.def`:

| Sigla | Tabela                   | Arquivo .def                         |
|-------|--------------------------|--------------------------------------|
| `HB`  | Habilitações             | `Habilitacao.def`                    |
| `LT`  | Leitos por Especialidade | `Leitos_Especialidade.def`           |
| `EQ`  | Equipamentos             | `Equipamento.def`                    |
| `SR`  | Serviços Especializados  | `Servico_Especializado_200803_.def`  |
| `ST`  | Estabelecimentos         | `Estabelecimento.def`                |

In [18]:
# Mapeamento: prefixo do CSV → arquivo .def correspondente
MAPA_DEF_CNES = {
    "hb": "Habilitacao.def",
    "lt": "Leitos_Especialidade.def",
    "eq": "Equipamento.def",
    "sr": "Servico_Especializado_200803_.def",
    "st": "Estabelecimento.def",
}

for prefixo, nome_def in MAPA_DEF_CNES.items():
    csvs = sorted(PASTA_INPUT_CNES.glob(f"{prefixo}*.csv"))
    if not csvs:
        print(f"[AVISO] Nenhum CSV encontrado para '{prefixo}' em {PASTA_INPUT_CNES}")
        continue

    arquivo_def = PASTA_DEF_CNES / nome_def
    mapa = mapear_colunas_def(str(arquivo_def))

    if not mapa:
        print(f"[AVISO] Nenhuma coluna mapeável encontrada em {nome_def}")
        continue

    print(f"\n── {prefixo.upper()} ({nome_def}) ──")
    print(f"   Colunas com dicionário: {list(mapa.keys())}")

    for csv_path in csvs:
        nome_saida = f"cnes_{prefixo}_{csv_path.stem}_traduzido.csv"
        caminho_saida = PASTA_INTERIM / nome_saida
        traduzir_csv_datasus(
            caminho_csv=str(csv_path),
            mapa_diretrizes=mapa,
            pasta_cnv=str(PASTA_CNV_CNES),
            caminho_salvar=str(caminho_saida),
        )

print("\n✓ Tradução CNES concluída.")

── HB (Habilitacao.def) ──
   Colunas com dicionário: ['MAPORTAR', 'CMPT_INI', 'CMPT_FIM', 'COMPETEN', 'TPGESTAO', 'NIV_DEP', 'PF_PJ', 'NATUREZA', 'NAT_JUR', 'RETENCAO', 'NIV_HIER', 'ESFERA_A', 'ATIVIDAD', 'TP_UNID', 'TURNO_AT', 'TP_PREST', 'VINC_SUS', 'CODUFMUN']
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1501_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1502_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1503_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1504_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1505_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1506_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1507_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1508_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1509_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1510_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1512_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1601_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1602_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1603_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1604_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1605_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'MAPORTAR' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1606_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'CMPT_INI' com o dicionário 'COMPT.CNV'...
Traduzindo a coluna 'CMPT_FIM' com o dicionário 'COMPT.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1501_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1502_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1503_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1504_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1505_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1506_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1507_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1508_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1509_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1510_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1512_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1601_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1602_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1603_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1604_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1605_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1606_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1607_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1608_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1609_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1610_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1612_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1701_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1702_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1703_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1704_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1705_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1706_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1707_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1708_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1709_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1710_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1712_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1801_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1802_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1803_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1804_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1805_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1806_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1807_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1808_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1809_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1810_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1812_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1901_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1902_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1903_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1904_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1905_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1906_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1907_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1908_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1909_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1910_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1912_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2001_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2002_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2003_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2004_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2005_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2006_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2007_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2008_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2009_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2010_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2012_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2101_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2102_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2103_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2104_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2105_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2106_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2107_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2108_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2109_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2110_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2112_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2201_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2202_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2203_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2204_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2205_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2206_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2207_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2208_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2209_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2210_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2212_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2301_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2302_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2303_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2304_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2305_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2306_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2307_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2308_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2309_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2310_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2312_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2401_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2402_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2403_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2404_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2405_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2406_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2407_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2408_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2409_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2410_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2412_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2501_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2502_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2503_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2504_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2505_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2506_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2507_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2508_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2509_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2510_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TIPEQUIP' com o dicionário 'Equipam_grp.cnv'...
Traduzindo a coluna 'IND_SUS' com o dicionário 'IND_SUS.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2512_traduzido.csv

── SR (Servico_Especializado_200803_.def) ──
   Colunas com dicionário: ['COMPETEN', 'TPGESTAO', 'NIV_DEP', 'PF_PJ', 'NATUREZA', 'NAT_JUR', 'NIV_HIER', 'ESFERA_A', 'ATIVIDAD', 'TP_UNID', 'CARACTER', 'AMB_NSUS', 'CODUFMUN', '1']
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1501_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1502_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1503_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1504_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1505_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1506_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1507_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1508_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1509_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1510_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1512_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1601_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1602_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1603_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1604_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1605_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1606_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1607_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1608_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1609_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1610_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1612_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1701_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1702_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1703_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1704_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1705_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1706_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1707_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1708_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1709_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1710_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1712_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1801_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1802_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1803_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRSAN, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1804_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1805_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1806_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1807_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1808_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1809_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1810_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1812_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1901_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1902_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1903_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1904_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1905_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1906_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1907_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1908_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1909_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1910_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1912_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2001_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2002_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2003_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2004_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2005_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2006_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2007_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2008_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2009_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2010_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2012_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2101_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2102_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2103_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2104_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2105_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2106_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2107_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2108_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2109_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2110_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2112_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2201_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2202_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2203_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2204_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2205_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2206_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2207_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2208_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2209_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2210_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2212_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2301_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2302_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2303_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2304_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2305_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2306_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2307_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2308_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2309_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2310_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2312_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2401_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2402_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2403_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2404_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2405_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2406_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2407_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2408_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2409_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2410_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2412_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2501_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2502_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2503_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2504_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2505_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2506_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2507_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2508_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2509_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2510_traduzido.csv
Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_frontzona.cnv'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'CARACTER' com o dicionário 'Srv_Caract.CNV'...
Traduzindo a coluna 'AMB_NSUS' com o dicionário 'AMB_HOSP.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'RETENCAO.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2512_traduzido.csv

── ST (Estabelecimento.def) ──
   Colunas com dicionário: ['COMPETEN', 'TPGESTAO', 'NIV_DEP', 'PF_PJ', 'CLIENTEL', 'NATUREZA', 'NAT_JUR', 'RETENCAO', 'COD_IR', 'NIV_HIER', 'ESFERA_A', 'ATIVIDAD', 'TP_UNID', 'TURNO_AT', 'TP_PREST', 'DT_EXPED', 'ORGEXPED', 'AV_ACRED', 'CLASAVAL', 'VINC_SUS', 'DT_PUBLM', 'DT_PUBLE', 'GESPRG1E', 'GESPRG2E', 'GESPRG4E', 'GESPRG5E', 'GESPRG6E', 'GESPRG3E', 'SERAP01P', 'SERAP02P', 'SERAP03P', 'SERAP04P', 'SERAP05P', 'SERAP06P', 'SERAP07P', 'SERAP08P', 'SERAP09P', 'SERAP10P', 'SERAP11P', 'AP01CV01', 'AP02CV01', 'AP03CV01', 'AP04CV01', 'AP05CV01', 'AP06CV01', 'AP07CV01', 'AP01CV03', 'AP02CV03', 'AP03CV03', 'AP04CV03', 'AP05CV03', 'AP06CV03', 'AP07CV03', 'RES_BIOL', 'RES_QUIM', 'RES_RADI', 'RES_COMU', 'COMISS01', 'COMISS02', 'COMISS03', 'COMISS04', 'COMISS05', 'COMISS06', 'COMISS07', 'COMISS08', 'COMISS09', 'COMISS10', 'COMISS11', 'COMISS12', 'CODUFMUN']

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC, 4: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1501_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC, 4: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1502_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC, 4: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1503_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1504_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1505_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1506_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1507_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1508_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1509_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1510_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1512_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1601_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1602_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1603_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1604_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1605_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1606_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1607_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1608_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1609_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1610_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1612_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1701_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1702_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1703_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1704_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1705_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1706_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1707_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1708_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1709_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1710_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1712_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1801_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1802_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1803_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1804_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1805_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1806_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1807_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1808_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1809_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1810_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1812_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1901_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1902_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1903_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1904_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...
Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1905_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1906_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1907_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: MICR_REG, 1: DISTRSAN, 2: DISTRADM, 3: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1908_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC, 5: C_CORREN) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1909_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRSAN, 3: DISTRADM, 4: CO_AGENC) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1910_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...
Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...
Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2001_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: REGSAUDE, 1: MICR_REG, 2: DISTRADM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'CODUFMUN' com o dicionário 'br_extrpobrez.cnv'...
Traduzindo a coluna 'PF_PJ' com o dicionário 'TP_PFPJ.CNV'...
Traduzindo a coluna 'NIV_DEP' com o dicionário 'NIVELDEP.CNV'...
Traduzindo a coluna 'COD_IR' com o dicionário 'RETENMAN.CNV'...
Traduzindo a coluna 'TPGESTAO' com o dicionário 'TPGESTAO.CNV'...
Traduzindo a coluna 'RETENCAO' com o dicionário 'RETENCAO.CNV'...
Traduzindo a coluna 'ATIVIDAD' com o dicionário 'Ativ_Ens.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'NATUREZA.CNV'...
Traduzindo a coluna 'TP_UNID' com o dicionário 'TP_ESTAB.CNV'...
Traduzindo a coluna 'NIV_HIER' com o dicionário 'NIV_HIER.CNV'...
Traduzindo a coluna 'TP_PREST' com o dicionário 'TIPOPRES.CNV'...
Traduzindo a coluna 'DT_PUBLM' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_PUBLE' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'DT_EXPED' com o dicionário 'ANO_MES.CNV'...
Traduzindo a coluna 'ORGEXPED' com o dicionário 'ORGEXPED.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'AV_ACRED' com o dicionário 'AVALIADO.CNV'...
Traduzindo a coluna 'CLASAVAL' com o dicionário 'CLASAVAL.CNV'...
Traduzindo a coluna 'GESPRG1E' com o dicionário 'GESPROG1.CNV'...
Traduzindo a coluna 'GESPRG2E' com o dicionário 'GESPROG2.CNV'...
Traduzindo a coluna 'GESPRG4E' com o dicionário 'GESPROG4.CNV'...
Traduzindo a coluna 'GESPRG3E' com o dicionário 'GESPROG3.CNV'...
Traduzindo a coluna 'GESPRG5E' com o dicionário 'GESPROG5.CNV'...
Traduzindo a coluna 'GESPRG6E' com o dicionário 'GESPROG6.CNV'...
Traduzindo a coluna 'SERAP01P' com o dicionário 'Srv_AP01.CNV'...
Traduzindo a coluna 'SERAP02P' com o dicionário 'Srv_AP02.CNV'...
Traduzindo a coluna 'SERAP03P' com o dicionário 'Srv_AP03.CNV'...
Traduzindo a coluna 'SERAP04P' com o dicionário 'Srv_AP04.CNV'...
Traduzindo a coluna 'SERAP05P' com o dicionário 'Srv_AP05.CNV'...
Traduzindo a coluna 'SERAP06P' com o dicionário 'Srv_AP06.CNV'...
Traduzindo a coluna 'SERAP07P' com o dicionário 'Srv_AP07.CNV'...
Traduzindo a coluna 'SERAP08P' com o dicionário 'Srv_AP08.CNV'...
Traduzindo a coluna 'SERAP09P' com o dicionário 'Srv_AP09.CNV'...
Traduzindo a coluna 'SERAP10P' com o dicionário 'Srv_AP10.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'SERAP11P' com o dicionário 'Srv_AP11.CNV'...
Traduzindo a coluna 'RES_BIOL' com o dicionário 'RES_BIOL.CNV'...
Traduzindo a coluna 'RES_QUIM' com o dicionário 'RES_QUIM.CNV'...
Traduzindo a coluna 'RES_RADI' com o dicionário 'RES_RADI.CNV'...
Traduzindo a coluna 'RES_COMU' com o dicionário 'RES_COMU.CNV'...
Traduzindo a coluna 'COMISS01' com o dicionário 'COM_ETMD.CNV'...
Traduzindo a coluna 'COMISS02' com o dicionário 'COM_ETEF.CNV'...
Traduzindo a coluna 'COMISS03' com o dicionário 'COM_FMTR.CNV'...
Traduzindo a coluna 'COMISS04' com o dicionário 'COM_CTIH.CNV'...
Traduzindo a coluna 'COMISS05' com o dicionário 'COM_APCT.CNV'...
Traduzindo a coluna 'COMISS06' com o dicionário 'COM_CIPA.CNV'...
Traduzindo a coluna 'COMISS07' com o dicionário 'COM_RVPR.CNV'...
Traduzindo a coluna 'COMISS08' com o dicionário 'COM_RDME.CNV'...
Traduzindo a coluna 'COMISS09' com o dicionário 'COM_ANOB.CNV'...
Traduzindo a coluna 'COMISS10' com o dicionário 'COM_IVEP.CNV'...
Traduzindo a coluna 'COMISS11' com o dicionário 'COM_NTFD.CNV'...
Traduzindo a coluna 'COMISS12' com o dicionário 'COM_CTZV.CNV'...

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'COMPETEN' com o dicionário 'COMPETEN.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2002_traduzido.csv

✓ Tradução CNES concluída.

### 4.3 Tradução do SIH

In [19]:
# Localiza o .def do SIH — tenta extensão em maiúsculo e minúsculo (Linux é case-sensitive)
defs_sih = (
    list(PASTA_DEF_SIH.glob("RD*.def")) +
    list(PASTA_DEF_SIH.glob("RD*.DEF")) +
    list(PASTA_DEF_SIH.glob("AIH*.def")) +
    list(PASTA_DEF_SIH.glob("AIH*.DEF"))
)

if not defs_sih:
    print("[AVISO] Arquivo .def do SIH não encontrado em", PASTA_DEF_SIH)
    print("Arquivos .def disponíveis:", [f.name for f in PASTA_DEF_SIH.iterdir() if f.suffix.upper() == ".DEF"])
else:
    arquivo_def_sih = defs_sih[0]
    mapa_sih = mapear_colunas_def(str(arquivo_def_sih))
    print(f"Usando .def: {arquivo_def_sih.name}")
    print(f"Colunas com dicionário ({len(mapa_sih)}): {list(mapa_sih.keys())}")

    for csv_path in sorted(PASTA_INPUT_SIH.glob("*.csv")):
        nome_saida = f"sih_{csv_path.stem}_traduzido.csv"
        caminho_saida = PASTA_INTERIM / nome_saida
        traduzir_csv_datasus(
            caminho_csv=str(csv_path),
            mapa_diretrizes=mapa_sih,
            pasta_cnv=str(PASTA_CNV_SIH),
            caminho_salvar=str(caminho_saida),
        )

    print("\n✓ Tradução SIH concluída.")

Usando .def: RD2008.DEF
Colunas com dicionário (56): ['MUNIC_MOV', 'CNES', 'NATUREZA', 'NAT_JUR', 'GESTAO', 'UF_ZI', 'ANO_CMPT', 'MES_CMPT', 'SEXO', 'COD_IDADE', 'RACA_COR', 'ETNIA', 'MUNIC_RES', 'NACIONAL', 'CNAER', 'VINCPREV', 'ESPEC', 'N_AIH', 'IDENT', 'SEQ_AIH5', 'CAR_INT', 'UTI_MES_TO', 'MARCA_UTI', 'MARCA_UCI', 'DT_INTER', 'DT_SAIDA', 'DIAS_PERM', 'COBRANCA', 'MORTE', 'FINANC', 'FAEC_TP', 'REGCT', 'COMPLEX', 'PROC_REA', 'IND_VDRL', 'INFEHOSP', 'DIAG_PRINC', 'TPDISEC1', 'TPDISEC2', 'TPDISEC3', 'TPDISEC4', 'TPDISEC5', 'TPDISEC6', 'TPDISEC7', 'TPDISEC8', 'TPDISEC9', 'DIAG_SECUN', 'CID_ASSO', 'CID_MORTE', 'NUM_FILHOS', 'INSTRU', 'CID_NOTIF', 'CONTRACEP1', 'CONTRACEP2', 'GESTRISCO', 'INSC_PN']

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1501_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1502_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1503_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1504_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1505_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1506_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1507_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1508_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1509_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1510_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1512_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1601_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1602_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1603_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1604_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1605_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1606_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1607_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1608_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1609_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1610_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1612_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1701_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1702_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1703_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1704_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1705_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1706_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1707_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC6, 3: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1708_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1709_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1710_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1712_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1801_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1802_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1803_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1804_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1805_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1806_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1807_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1808_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1809_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1810_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1812_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1901_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1902_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1903_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1904_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1905_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1906_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1907_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1908_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1909_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1910_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1912_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2001_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2002_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2003_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2004_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2005_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: CID_NOTIF, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC1, 4: DIAGSEC2, 5: DIAGSEC3, 6: DIAGSEC4, 7: DIAGSEC5, 8: DIAGSEC6, 9: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2006_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2007_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2008_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2009_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2010_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2012_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2101_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2102_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2103_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2104_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2105_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2106_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2107_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2108_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2109_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2110_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2112_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2201_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2202_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2203_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2204_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2205_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2206_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2207_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2208_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2209_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2210_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2212_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2301_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC6, 3: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2302_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2303_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2304_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC1, 3: DIAGSEC2, 4: DIAGSEC3, 5: DIAGSEC4, 6: DIAGSEC5, 7: DIAGSEC6, 8: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2305_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2306_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC6, 3: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2307_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2308_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2309_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2310_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC6, 3: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2312_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2401_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2402_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:114: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[nova_coluna_desc] = df[coluna_csv].map(dicionario_traducao)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2403_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7, 5: DIAGSEC8, 6: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2404_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7, 8: DIAGSEC8, 9: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2405_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7, 8: DIAGSEC8, 9: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2406_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC3, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7, 7: DIAGSEC8, 8: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2407_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7, 8: DIAGSEC8, 9: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2408_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: AUD_JUST, 1: SIS_JUST, 2: DIAGSEC5, 3: DIAGSEC6, 4: DIAGSEC7, 5: DIAGSEC8, 6: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2409_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7, 6: DIAGSEC8, 7: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2410_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7, 8: DIAGSEC8, 9: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2412_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC2, 4: DIAGSEC3, 5: DIAGSEC4, 6: DIAGSEC5, 7: DIAGSEC6, 8: DIAGSEC7, 9: DIAGSEC8, 10: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2501_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC2, 4: DIAGSEC3, 5: DIAGSEC4, 6: DIAGSEC5, 7: DIAGSEC6, 8: DIAGSEC7, 9: DIAGSEC8, 10: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2502_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC2, 4: DIAGSEC3, 5: DIAGSEC4, 6: DIAGSEC5, 7: DIAGSEC6, 8: DIAGSEC7, 9: DIAGSEC8, 10: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2503_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7, 6: DIAGSEC8, 7: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2504_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7, 6: DIAGSEC8, 7: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2505_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: SIS_JUST, 2: DIAGSEC6, 3: DIAGSEC7, 4: DIAGSEC8, 5: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2506_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: SIS_JUST, 2: DIAGSEC2, 3: DIAGSEC3, 4: DIAGSEC4, 5: DIAGSEC5, 6: DIAGSEC6, 7: DIAGSEC7, 8: DIAGSEC8, 9: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2507_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC4, 4: DIAGSEC5, 5: DIAGSEC6, 6: DIAGSEC7, 7: DIAGSEC8, 8: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2508_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: SIS_JUST, 2: DIAGSEC4, 3: DIAGSEC5, 4: DIAGSEC6, 5: DIAGSEC7, 6: DIAGSEC8, 7: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2509_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC2, 4: DIAGSEC3, 5: DIAGSEC4, 6: DIAGSEC5, 7: DIAGSEC6, 8: DIAGSEC7, 9: DIAGSEC8, 10: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2510_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:84: DtypeWarning: Columns (0: ETNIA, 1: AUD_JUST, 2: SIS_JUST, 3: DIAGSEC2, 4: DIAGSEC3, 5: DIAGSEC4, 6: DIAGSEC5, 7: DIAGSEC6, 8: DIAGSEC7, 9: DIAGSEC8, 10: DIAGSEC9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_csv)

Traduzindo a coluna 'UF_ZI' com o dicionário 'br_municgestor.cnv'...
Traduzindo a coluna 'ANO_CMPT' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'MES_CMPT' com o dicionário 'MESES.CNV'...
Traduzindo a coluna 'ESPEC' com o dicionário 'LEITOS.CNV'...
Traduzindo a coluna 'N_AIH' com o dicionário 'IDENTIFIC.CNV'...
Traduzindo a coluna 'IDENT' com o dicionário 'IDENT.CNV'...
Traduzindo a coluna 'MUNIC_RES' com o dicionário 'br_pndr.cnv'...
Traduzindo a coluna 'SEXO' com o dicionário 'SEXO.CNV'...
Traduzindo a coluna 'UTI_MES_TO' com o dicionário 'DIARIASUTI.CNV'...
Traduzindo a coluna 'MARCA_UTI' com o dicionário 'MARCAUTI.CNV'...
Traduzindo a coluna 'PROC_REA' com o dicionário 'PROCOBS2b.CNV'...
Traduzindo a coluna 'DT_INTER' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DT_SAIDA' com o dicionário 'ANOMESC.CNV'...
Traduzindo a coluna 'DIAG_PRINC' com o dicionário 'DIAGPACTO.CNV'...
Traduzindo a coluna 'DIAG_SECUN' com o dicionário 'CID10_22.CNV'...
Traduzindo a coluna 'COBRANCA' com o dicionário 'SAIDAPERM.CNV'...
Traduzindo a coluna 'NATUREZA' com o dicionário 'REGIME.CNV'...
Traduzindo a coluna 'NAT_JUR' com o dicionário 'ESFERAJURC.CNV'...
Traduzindo a coluna 'GESTAO' com o dicionário 'GESTAO.CNV'...
Traduzindo a coluna 'IND_VDRL' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'MUNIC_MOV' com o dicionário 'DistrFederal.CNV'...
Traduzindo a coluna 'COD_IDADE' com o dicionário 'IDADEDET.CNV'...
Traduzindo a coluna 'DIAS_PERM' com o dicionário 'PERM.CNV'...
Traduzindo a coluna 'MORTE' com o dicionário 'MORTES.CNV'...
Traduzindo a coluna 'NACIONAL' com o dicionário 'NACION3D.CNV'...
Traduzindo a coluna 'CAR_INT' com o dicionário 'CARATENDc.CNV'...
Traduzindo a coluna 'NUM_FILHOS' com o dicionário 'NUMFILH.CNV'...
Traduzindo a coluna 'INSTRU' com o dicionário 'INSTRU.CNV'...
Traduzindo a coluna 'CID_NOTIF' com o dicionário 'CID10_09.CNV'...
Traduzindo a coluna 'CONTRACEP1' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'CONTRACEP2' com o dicionário 'CONTRAC.CNV'...
Traduzindo a coluna 'GESTRISCO' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'INSC_PN' com o dicionário 'INSCPN.CNV'...
Traduzindo a coluna 'SEQ_AIH5' com o dicionário 'SEQAIH.CNV'...
Traduzindo a coluna 'CNAER' com o dicionário 'CNAE.CNV'...
Traduzindo a coluna 'VINCPREV' com o dicionário 'VINCPREV.CNV'...
Traduzindo a coluna 'INFEHOSP' com o dicionário 'SIMNAO.CNV'...
Traduzindo a coluna 'CID_ASSO' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'CID_MORTE' com o dicionário 'CID10_3D.CNV'...
Traduzindo a coluna 'COMPLEX' com o dicionário 'COMPLEX2.CNV'...
Traduzindo a coluna 'FINANC' com o dicionário 'FINANC.CNV'...
Traduzindo a coluna 'FAEC_TP' com o dicionário 'TP_FINAN.CNV'...
Traduzindo a coluna 'RACA_COR' com o dicionário 'RACACOR.CNV'...
Traduzindo a coluna 'ETNIA' com o dicionário 'ETNIA.CNV'...
Traduzindo a coluna 'TPDISEC1' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC2' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC3' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC4' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC5' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC6' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC7' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC8' com o dicionário 'TP_DIAGSEC.CNV'...
Traduzindo a coluna 'TPDISEC9' com o dicionário 'TP_DIAGSEC.CNV'...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2512_traduzido.csv

✓ Tradução SIH concluída.

### 4.4 Verificação do resultado

Mostra as colunas `_DESC` geradas em um arquivo de exemplo para confirmar que a tradução funcionou.

In [20]:
arquivos_traduzidos = sorted(PASTA_INTERIM.glob("*.csv"))
print(f"{len(arquivos_traduzidos)} arquivo(s) traduzido(s) em {PASTA_INTERIM}\n")

if arquivos_traduzidos:
    exemplo = arquivos_traduzidos[0]
    df_ex = pd.read_csv(exemplo, nrows=3)
    colunas_desc = [c for c in df_ex.columns if c.endswith("_DESC")]
    print(f"Exemplo: {exemplo.name}")
    print(f"Colunas _DESC geradas ({len(colunas_desc)}): {colunas_desc}\n")
    display(df_ex[colunas_desc].head(3))

661 arquivo(s) traduzido(s) em /home/carolina/Documents/TCC Documentos/TCC/data/interim

Exemplo: cnes_eq_eqsp1501_traduzido.csv
Colunas _DESC geradas (13): ['CODUFMUN_DESC', 'TPGESTAO_DESC', 'PF_PJ_DESC', 'NIV_DEP_DESC', 'ATIVIDAD_DESC', 'RETENCAO_DESC', 'NATUREZA_DESC', 'TP_UNID_DESC', 'NIV_HIER_DESC', 'TIPEQUIP_DESC', 'IND_SUS_DESC', 'COMPETEN_DESC', 'NAT_JUR_DESC']

,CODUFMUN_DESC,TPGESTAO_DESC,PF_PJ_DESC,NIV_DEP_DESC,ATIVIDAD_DESC,RETENCAO_DESC,NATUREZA_DESC,TP_UNID_DESC,NIV_HIER_DESC,TIPEQUIP_DESC,IND_SUS_DESC,COMPETEN_DESC,NAT_JUR_DESC
0,NaN,NaN,Pessoa Física,Individual,Unidade SEM atividade de Ensino,NaN,07-Empresa Privada,HOSPITAL/DIA - ISOLADO,NaN,EQUIPAMENTOS DE DIAGNÓSTICO POR IMAGEM,Equipamento para o SUS,NaN,NaN
1,NaN,NaN,Pessoa Física,Individual,Unidade SEM atividade de Ensino,NaN,07-Empresa Privada,HOSPITAL/DIA - ISOLADO,NaN,.. MAMOGRAFO COM ESTEREOTAXIA,Equipamento para o SUS,NaN,NaN
2,NaN,NaN,Não informado,NaN,Unidade SEM atividade de Ensino,NaN,"01-Administração Direta da Saúde (MS, SES, e SMS)",CENTRO DE SAUDE/UNIDADE BASICA,NaN,.. RAIO X MAIS DE 500MA,Equipamento para o SUS,NaN,NaN

## Preview dos Dados Coletados

In [21]:
# Preview do primeiro arquivo SIH gerado
if csvs_sih:
    df_preview_sih = pd.read_csv(csvs_sih[0], nrows=5)
    print(f"SIH — {csvs_sih[0].name}: {df_preview_sih.shape[0]} linhas (amostra) × {df_preview_sih.shape[1]} colunas")
    display(df_preview_sih.head())
else:
    print("Nenhum arquivo SIH encontrado em", PASTA_INPUT_SIH)

SIH — rdsp1501.csv: 5 linhas (amostra) × 113 colunas

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,...,DIAGSEC9,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7,TPDISEC8,TPDISEC9
0,350000,2015,1,5,46374500005315,3515104439726,1,13840040,353070,19781027,...,NaN,0,0,0,0,0,0,0,0,0
1,350000,2015,1,5,46374500005315,3515104439737,1,1121000,355030,19810830,...,NaN,0,0,0,0,0,0,0,0,0
2,350000,2015,1,5,46374500005315,3515104439748,1,8010020,355030,19901030,...,NaN,0,0,0,0,0,0,0,0,0
3,350000,2015,1,5,46374500005315,3515104439759,1,8010020,355030,19560905,...,NaN,0,0,0,0,0,0,0,0,0
4,350000,2015,1,5,46374500005315,3515104439760,1,14871000,352430,19730216,...,NaN,0,0,0,0,0,0,0,0,0

In [22]:
# Preview do primeiro arquivo CNES (ST) gerado
csvs_cnes_st = sorted(PASTA_INPUT_CNES.glob("st*.csv"))
if csvs_cnes_st:
    df_preview_cnes = pd.read_csv(csvs_cnes_st[0], nrows=5)
    print(f"CNES/ST — {csvs_cnes_st[0].name}: {df_preview_cnes.shape[0]} linhas (amostra) × {df_preview_cnes.shape[1]} colunas")
    display(df_preview_cnes.head())
else:
    print("Nenhum arquivo CNES/ST encontrado em", PASTA_INPUT_CNES)

CNES/ST — stsp1501.csv: 5 linhas (amostra) × 201 colunas

,CNES,CODUFMUN,COD_CEP,CPF_CNPJ,PF_PJ,NIV_DEP,CNPJ_MAN,COD_IR,REGSAUDE,MICR_REG,...,AP07CV01,AP07CV02,AP07CV05,AP07CV06,AP07CV03,AP07CV04,ATEND_PR,DT_ATUAL,COMPETEN,NAT_JUR
0,2025825,350010,17800000,92664130897,1,1,0,NaN,209,NaN,...,0,0,0,0,0,0,1,201406,201501,4000
1,2025833,350010,17800000,0,3,3,43008291000177,10.0,209,NaN,...,0,0,0,0,0,0,1,201402,201501,1031
2,2035766,350010,17800000,1558435000119,3,1,0,NaN,209,NaN,...,0,0,0,0,0,0,1,201306,201501,2240
3,2056100,350010,17800000,50115393000238,3,1,0,NaN,209,NaN,...,0,0,0,0,0,0,1,201412,201501,2240
4,2077647,350010,17800000,43002005000166,3,1,0,NaN,209,NaN,...,0,0,0,0,0,0,1,201412,201501,3999