# 01B · Tradução dos Códigos das Tabelas

## 0. Configuração do Ambiente

In [1]:
import sys
import os
import pandas as pd
from pathlib import Path

In [2]:
# Garante que a raiz do projeto está no sys.path para importar src/
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

print(f"Raiz do projeto: {ROOT}")

Raiz do projeto: /home/carolina/Documents/TCC Documentos/TCC

In [3]:
# Importa utilitários do projeto
from src.utils.download_data_from_datasus import download_data, download_dicionarios
from src.utils.converter_dbc_para_csv import converter_dbc_para_csv_lote

print("Utilitários importados")

Utilitários importados

## 4. Tradução dos Códigos das Tabelas

O DataSUS armazena os dados como **códigos numéricos** (ex: `1`, `3`, `M`). Esta seção
traduz esses códigos para **descrições legíveis** usando os dicionários `.cnv` e as
instruções `.def` baixados do FTP do DataSUS.

**Como funciona:**
1. O arquivo `.def` indica quais colunas têm código e qual `.cnv` usar para cada uma
2. O arquivo `.cnv` contém o mapeamento `CÓDIGO → DESCRIÇÃO`
3. Para cada coluna com dicionário é criada uma coluna `COLUNA_DESC` com o texto traduzido

**Resultado:** arquivos salvos em `data/interim/` com colunas `_DESC` adicionadas.

### 4.0 Download dos dicionários (executar apenas uma vez)

Os dicionários `.def` e `.cnv` são baixados do FTP do DataSUS e salvos em `data/external/`.
Se os arquivos já existirem localmente este passo pode ser pulado.

In [4]:
# Pasta destino ancorada em ROOT para não depender do diretório de trabalho do notebook
PASTA_EXTERNAL_SIH = Path(ROOT, "data", "external", "SIH")
PASTA_EXTERNAL_CNES = Path(ROOT, "data", "external", "CNES")
PASTA_EXTERNAL_SIH.mkdir(parents=True, exist_ok=True)
PASTA_EXTERNAL_CNES.mkdir(parents=True, exist_ok=True)

PASTA_INPUT_CNES = Path(ROOT, "data", "input", "CNES")
PASTA_INPUT_SIH= Path(ROOT, "data", "input", "SIH")

In [5]:
#Dicionários do CNES
download_dicionarios("CNES", str(PASTA_EXTERNAL_CNES))

#Dicionários do SIH
download_dicionarios("SIH", str(PASTA_EXTERNAL_SIH))

Conectando ao FTP para buscar tabelas de CNES: ftp.datasus.gov.br
Arquivo encontrado: TAB_CNES.zip. Baixando para a memória...

Extraindo dicionários (.cnv) e configurações (.def)...

Processo concluído! Arquivos salvos em: /home/carolina/Documents/TCC Documentos/TCC/data/external/CNES
Conectando ao FTP para buscar tabelas de SIH: ftp.datasus.gov.br

Arquivo encontrado: TAB_SIH.zip. Baixando para a memória...

Extraindo dicionários (.cnv) e configurações (.def)...

Processo concluído! Arquivos salvos em: /home/carolina/Documents/TCC Documentos/TCC/data/external/SIH

### 4.1 Configuração dos caminhos e importação dos utilitários

In [6]:
from src.utils.information_translation import mapear_colunas_def, traduzir_csv_datasus

# Caminhos dos dicionários — separados por sistema (CNES e SIH)
PASTA_DEF_CNES  = PASTA_EXTERNAL_CNES                    # arquivos .def do CNES
PASTA_CNV_CNES  = PASTA_EXTERNAL_CNES / "CNV"            # arquivos .cnv do CNES
PASTA_DEF_SIH   = PASTA_EXTERNAL_SIH                     # arquivos .def do SIH
PASTA_CNV_SIH   = PASTA_EXTERNAL_SIH / "CNV"             # arquivos .cnv do SIH

# Pasta de saída dos CSVs traduzidos
PASTA_INTERIM = Path(ROOT, "data", "interim")
PASTA_INTERIM.mkdir(parents=True, exist_ok=True)

print(f"DEF CNES : {PASTA_DEF_CNES}")
print(f"CNV CNES : {PASTA_CNV_CNES}")
print(f"DEF SIH  : {PASTA_DEF_SIH}")
print(f"CNV SIH  : {PASTA_CNV_SIH}")
print(f"Saída    : {PASTA_INTERIM}")

DEF CNES : /home/carolina/Documents/TCC Documentos/TCC/data/external/CNES
CNV CNES : /home/carolina/Documents/TCC Documentos/TCC/data/external/CNES/CNV
DEF SIH  : /home/carolina/Documents/TCC Documentos/TCC/data/external/SIH
CNV SIH  : /home/carolina/Documents/TCC Documentos/TCC/data/external/SIH/CNV
Saída    : /home/carolina/Documents/TCC Documentos/TCC/data/interim

### 4.2 Tradução de Teste (1 arquivo por tipo)
Rode esta célula para testar rapidamente a tradução em apenas 1 arquivo de cada tabela. Isso permite verificar os resultados antes de processar toda a base.

In [7]:
# Mapeamento CNES
MAPA_DEF_CNES = {
    'hb': 'Habilitacao.def',
    'lt': 'Leitos_Especialidade.def',
    'eq': 'Equipamento.def',
    'sr': 'Servico_Especializado_200803_.def',
    'st': 'Estabelecimento.def',
}

# Mapeamento SIH
defs_sih = list(PASTA_DEF_SIH.glob('RD*.def')) + list(PASTA_DEF_SIH.glob('RD*.DEF'))

In [8]:

print('--- TESTE DE TRADUÇÃO ---')
for prefixo, nome_def in MAPA_DEF_CNES.items():
    csvs = sorted(PASTA_INPUT_CNES.glob(f'{prefixo}*.csv'))
    if not csvs: continue
    
    arquivo_def = PASTA_DEF_CNES / nome_def
    mapa = mapear_colunas_def(str(arquivo_def))
    if not mapa: continue
    
    csv_teste = csvs[0] # Pega apenas o primeiro
    caminho_saida = PASTA_INTERIM / f'cnes_{prefixo}_{csv_teste.stem}_traduzido_teste.csv'
    import json as json_lib
    path_dict_cnes = Path(ROOT, 'data', 'external', f'dicionario_CNES_{prefixo.upper()}.json')
    rename_dict_cnes = None
    if path_dict_cnes.exists():
        with open(path_dict_cnes, 'r', encoding='utf-8') as f:
            schema_cnes = json_lib.load(f)
        rename_dict_cnes = {col['old_name']: col['new_name'] for col in schema_cnes}
    traduzir_csv_datasus(str(csv_teste), mapa, str(PASTA_CNV_CNES), str(caminho_saida), dicionario_renomeacao=rename_dict_cnes)


if defs_sih:
    mapa_sih = mapear_colunas_def(str(defs_sih[0]))
    csvs_sih = sorted(PASTA_INPUT_SIH.glob('*.csv'))
    if csvs_sih:
        csv_teste = csvs_sih[0]
        caminho_saida = PASTA_INTERIM / f'sih_{csv_teste.stem}_traduzido_teste.csv'
        import json as json_lib
        with open(Path(ROOT, 'data', 'external', 'dicionario_SIH.json'), 'r', encoding='utf-8') as f:
            schema = json_lib.load(f)
        rename_dict_sih = {col['old_name']: col['new_name'] for col in schema}
        traduzir_csv_datasus(str(csv_teste), mapa_sih, str(PASTA_CNV_SIH), str(caminho_saida), dicionario_renomeacao=rename_dict_sih)

--- TESTE DE TRADUÇÃO ---

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1501_traduzido_teste.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1501_traduzido_teste.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1501_traduzido_teste.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1501_traduzido_teste.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])
/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1501_traduzido_teste.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1501_traduzido_teste.csv

### 4.3 Tradução Completa em Lote (Multiprocessamento - CPU)
Rode esta célula para processar **todos os arquivos** simultaneamente usando os 16 núcleos do seu processador.

In [9]:
import concurrent.futures

def processar_arquivo(args):
    caminho_csv, mapa, pasta_cnv, caminho_saida, rename_dict = args
    if not caminho_saida.exists():
        traduzir_csv_datasus(caminho_csv, mapa, pasta_cnv, str(caminho_saida), dicionario_renomeacao=rename_dict)
    return caminho_saida.name

tarefas = []

In [10]:

# Prepara tarefas CNES
for prefixo, nome_def in MAPA_DEF_CNES.items():
    csvs = sorted(PASTA_INPUT_CNES.glob(f'{prefixo}*.csv'))
    arquivo_def = PASTA_DEF_CNES / nome_def
    if not arquivo_def.exists(): continue
    mapa = mapear_colunas_def(str(arquivo_def))
    if not mapa: continue
    
    path_dict_cnes = Path(ROOT, 'data', 'external', f'dicionario_CNES_{prefixo.upper()}.json')
    rename_dict_cnes = None
    if path_dict_cnes.exists():
        import json as json_lib
        with open(path_dict_cnes, 'r', encoding='utf-8') as f:
            schema_cnes = json_lib.load(f)
        rename_dict_cnes = {col['old_name']: col['new_name'] for col in schema_cnes}
    
    for csv_path in csvs:
        caminho_saida = PASTA_INTERIM / f'cnes_{prefixo}_{csv_path.stem}_traduzido.csv'
        tarefas.append((str(csv_path), mapa, str(PASTA_CNV_CNES), caminho_saida, rename_dict_cnes))

In [11]:
# Prepara tarefas SIH
if defs_sih:
    mapa_sih = mapear_colunas_def(str(defs_sih[0]))
    import json as json_lib
    with open(Path(ROOT, 'data', 'external', 'dicionario_SIH.json'), 'r', encoding='utf-8') as f:
        schema = json_lib.load(f)
    rename_dict_sih = {col['old_name']: col['new_name'] for col in schema}
    for csv_path in sorted(PASTA_INPUT_SIH.glob('*.csv')):
        caminho_saida = PASTA_INTERIM / f'sih_{csv_path.stem}_traduzido.csv'
        tarefas.append((str(csv_path), mapa_sih, str(PASTA_CNV_SIH), caminho_saida, rename_dict_sih))

In [12]:
print(f'Iniciando tradução de {len(tarefas)} arquivos utilizando multiprocessamento...')

with concurrent.futures.ProcessPoolExecutor() as executor:
    resultados = list(executor.map(processar_arquivo, tarefas))

print(f'\n✓ Tradução completa finalizada! {len(resultados)} arquivos salvos na pasta interim.')

Iniciando tradução de 792 arquivos utilizando multiprocessamento...

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1603_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1601_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1602_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1604_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1606_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1611_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1605_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1609_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1608_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1705_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1704_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1702_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1610_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1706_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1612_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1701_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1607_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1703_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1707_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1708_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1805_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1710_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1712_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1811_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1807_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1802_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1806_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1803_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1709_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1711_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1810_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1801_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1804_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1808_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1809_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1812_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1901_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1903_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1902_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1905_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1908_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1907_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1904_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1909_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1906_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2001_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1911_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1912_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp1910_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2003_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2002_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2004_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2005_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2008_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2006_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2007_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2011_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2010_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2009_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2012_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2103_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2101_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2102_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2106_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2104_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2105_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2107_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2108_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2110_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2109_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2111_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2112_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2202_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2206_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2201_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2204_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2208_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2205_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2210_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2203_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2207_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2209_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2211_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2212_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2301_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2302_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2303_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2305_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2307_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2304_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2306_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2310_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2403_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2308_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2311_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2312_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2401_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2309_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2402_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2404_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2405_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2406_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2408_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2407_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2412_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2409_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2411_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2410_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1601_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1602_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1604_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1603_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1605_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1609_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1606_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1607_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1608_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1610_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1612_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1611_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1701_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1702_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1703_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1704_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1709_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1708_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1706_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1707_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1705_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hb_hbsp2512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1710_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1712_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1711_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1801_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1803_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1804_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1805_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1806_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1802_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1807_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1809_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1810_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1808_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1811_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1812_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1901_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1902_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1903_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1904_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1906_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1905_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1909_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1907_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1908_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1911_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1910_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2001_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp1912_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2002_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2003_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2005_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2004_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2006_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2007_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2008_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2009_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2010_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2102_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2101_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2103_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2011_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2104_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2012_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2105_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2106_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2107_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2109_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2110_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2108_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2112_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2111_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2201_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2202_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2203_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2205_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2207_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2204_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2209_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2206_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2210_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2208_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2211_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2212_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2301_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2302_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2303_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2306_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2305_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2304_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2309_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2311_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2308_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2310_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2307_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2312_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2401_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2402_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2403_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2404_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2405_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2406_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2407_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2408_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2409_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2411_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2410_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2412_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_lt_ltsp2511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1601_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1602_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1604_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1603_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1605_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1606_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1607_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1610_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1612_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1608_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1611_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1703_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1609_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1702_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1705_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1701_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1704_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1706_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1707_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1708_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1710_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1711_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1709_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1801_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1802_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1712_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1809_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1803_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1804_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1807_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1810_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1806_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1805_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1812_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1808_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1811_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1903_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1902_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1904_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1905_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1901_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1909_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2003_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1908_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1912_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1910_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2004_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1906_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1907_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2002_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp1911_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2001_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2006_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2005_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2007_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2008_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2009_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2010_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2101_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2012_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2107_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2011_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2102_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2105_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2106_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2103_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2108_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2104_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2112_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2109_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2110_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2201_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2111_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2202_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2203_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2204_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2205_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2206_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2207_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2208_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2209_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2210_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2211_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2212_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2301_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2302_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2304_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2303_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2305_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2306_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2307_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2309_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2308_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2310_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2311_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2312_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2401_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2402_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2403_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2404_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2406_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2408_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2407_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2410_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2411_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2405_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2409_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2412_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_eq_eqsp2511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1601_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1602_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1603_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1604_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1605_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1607_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1608_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1611_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1606_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1610_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1612_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1609_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1701_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1703_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1702_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1705_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1704_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1708_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1707_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1706_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1709_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1710_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1802_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1711_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1803_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1712_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1801_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1804_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1805_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1806_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1808_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1809_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1807_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1812_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1811_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1810_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1901_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1909_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1904_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1908_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1906_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1905_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1903_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1907_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1902_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1910_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1911_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2001_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp1912_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2002_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2003_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2004_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2005_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2008_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2006_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2007_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2011_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2010_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2012_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2009_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2101_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2102_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2103_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2105_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2104_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2107_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2108_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2106_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2109_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2201_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2110_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2203_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2111_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2202_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2205_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2112_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2204_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2206_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2207_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2209_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2208_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2211_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2212_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2210_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2301_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2302_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2310_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2309_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2303_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2304_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2307_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2306_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2308_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2305_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2311_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2312_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2401_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2402_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2403_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2404_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2405_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2407_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2409_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2410_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2412_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2411_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2408_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2406_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2505_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2510_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2512_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_sr_srsp2511_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1511_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1512_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1602_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1601_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1603_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1604_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1607_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1606_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1605_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1608_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1609_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1610_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1612_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1611_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1701_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1702_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1703_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1704_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1705_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1706_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1707_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1708_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1710_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1712_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1709_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1711_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1802_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1803_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1804_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1801_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1805_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1806_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1807_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1808_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1809_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1810_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1812_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1811_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1902_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1905_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1904_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1901_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1906_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1909_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1908_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1903_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1910_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1907_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1911_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2003_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2001_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2004_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp1912_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2002_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2005_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2006_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2007_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2011_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2010_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2102_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2101_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2008_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2009_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2012_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2103_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2104_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2106_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2105_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2108_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2107_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2109_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2111_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2201_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2110_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2203_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2205_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2202_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2204_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2112_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2207_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2206_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2208_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2209_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2210_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2212_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2211_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2302_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2301_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2305_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2303_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2306_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2304_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2309_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2307_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2308_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2310_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2311_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2312_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2403_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2402_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2401_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2404_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2405_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2406_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2407_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2409_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2410_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2411_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2412_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2408_traduzido.csv

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

/home/carolina/Documents/TCC Documentos/TCC/src/utils/information_translation.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[coluna_csv] = pd.to_datetime(valores_limpos, format='%Y%m%d', errors='coerce').dt.strftime('%Y-%m-%d').fillna(df[coluna_csv])

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_st_stsp2511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1508_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1602_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1601_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1604_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1603_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1605_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1609_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1606_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1610_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1607_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1611_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1608_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1702_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1612_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1701_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1704_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1703_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1707_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1705_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1706_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1709_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1801_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1708_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1710_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1802_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1712_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1711_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1803_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1804_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1805_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1806_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1808_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1807_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1902_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1811_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1809_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1812_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1906_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1901_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1904_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1903_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1907_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1905_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1810_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1909_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1912_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1911_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1910_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp1908_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2004_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2005_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2006_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2008_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2007_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2009_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2010_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2002_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2003_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2001_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2011_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2012_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2102_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2101_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2104_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2103_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2105_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2106_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2107_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2109_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2202_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2108_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2110_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2111_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2201_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2112_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2203_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2204_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2206_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2205_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2207_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2302_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2209_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2208_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2210_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2211_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2301_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2212_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2304_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2303_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2305_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2306_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2307_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2312_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2311_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2402_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2310_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2308_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2309_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2403_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2406_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2409_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2401_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2407_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2404_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2405_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2408_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2410_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2411_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2412_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2502_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2501_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2503_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2512_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2504_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2509_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2506_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2510_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2511_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2507_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2505_traduzido.csv

Sucesso! O arquivo traduzido foi salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_rdsp2508_traduzido.csv

✓ Tradução completa finalizada! 792 arquivos salvos na pasta interim.

### 4.4 Verificação do resultado

Mostra as colunas `_DESC` geradas em um arquivo de exemplo para confirmar que a tradução funcionou.

In [13]:
arquivos_traduzidos = sorted(PASTA_INTERIM.glob("*.csv"))
print(f"{len(arquivos_traduzidos)} arquivo(s) traduzido(s) em {PASTA_INTERIM}\n")

if arquivos_traduzidos:
    exemplo = arquivos_traduzidos[0]
    df_ex = pd.read_csv(exemplo, nrows=3, low_memory=False)
    colunas_desc = [c for c in df_ex.columns if c.endswith("_DESC")]
    print(f"Exemplo: {exemplo.name}")
    print(f"Colunas _DESC geradas ({len(colunas_desc)}): {colunas_desc}\n")
    display(df_ex[colunas_desc].head(3))

798 arquivo(s) traduzido(s) em /home/carolina/Documents/TCC Documentos/TCC/data/interim

Exemplo: cnes_eq_eqsp1501_traduzido.csv
Colunas _DESC geradas (0): []

Empty DataFrame
Columns: []
Index: [0, 1, 2]

## Preview dos Dados Coletados

In [14]:
# Preview do primeiro arquivo CNES (ST) traduzido
csvs_cnes_st_traduzidos = sorted(PASTA_INTERIM.glob("cnes_st*.csv"))
if csvs_cnes_st_traduzidos:
    df_preview_cnes = pd.read_csv(csvs_cnes_st_traduzidos[0], nrows=5, low_memory=False)
    print(f"CNES/ST Traduzido — {csvs_cnes_st_traduzidos[0].name}: {df_preview_cnes.shape[0]} linhas (amostra) × {df_preview_cnes.shape[1]} colunas")
    display(df_preview_cnes.head())
else:
    print("Nenhum arquivo CNES/ST traduzido encontrado em", PASTA_INTERIM)

CNES/ST Traduzido — cnes_st_stsp1501_traduzido.csv: 5 linhas (amostra) × 250 colunas

,codigo_cnes,codigo_municipio_cod,cep_estabelecimento,cpf_cnpj_estabelecimento,tipo_pessoa_cod,nivel_dependencia_cod,cnpj_mantenedora,codigo_retencao_mantenedora_cod,codigo_regiao_saude,codigo_micro_regiao_saude,...,comissao_apropriacao_custos,comissao_cipa,comissao_revisao_prontuarios,comissao_revisao_documentacao,comissao_analise_obitos_biopsias,comissao_investigacao_epidemiologica,comissao_notificacao_doencas,comissao_zoonoses_vetores,competencia,natureza_juridica
0,2025825,350010,17800000,92664130897,1,1,0,NaN,209,NaN,...,Não Tem Comissão Apropriação de Custos,Não Tem Comissão CIPA,Não Tem Comissão Revisão Prontuários,Não Tem Comissão Revisão Docum.Médica/Estatísca,Não Tem Comissão Análise de Óbitos/Biópsias,Não Tem Comissão Investigação Epidemiológica,Não Tem Comissão Notificação de Doenças,Não Tem Comissão Controle Zoonoses/Vetores,Jan/2015,Pessoas Físicas
1,2025833,350010,17800000,0,3,3,43008291000177,10.0,209,NaN,...,Não Tem Comissão Apropriação de Custos,Não Tem Comissão CIPA,Não Tem Comissão Revisão Prontuários,Não Tem Comissão Revisão Docum.Médica/Estatísca,Não Tem Comissão Análise de Óbitos/Biópsias,Não Tem Comissão Investigação Epidemiológica,Não Tem Comissão Notificação de Doenças,Não Tem Comissão Controle Zoonoses/Vetores,Jan/2015,Administração Pública Municipal
2,2035766,350010,17800000,1558435000119,3,1,0,NaN,209,NaN,...,Não Tem Comissão Apropriação de Custos,Não Tem Comissão CIPA,Não Tem Comissão Revisão Prontuários,Não Tem Comissão Revisão Docum.Médica/Estatísca,Não Tem Comissão Análise de Óbitos/Biópsias,Não Tem Comissão Investigação Epidemiológica,Não Tem Comissão Notificação de Doenças,Não Tem Comissão Controle Zoonoses/Vetores,Jan/2015,Demais Entidades Empresariais
3,2056100,350010,17800000,50115393000238,3,1,0,NaN,209,NaN,...,Não Tem Comissão Apropriação de Custos,Não Tem Comissão CIPA,Não Tem Comissão Revisão Prontuários,Não Tem Comissão Revisão Docum.Médica/Estatísca,Não Tem Comissão Análise de Óbitos/Biópsias,Não Tem Comissão Investigação Epidemiológica,Não Tem Comissão Notificação de Doenças,Não Tem Comissão Controle Zoonoses/Vetores,Jan/2015,Demais Entidades Empresariais
4,2077647,350010,17800000,43002005000166,3,1,0,NaN,209,NaN,...,Não Tem Comissão Apropriação de Custos,Tem Comissão CIPA,Tem Comissão Revisão Prontuários,Não Tem Comissão Revisão Docum.Médica/Estatísca,Não Tem Comissão Análise de Óbitos/Biópsias,Não Tem Comissão Investigação Epidemiológica,Tem Comissão Notificação de Doenças,Não Tem Comissão Controle Zoonoses/Vetores,Jan/2015,Entidades sem Fins Lucrativos