# 02 · ETL e Integração SIH + CNES

**Objetivo:** Carregar os dados traduzidos do SIH e CNES, filtrar internações por IAM (CID I21), realizar limpeza e integrar as duas bases em uma base de modelagem unificada.

**Inputs:**
- `data/interim/sih_*_traduzido.csv` — registros de AIH do SIH com colunas `_DESC` de códigos traduzidos
- `data/interim/cnes_*_traduzido.csv` — tabelas do CNES (ST, LT, EQ, SR, HB) com colunas `_DESC` traduzidas
- `data/external/dicionario_SIH.json` — mapeamento de nomes de colunas do SIH
- `data/external/dicionario_CNES_*.json` — mapeamentos de nomes de colunas do CNES

**Outputs gerados:**
- `data/interim/sih_iam.csv` — internações por IAM (base limpa SIH)
- `data/interim/cnes_hospitais.csv` — base mestre de hospitais (CNES consolidado)
- `data/processed/base_modelagem.csv` — base final SIH × CNES pronta para modelagem

## 0. Configuração do Ambiente

In [1]:
import pandas as pd
import numpy as np
import os
import json
from pathlib import Path
import sys
import gc

In [2]:
# Adiciona a raiz do projeto ao sys.path para importar src/
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

print(f"Raiz do projeto: {ROOT}")

Raiz do projeto: /home/carolina/Documents/TCC Documentos/TCC

In [3]:
pd.set_option('display.float_format', '{:.2f}'.format)

# ── Caminhos ───────────────────────────────────────────────────────────
# Os CSVs de entrada agora são os arquivos *traduzidos* gerados pelo
# notebook 01_data_collection.ipynb e salvos em data/interim/
INTERIM   = Path(ROOT, 'data', 'interim')    # traduzidos (input) e outputs do ETL
PROCESSED = Path(ROOT, 'data', 'processed')
EXTERNAL  = Path(ROOT, 'data', 'external')

INTERIM.mkdir(parents=True, exist_ok=True)
PROCESSED.mkdir(parents=True, exist_ok=True)

print("Caminhos configurados:")
print(f"  Entrada: {INTERIM}")
print(f"  Saída  : {PROCESSED}")

Caminhos configurados:
  Entrada: /home/carolina/Documents/TCC Documentos/TCC/data/interim
  Saída  : /home/carolina/Documents/TCC Documentos/TCC/data/processed

## 1. Carregamento e Padronização do SIH

### 1.1 Leitura dos arquivos

Concatenamos **todos** os arquivos CSV disponíveis em `data/input/SIH/`.
O dicionário `dicionario_SIH.json` é usado para renomear as colunas para nomes legíveis.

In [18]:
# Lê os CSVs traduzidos do SIH (padrão: sih_*_traduzido.csv)
arquivos_sih = sorted(INTERIM.glob('sih_*_traduzido.csv'))
print(f"Arquivos SIH traduzidos encontrados: {len(arquivos_sih)}")
for f in arquivos_sih:
    print(f"  {f.name}")

Arquivos SIH traduzidos encontrados: 121
  sih_rdsp1501_traduzido.csv
  sih_rdsp1502_traduzido.csv
  sih_rdsp1503_traduzido.csv
  sih_rdsp1504_traduzido.csv
  sih_rdsp1505_traduzido.csv
  sih_rdsp1506_traduzido.csv
  sih_rdsp1507_traduzido.csv
  sih_rdsp1508_traduzido.csv
  sih_rdsp1509_traduzido.csv
  sih_rdsp1510_traduzido.csv
  sih_rdsp1512_traduzido.csv
  sih_rdsp1601_traduzido.csv
  sih_rdsp1602_traduzido.csv
  sih_rdsp1603_traduzido.csv
  sih_rdsp1604_traduzido.csv
  sih_rdsp1605_traduzido.csv
  sih_rdsp1606_traduzido.csv
  sih_rdsp1607_traduzido.csv
  sih_rdsp1608_traduzido.csv
  sih_rdsp1609_traduzido.csv
  sih_rdsp1610_traduzido.csv
  sih_rdsp1612_traduzido.csv
  sih_rdsp1701_traduzido.csv
  sih_rdsp1702_traduzido.csv
  sih_rdsp1703_traduzido.csv
  sih_rdsp1704_traduzido.csv
  sih_rdsp1705_traduzido.csv
  sih_rdsp1706_traduzido.csv
  sih_rdsp1707_traduzido.csv
  sih_rdsp1708_traduzido.csv
  sih_rdsp1709_traduzido.csv
  sih_rdsp1710_traduzido.csv
  sih_rdsp1712_traduzido.csv
  sih_rdsp1801_traduzido.csv
  sih_rdsp1802_traduzido.csv
  sih_rdsp1803_traduzido.csv
  sih_rdsp1804_traduzido.csv
  sih_rdsp1805_traduzido.csv
  sih_rdsp1806_traduzido.csv
  sih_rdsp1807_traduzido.csv
  sih_rdsp1808_traduzido.csv
  sih_rdsp1809_traduzido.csv
  sih_rdsp1810_traduzido.csv
  sih_rdsp1812_traduzido.csv
  sih_rdsp1901_traduzido.csv
  sih_rdsp1902_traduzido.csv
  sih_rdsp1903_traduzido.csv
  sih_rdsp1904_traduzido.csv
  sih_rdsp1905_traduzido.csv
  sih_rdsp1906_traduzido.csv
  sih_rdsp1907_traduzido.csv
  sih_rdsp1908_traduzido.csv
  sih_rdsp1909_traduzido.csv
  sih_rdsp1910_traduzido.csv
  sih_rdsp1912_traduzido.csv
  sih_rdsp2001_traduzido.csv
  sih_rdsp2002_traduzido.csv
  sih_rdsp2003_traduzido.csv
  sih_rdsp2004_traduzido.csv
  sih_rdsp2005_traduzido.csv
  sih_rdsp2006_traduzido.csv
  sih_rdsp2007_traduzido.csv
  sih_rdsp2008_traduzido.csv
  sih_rdsp2009_traduzido.csv
  sih_rdsp2010_traduzido.csv
  sih_rdsp2012_traduzido.csv
  sih_rdsp2101_traduzido.csv
  sih_rdsp2102_traduzido.csv
  sih_rdsp2103_traduzido.csv
  sih_rdsp2104_traduzido.csv
  sih_rdsp2105_traduzido.csv
  sih_rdsp2106_traduzido.csv
  sih_rdsp2107_traduzido.csv
  sih_rdsp2108_traduzido.csv
  sih_rdsp2109_traduzido.csv
  sih_rdsp2110_traduzido.csv
  sih_rdsp2112_traduzido.csv
  sih_rdsp2201_traduzido.csv
  sih_rdsp2202_traduzido.csv
  sih_rdsp2203_traduzido.csv
  sih_rdsp2204_traduzido.csv
  sih_rdsp2205_traduzido.csv
  sih_rdsp2206_traduzido.csv
  sih_rdsp2207_traduzido.csv
  sih_rdsp2208_traduzido.csv
  sih_rdsp2209_traduzido.csv
  sih_rdsp2210_traduzido.csv
  sih_rdsp2212_traduzido.csv
  sih_rdsp2301_traduzido.csv
  sih_rdsp2302_traduzido.csv
  sih_rdsp2303_traduzido.csv
  sih_rdsp2304_traduzido.csv
  sih_rdsp2305_traduzido.csv
  sih_rdsp2306_traduzido.csv
  sih_rdsp2307_traduzido.csv
  sih_rdsp2308_traduzido.csv
  sih_rdsp2309_traduzido.csv
  sih_rdsp2310_traduzido.csv
  sih_rdsp2312_traduzido.csv
  sih_rdsp2401_traduzido.csv
  sih_rdsp2402_traduzido.csv
  sih_rdsp2403_traduzido.csv
  sih_rdsp2404_traduzido.csv
  sih_rdsp2405_traduzido.csv
  sih_rdsp2406_traduzido.csv
  sih_rdsp2407_traduzido.csv
  sih_rdsp2408_traduzido.csv
  sih_rdsp2409_traduzido.csv
  sih_rdsp2410_traduzido.csv
  sih_rdsp2412_traduzido.csv
  sih_rdsp2501_traduzido.csv
  sih_rdsp2502_traduzido.csv
  sih_rdsp2503_traduzido.csv
  sih_rdsp2504_traduzido.csv
  sih_rdsp2505_traduzido.csv
  sih_rdsp2506_traduzido.csv
  sih_rdsp2507_traduzido.csv
  sih_rdsp2508_traduzido.csv
  sih_rdsp2509_traduzido.csv
  sih_rdsp2510_traduzido.csv
  sih_rdsp2512_traduzido.csv

In [19]:
# Carrega e renomeia colunas usando o dicionário externo
path_dicionario = Path(ROOT, 'data', 'external', 'dicionario_SIH.json')
with open(path_dicionario, 'r', encoding='utf-8') as f:
    schema = json.load(f)

rename_dict = {col["old_name"]: col["new_name"] for col in schema}

In [20]:
# Concatena todos os meses aplicando o filtro IAM DURANTE a leitura
# — lê em chunks de 50 000 linhas, filtra por CID I21 imediatamente
# — acumula apenas as linhas IAM
CID_PREFIXO = "I21"
CHUNK_SIZE  = 50_000

frames = []
for i, arq in enumerate(arquivos_sih, 1):
    chunks_iam = []
    try:
        reader = pd.read_csv(arq, dtype=str, low_memory=False, chunksize=CHUNK_SIZE)
        for chunk in reader:
            chunk = chunk.rename(columns=rename_dict)
            chunk["diagnostico_principal"]  = chunk["diagnostico_principal"].astype(str)
            chunk["diagnostico_secundario"] = chunk["diagnostico_secundario"].astype(str)
            mask = (
                chunk["diagnostico_principal"].str.startswith(CID_PREFIXO) |
                chunk["diagnostico_secundario"].str.startswith(CID_PREFIXO)
            )
            iam_chunk = chunk[mask]
            if not iam_chunk.empty:
                chunks_iam.append(iam_chunk)
            del chunk, iam_chunk, mask
            gc.collect()
        if chunks_iam:
            frames.append(pd.concat(chunks_iam, ignore_index=True))
        del chunks_iam
        gc.collect()
        print(f"  [{i:>3}/{len(arquivos_sih)}] {arq.name} — OK")
    except Exception as e:
        print(f"  [{i:>3}/{len(arquivos_sih)}] {arq.name} — ERRO: {e}")
df_iam = pd.concat(frames, ignore_index=True)
del frames
gc.collect()
print(f"\nSIH-IAM carregado: {df_iam.shape[0]:,} registros × {df_iam.shape[1]} colunas")
df_iam.head(3)

  [  1/121] sih_rdsp1501_traduzido.csv — OK
  [  2/121] sih_rdsp1502_traduzido.csv — OK
  [  3/121] sih_rdsp1503_traduzido.csv — OK
  [  4/121] sih_rdsp1504_traduzido.csv — OK
  [  5/121] sih_rdsp1505_traduzido.csv — OK
  [  6/121] sih_rdsp1506_traduzido.csv — OK
  [  7/121] sih_rdsp1507_traduzido.csv — OK
  [  8/121] sih_rdsp1508_traduzido.csv — OK
  [  9/121] sih_rdsp1509_traduzido.csv — OK
  [ 10/121] sih_rdsp1510_traduzido.csv — OK
  [ 11/121] sih_rdsp1512_traduzido.csv — OK
  [ 12/121] sih_rdsp1601_traduzido.csv — OK
  [ 13/121] sih_rdsp1602_traduzido.csv — OK
  [ 14/121] sih_rdsp1603_traduzido.csv — OK
  [ 15/121] sih_rdsp1604_traduzido.csv — OK
  [ 16/121] sih_rdsp1605_traduzido.csv — OK
  [ 17/121] sih_rdsp1606_traduzido.csv — OK
  [ 18/121] sih_rdsp1607_traduzido.csv — OK
  [ 19/121] sih_rdsp1608_traduzido.csv — OK
  [ 20/121] sih_rdsp1609_traduzido.csv — OK
  [ 21/121] sih_rdsp1610_traduzido.csv — OK
  [ 22/121] sih_rdsp1612_traduzido.csv — OK
  [ 23/121] sih_rdsp1701_traduzido.csv — OK
  [ 24/121] sih_rdsp1702_traduzido.csv — OK
  [ 25/121] sih_rdsp1703_traduzido.csv — OK
  [ 26/121] sih_rdsp1704_traduzido.csv — OK
  [ 27/121] sih_rdsp1705_traduzido.csv — OK
  [ 28/121] sih_rdsp1706_traduzido.csv — OK
  [ 29/121] sih_rdsp1707_traduzido.csv — OK
  [ 30/121] sih_rdsp1708_traduzido.csv — OK
  [ 31/121] sih_rdsp1709_traduzido.csv — OK
  [ 32/121] sih_rdsp1710_traduzido.csv — OK
  [ 33/121] sih_rdsp1712_traduzido.csv — OK
  [ 34/121] sih_rdsp1801_traduzido.csv — OK
  [ 35/121] sih_rdsp1802_traduzido.csv — OK
  [ 36/121] sih_rdsp1803_traduzido.csv — OK
  [ 37/121] sih_rdsp1804_traduzido.csv — OK
  [ 38/121] sih_rdsp1805_traduzido.csv — OK
  [ 39/121] sih_rdsp1806_traduzido.csv — OK
  [ 40/121] sih_rdsp1807_traduzido.csv — OK
  [ 41/121] sih_rdsp1808_traduzido.csv — OK
  [ 42/121] sih_rdsp1809_traduzido.csv — OK
  [ 43/121] sih_rdsp1810_traduzido.csv — OK
  [ 44/121] sih_rdsp1812_traduzido.csv — OK
  [ 45/121] sih_rdsp1901_traduzido.csv — OK
  [ 46/121] sih_rdsp1902_traduzido.csv — OK
  [ 47/121] sih_rdsp1903_traduzido.csv — OK
  [ 48/121] sih_rdsp1904_traduzido.csv — OK
  [ 49/121] sih_rdsp1905_traduzido.csv — OK
  [ 50/121] sih_rdsp1906_traduzido.csv — OK
  [ 51/121] sih_rdsp1907_traduzido.csv — OK
  [ 52/121] sih_rdsp1908_traduzido.csv — OK
  [ 53/121] sih_rdsp1909_traduzido.csv — OK
  [ 54/121] sih_rdsp1910_traduzido.csv — OK
  [ 55/121] sih_rdsp1912_traduzido.csv — OK
  [ 56/121] sih_rdsp2001_traduzido.csv — OK
  [ 57/121] sih_rdsp2002_traduzido.csv — OK
  [ 58/121] sih_rdsp2003_traduzido.csv — OK
  [ 59/121] sih_rdsp2004_traduzido.csv — OK
  [ 60/121] sih_rdsp2005_traduzido.csv — OK
  [ 61/121] sih_rdsp2006_traduzido.csv — OK
  [ 62/121] sih_rdsp2007_traduzido.csv — OK
  [ 63/121] sih_rdsp2008_traduzido.csv — OK
  [ 64/121] sih_rdsp2009_traduzido.csv — OK
  [ 65/121] sih_rdsp2010_traduzido.csv — OK
  [ 66/121] sih_rdsp2012_traduzido.csv — OK
  [ 67/121] sih_rdsp2101_traduzido.csv — OK
  [ 68/121] sih_rdsp2102_traduzido.csv — OK
  [ 69/121] sih_rdsp2103_traduzido.csv — OK
  [ 70/121] sih_rdsp2104_traduzido.csv — OK
  [ 71/121] sih_rdsp2105_traduzido.csv — OK
  [ 72/121] sih_rdsp2106_traduzido.csv — OK
  [ 73/121] sih_rdsp2107_traduzido.csv — OK
  [ 74/121] sih_rdsp2108_traduzido.csv — OK
  [ 75/121] sih_rdsp2109_traduzido.csv — OK
  [ 76/121] sih_rdsp2110_traduzido.csv — OK
  [ 77/121] sih_rdsp2112_traduzido.csv — OK
  [ 78/121] sih_rdsp2201_traduzido.csv — OK
  [ 79/121] sih_rdsp2202_traduzido.csv — OK
  [ 80/121] sih_rdsp2203_traduzido.csv — OK
  [ 81/121] sih_rdsp2204_traduzido.csv — OK
  [ 82/121] sih_rdsp2205_traduzido.csv — OK
  [ 83/121] sih_rdsp2206_traduzido.csv — OK
  [ 84/121] sih_rdsp2207_traduzido.csv — OK
  [ 85/121] sih_rdsp2208_traduzido.csv — OK
  [ 86/121] sih_rdsp2209_traduzido.csv — OK
  [ 87/121] sih_rdsp2210_traduzido.csv — OK
  [ 88/121] sih_rdsp2212_traduzido.csv — OK
  [ 89/121] sih_rdsp2301_traduzido.csv — OK
  [ 90/121] sih_rdsp2302_traduzido.csv — OK
  [ 91/121] sih_rdsp2303_traduzido.csv — OK
  [ 92/121] sih_rdsp2304_traduzido.csv — OK
  [ 93/121] sih_rdsp2305_traduzido.csv — OK
  [ 94/121] sih_rdsp2306_traduzido.csv — OK
  [ 95/121] sih_rdsp2307_traduzido.csv — OK
  [ 96/121] sih_rdsp2308_traduzido.csv — OK
  [ 97/121] sih_rdsp2309_traduzido.csv — OK
  [ 98/121] sih_rdsp2310_traduzido.csv — OK
  [ 99/121] sih_rdsp2312_traduzido.csv — OK
  [100/121] sih_rdsp2401_traduzido.csv — OK
  [101/121] sih_rdsp2402_traduzido.csv — OK
  [102/121] sih_rdsp2403_traduzido.csv — OK
  [103/121] sih_rdsp2404_traduzido.csv — OK
  [104/121] sih_rdsp2405_traduzido.csv — OK
  [105/121] sih_rdsp2406_traduzido.csv — OK
  [106/121] sih_rdsp2407_traduzido.csv — OK
  [107/121] sih_rdsp2408_traduzido.csv — OK
  [108/121] sih_rdsp2409_traduzido.csv — OK
  [109/121] sih_rdsp2410_traduzido.csv — OK
  [110/121] sih_rdsp2412_traduzido.csv — OK
  [111/121] sih_rdsp2501_traduzido.csv — OK
  [112/121] sih_rdsp2502_traduzido.csv — OK
  [113/121] sih_rdsp2503_traduzido.csv — OK
  [114/121] sih_rdsp2504_traduzido.csv — OK
  [115/121] sih_rdsp2505_traduzido.csv — OK
  [116/121] sih_rdsp2506_traduzido.csv — OK
  [117/121] sih_rdsp2507_traduzido.csv — OK
  [118/121] sih_rdsp2508_traduzido.csv — OK
  [119/121] sih_rdsp2509_traduzido.csv — OK
  [120/121] sih_rdsp2510_traduzido.csv — OK
  [121/121] sih_rdsp2512_traduzido.csv — OK

SIH-IAM carregado: 381,203 registros × 167 colunas

,municipio_gestor,ano_competencia,mes_competencia,especialidade_leito,cnpj_hospital,numero_aih,tipo_aih,cep_paciente,municipio_residencia,data_nascimento,...,TPDISEC1_DESC,TPDISEC2_DESC,TPDISEC3_DESC,TPDISEC4_DESC,TPDISEC5_DESC,TPDISEC6_DESC,TPDISEC7_DESC,TPDISEC8_DESC,TPDISEC9_DESC,FONTE_ORC
0,350000,2015,1,3,57740490000260.0,3514116185327,1,11713110,354100,19571124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,350000,2015,1,3,46374500011390.0,3515100592289,1,2804050,355030,19520920,...,Preexistente,Preexistente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,350000,2015,1,3,46374500011390.0,3514120847370,1,2832250,355030,19461225,...,Preexistente,Preexistente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# identificação dos tipos das colunas
df_iam.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 381203 entries, 0 to 381202
Columns: 167 entries, municipio_gestor to FONTE_ORC
dtypes: str(167)
memory usage: 485.7 MB

Todas  as colunas foram identificadas como tipo string, o que devera ser ajustado em breve.

In [22]:
print(f"Internações por IAM carregadas: {len(df_iam):,} registros")

Internações por IAM carregadas: 381,203 registros

### 1.2 Seleção de Colunas Relevantes

In [23]:
df_iam.shape

(381203, 167)

#### Tratamento de Valores Ausentes
Campos administrativos do DataSUS frequentemente chegam como strings vazias ou `"0000"`.
Substituímos apenas **colunas de texto** (object), preservando zeros em variáveis
numéricas legítimas (ex.: `indicador_obito=0` = alta; `uti_mes_total=0` = sem UTI).

In [24]:
# Aplica replace somente em colunas de texto para não corromper variáveis numéricas/binárias
str_cols = df_iam.select_dtypes(include='str').columns
df_iam[str_cols] = df_iam[str_cols].replace(["", "0000", "000"], pd.NA)

# Converte colunas numéricas para tipo correto
num_cols = ["idade", "dias_permanencia", "indicador_obito",
            "uti_mes_total", "codigo_idade"]
for col in num_cols:
    if col in df_iam.columns:
        df_iam[col] = pd.to_numeric(df_iam[col], errors='coerce')

        # IDADE INCOERentE

print("Tratamento de nulos concluído.")

Tratamento de nulos concluído.

Ainda temos 114 colunas e nem todas serão nesessárias então iremos aplicar uma limpeza.
#### Remoção de colunas inutilizáveis

In [25]:
pct_nulos = df_iam.isnull().mean() * 100
print(pct_nulos.sort_values(ascending=False))

INSC_PN_DESC          100.00
SEQ_AIH5_DESC         100.00
infeccao_hospitalar   100.00
data_autorizacao      100.00
cid_notificacao       100.00
                       ...
MES_CMPT_DESC           0.00
tipo_diag_sec_9         0.00
CAR_INT_DESC            0.00
GESTRISCO_DESC          0.00
FINANC_DESC             0.00
Length: 167, dtype: float64

In [26]:
# ── Remoção de colunas inutilizáveis ─────────────────────────────────────────
# Colunas 100% nulas (sem informação alguma)
limite = 70  # %
cols_remover = pct_nulos[pct_nulos > limite].index
df_iam = df_iam.drop(columns=cols_remover)
print(f'Removidas {len(cols_remover)} colunas com mais de {limite}% de nulos')


# Filtro de idade: manter apenas adultos (>= 18 anos)
#    IAM pediátrico é evento raro e biologicamente distinto — excluído do escopo
df_iam['idade'] = pd.to_numeric(df_iam['idade'], errors='coerce')
n_antes = len(df_iam)
df_iam = df_iam[df_iam['idade'] >= 18].copy()
print(f'Registros pediátricos removidos (idade < 18): {n_antes - len(df_iam)}')
print(f'Base SIH-IAM adultos: {len(df_iam)} registros × {df_iam.shape[1]} colunas')

Removidas 57 colunas com mais de 70% de nulos
Registros pediátricos removidos (idade < 18): 612
Base SIH-IAM adultos: 380591 registros × 110 colunas

In [27]:
# Resumo de completude
nulls = pd.DataFrame({
    "qtd_nulos":  df_iam.isnull().sum(),
    "perc_nulos": df_iam.isnull().mean() * 100
}).sort_values("perc_nulos", ascending=False)

nulls[nulls["qtd_nulos"] > 0]

                          qtd_nulos  perc_nulos
diagnostico_secundario_1     204107       53.63
TPDISEC1_DESC                204107       53.63
cnpj_mantenedora             197800       51.97
COBRANCA_DESC                101222       26.60
DIAS_PERM_DESC                85765       22.53
cnpj_hospital                 60908       16.00
RACA_COR_DESC                 41751       10.97
etnia                          5219        1.37
IDENT_DESC                        3        0.00
NACIONAL_DESC                     3        0.00

### 1.3 Salvar Base SIH-IAM Intermediária

In [28]:
path_sih_interim = INTERIM / "sih_iam.csv"
df_iam.to_csv(path_sih_interim, index=False)
print(f"SIH-IAM salvo em: {path_sih_interim}  ({len(df_iam):,} registros)")

SIH-IAM salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/sih_iam.csv  (380,591 registros)

## 2. Carregamento e Padronização do CNES

Carregamos as cinco tabelas do CNES usando dicionários JSON específicos para cada prefixo.

In [4]:
# Lê os CSVs traduzidos do CNES (padrão: cnes_*_traduzido.csv)
arquivos_cnes = sorted(INTERIM.glob('cnes_*_traduzido.csv'))
print(f"Arquivos CNES traduzidos encontrados: {len(arquivos_cnes)}")
for f in arquivos_cnes:
    print(f"  {f.name}")

Arquivos CNES traduzidos encontrados: 540
  cnes_eq_eqsp1501_traduzido.csv
  cnes_eq_eqsp1502_traduzido.csv
  cnes_eq_eqsp1503_traduzido.csv
  cnes_eq_eqsp1504_traduzido.csv
  cnes_eq_eqsp1505_traduzido.csv
  cnes_eq_eqsp1506_traduzido.csv
  cnes_eq_eqsp1507_traduzido.csv
  cnes_eq_eqsp1508_traduzido.csv
  cnes_eq_eqsp1509_traduzido.csv
  cnes_eq_eqsp1510_traduzido.csv
  cnes_eq_eqsp1512_traduzido.csv
  cnes_eq_eqsp1601_traduzido.csv
  cnes_eq_eqsp1602_traduzido.csv
  cnes_eq_eqsp1603_traduzido.csv
  cnes_eq_eqsp1604_traduzido.csv
  cnes_eq_eqsp1605_traduzido.csv
  cnes_eq_eqsp1606_traduzido.csv
  cnes_eq_eqsp1607_traduzido.csv
  cnes_eq_eqsp1608_traduzido.csv
  cnes_eq_eqsp1609_traduzido.csv
  cnes_eq_eqsp1610_traduzido.csv
  cnes_eq_eqsp1612_traduzido.csv
  cnes_eq_eqsp1701_traduzido.csv
  cnes_eq_eqsp1702_traduzido.csv
  cnes_eq_eqsp1703_traduzido.csv
  cnes_eq_eqsp1704_traduzido.csv
  cnes_eq_eqsp1705_traduzido.csv
  cnes_eq_eqsp1706_traduzido.csv
  cnes_eq_eqsp1707_traduzido.csv
  cnes_eq_eqsp1708_traduzido.csv
  cnes_eq_eqsp1709_traduzido.csv
  cnes_eq_eqsp1710_traduzido.csv
  cnes_eq_eqsp1712_traduzido.csv
  cnes_eq_eqsp1801_traduzido.csv
  cnes_eq_eqsp1802_traduzido.csv
  cnes_eq_eqsp1803_traduzido.csv
  cnes_eq_eqsp1804_traduzido.csv
  cnes_eq_eqsp1805_traduzido.csv
  cnes_eq_eqsp1806_traduzido.csv
  cnes_eq_eqsp1807_traduzido.csv
  cnes_eq_eqsp1808_traduzido.csv
  cnes_eq_eqsp1809_traduzido.csv
  cnes_eq_eqsp1810_traduzido.csv
  cnes_eq_eqsp1812_traduzido.csv
  cnes_eq_eqsp1901_traduzido.csv
  cnes_eq_eqsp1902_traduzido.csv
  cnes_eq_eqsp1903_traduzido.csv
  cnes_eq_eqsp1904_traduzido.csv
  cnes_eq_eqsp1905_traduzido.csv
  cnes_eq_eqsp1906_traduzido.csv
  cnes_eq_eqsp1907_traduzido.csv
  cnes_eq_eqsp1908_traduzido.csv
  cnes_eq_eqsp1909_traduzido.csv
  cnes_eq_eqsp1910_traduzido.csv
  cnes_eq_eqsp1912_traduzido.csv
  cnes_eq_eqsp2001_traduzido.csv
  cnes_eq_eqsp2002_traduzido.csv
  cnes_eq_eqsp2003_traduzido.csv
  cnes_eq_eqsp2004_traduzido.csv
  cnes_eq_eqsp2005_traduzido.csv
  cnes_eq_eqsp2006_traduzido.csv
  cnes_eq_eqsp2007_traduzido.csv
  cnes_eq_eqsp2008_traduzido.csv
  cnes_eq_eqsp2009_traduzido.csv
  cnes_eq_eqsp2010_traduzido.csv
  cnes_eq_eqsp2012_traduzido.csv
  cnes_eq_eqsp2101_traduzido.csv
  cnes_eq_eqsp2102_traduzido.csv
  cnes_eq_eqsp2103_traduzido.csv
  cnes_eq_eqsp2104_traduzido.csv
  cnes_eq_eqsp2105_traduzido.csv
  cnes_eq_eqsp2106_traduzido.csv
  cnes_eq_eqsp2107_traduzido.csv
  cnes_eq_eqsp2108_traduzido.csv
  cnes_eq_eqsp2109_traduzido.csv
  cnes_eq_eqsp2110_traduzido.csv
  cnes_eq_eqsp2112_traduzido.csv
  cnes_eq_eqsp2201_traduzido.csv
  cnes_eq_eqsp2202_traduzido.csv
  cnes_eq_eqsp2203_traduzido.csv
  cnes_eq_eqsp2204_traduzido.csv
  cnes_eq_eqsp2205_traduzido.csv
  cnes_eq_eqsp2206_traduzido.csv
  cnes_eq_eqsp2207_traduzido.csv
  cnes_eq_eqsp2208_traduzido.csv
  cnes_eq_eqsp2209_traduzido.csv
  cnes_eq_eqsp2210_traduzido.csv
  cnes_eq_eqsp2212_traduzido.csv
  cnes_eq_eqsp2301_traduzido.csv
  cnes_eq_eqsp2302_traduzido.csv
  cnes_eq_eqsp2303_traduzido.csv
  cnes_eq_eqsp2304_traduzido.csv
  cnes_eq_eqsp2305_traduzido.csv
  cnes_eq_eqsp2306_traduzido.csv
  cnes_eq_eqsp2307_traduzido.csv
  cnes_eq_eqsp2308_traduzido.csv
  cnes_eq_eqsp2309_traduzido.csv
  cnes_eq_eqsp2310_traduzido.csv
  cnes_eq_eqsp2312_traduzido.csv
  cnes_eq_eqsp2401_traduzido.csv
  cnes_eq_eqsp2402_traduzido.csv
  cnes_eq_eqsp2403_traduzido.csv
  cnes_eq_eqsp2404_traduzido.csv
  cnes_eq_eqsp2405_traduzido.csv
  cnes_eq_eqsp2406_traduzido.csv
  cnes_eq_eqsp2407_traduzido.csv
  cnes_eq_eqsp2408_traduzido.csv
  cnes_eq_eqsp2409_traduzido.csv
  cnes_eq_eqsp2410_traduzido.csv
  cnes_eq_eqsp2412_traduzido.csv
  cnes_eq_eqsp2501_traduzido.csv
  cnes_eq_eqsp2502_traduzido.csv
  cnes_eq_eqsp2503_traduzido.csv
  cnes_eq_eqsp2504_traduzido.csv
  cnes_eq_eqsp2505_traduzido.csv
  cnes_eq_eqsp2506_traduzido.csv
  cnes_eq_eqsp2507_traduzido.csv
  cnes_eq_eqsp2508_traduzido.csv
  cnes_eq_eqsp2509_traduzido.csv
  cnes_eq_eqsp2510_traduzido.csv
  cnes_eq_eqsp2512_traduzido.csv
  cnes_hb_hbsp1501_traduzido.csv
  cnes_hb_hbsp1502_traduzido.csv
  cnes_hb_hbsp1503_traduzido.csv
  cnes_hb_hbsp1504_traduzido.csv
  cnes_hb_hbsp1505_traduzido.csv
  cnes_hb_hbsp1506_traduzido.csv
  cnes_hb_hbsp1507_traduzido.csv
  cnes_hb_hbsp1508_traduzido.csv
  cnes_hb_hbsp1509_traduzido.csv
  cnes_hb_hbsp1510_traduzido.csv
  cnes_hb_hbsp1512_traduzido.csv
  cnes_hb_hbsp1601_traduzido.csv
  cnes_hb_hbsp1602_traduzido.csv
  cnes_hb_hbsp1603_traduzido.csv
  cnes_hb_hbsp1604_traduzido.csv
  cnes_hb_hbsp1605_traduzido.csv
  cnes_hb_hbsp1606_traduzido.csv
  cnes_hb_hbsp1607_traduzido.csv
  cnes_hb_hbsp1608_traduzido.csv
  cnes_hb_hbsp1609_traduzido.csv
  cnes_hb_hbsp1610_traduzido.csv
  cnes_hb_hbsp1612_traduzido.csv
  cnes_hb_hbsp1701_traduzido.csv
  cnes_hb_hbsp1702_traduzido.csv
  cnes_hb_hbsp1703_traduzido.csv
  cnes_hb_hbsp1704_traduzido.csv
  cnes_hb_hbsp1705_traduzido.csv
  cnes_hb_hbsp1706_traduzido.csv
  cnes_hb_hbsp1707_traduzido.csv
  cnes_hb_hbsp1708_traduzido.csv
  cnes_hb_hbsp1709_traduzido.csv
  cnes_hb_hbsp1710_traduzido.csv
  cnes_hb_hbsp1712_traduzido.csv
  cnes_hb_hbsp1801_traduzido.csv
  cnes_hb_hbsp1802_traduzido.csv
  cnes_hb_hbsp1803_traduzido.csv
  cnes_hb_hbsp1804_traduzido.csv
  cnes_hb_hbsp1805_traduzido.csv
  cnes_hb_hbsp1806_traduzido.csv
  cnes_hb_hbsp1807_traduzido.csv
  cnes_hb_hbsp1808_traduzido.csv
  cnes_hb_hbsp1809_traduzido.csv
  cnes_hb_hbsp1810_traduzido.csv
  cnes_hb_hbsp1812_traduzido.csv
  cnes_hb_hbsp1901_traduzido.csv
  cnes_hb_hbsp1902_traduzido.csv
  cnes_hb_hbsp1903_traduzido.csv
  cnes_hb_hbsp1904_traduzido.csv
  cnes_hb_hbsp1905_traduzido.csv
  cnes_hb_hbsp1906_traduzido.csv
  cnes_hb_hbsp1907_traduzido.csv
  cnes_hb_hbsp1908_traduzido.csv
  cnes_hb_hbsp1909_traduzido.csv
  cnes_hb_hbsp1910_traduzido.csv
  cnes_hb_hbsp1912_traduzido.csv
  cnes_hb_hbsp2001_traduzido.csv
  cnes_hb_hbsp2002_traduzido.csv
  cnes_hb_hbsp2003_traduzido.csv
  cnes_hb_hbsp2004_traduzido.csv
  cnes_hb_hbsp2005_traduzido.csv
  cnes_hb_hbsp2006_traduzido.csv
  cnes_hb_hbsp2007_traduzido.csv
  cnes_hb_hbsp2008_traduzido.csv
  cnes_hb_hbsp2009_traduzido.csv
  cnes_hb_hbsp2010_traduzido.csv
  cnes_hb_hbsp2012_traduzido.csv
  cnes_hb_hbsp2101_traduzido.csv
  cnes_hb_hbsp2102_traduzido.csv
  cnes_hb_hbsp2103_traduzido.csv
  cnes_hb_hbsp2104_traduzido.csv
  cnes_hb_hbsp2105_traduzido.csv
  cnes_hb_hbsp2106_traduzido.csv
  cnes_hb_hbsp2107_traduzido.csv
  cnes_hb_hbsp2108_traduzido.csv
  cnes_hb_hbsp2109_traduzido.csv
  cnes_hb_hbsp2110_traduzido.csv
  cnes_hb_hbsp2112_traduzido.csv
  cnes_hb_hbsp2201_traduzido.csv
  cnes_hb_hbsp2202_traduzido.csv
  cnes_hb_hbsp2203_traduzido.csv
  cnes_hb_hbsp2204_traduzido.csv
  cnes_hb_hbsp2205_traduzido.csv
  cnes_hb_hbsp2206_traduzido.csv
  cnes_hb_hbsp2207_traduzido.csv
  cnes_hb_hbsp2208_traduzido.csv
  cnes_hb_hbsp2209_traduzido.csv
  cnes_hb_hbsp2210_traduzido.csv
  cnes_hb_hbsp2212_traduzido.csv
  cnes_hb_hbsp2301_traduzido.csv
  cnes_hb_hbsp2302_traduzido.csv
  cnes_hb_hbsp2303_traduzido.csv
  cnes_hb_hbsp2304_traduzido.csv
  cnes_hb_hbsp2305_traduzido.csv
  cnes_hb_hbsp2306_traduzido.csv
  cnes_hb_hbsp2307_traduzido.csv
  cnes_hb_hbsp2308_traduzido.csv
  cnes_hb_hbsp2309_traduzido.csv
  cnes_hb_hbsp2310_traduzido.csv
  cnes_hb_hbsp2312_traduzido.csv
  cnes_hb_hbsp2401_traduzido.csv
  cnes_hb_hbsp2402_traduzido.csv
  cnes_hb_hbsp2403_traduzido.csv
  cnes_hb_hbsp2404_traduzido.csv
  cnes_hb_hbsp2405_traduzido.csv
  cnes_hb_hbsp2406_traduzido.csv
  cnes_hb_hbsp2407_traduzido.csv
  cnes_hb_hbsp2408_traduzido.csv
  cnes_hb_hbsp2409_traduzido.csv
  cnes_hb_hbsp2410_traduzido.csv
  cnes_hb_hbsp2412_traduzido.csv
  cnes_hb_hbsp2501_traduzido.csv
  cnes_hb_hbsp2502_traduzido.csv
  cnes_hb_hbsp2503_traduzido.csv
  cnes_hb_hbsp2504_traduzido.csv
  cnes_hb_hbsp2505_traduzido.csv
  cnes_hb_hbsp2506_traduzido.csv
  cnes_hb_hbsp2507_traduzido.csv
  cnes_hb_hbsp2508_traduzido.csv
  cnes_hb_hbsp2509_traduzido.csv
  cnes_hb_hbsp2510_traduzido.csv
  cnes_hb_hbsp2512_traduzido.csv
  cnes_lt_ltsp1501_traduzido.csv
  cnes_lt_ltsp1502_traduzido.csv
  cnes_lt_ltsp1503_traduzido.csv
  cnes_lt_ltsp1504_traduzido.csv
  cnes_lt_ltsp1505_traduzido.csv
  cnes_lt_ltsp1506_traduzido.csv
  cnes_lt_ltsp1507_traduzido.csv
  cnes_lt_ltsp1508_traduzido.csv
  cnes_lt_ltsp1509_traduzido.csv
  cnes_lt_ltsp1510_traduzido.csv
  cnes_lt_ltsp1512_traduzido.csv
  cnes_lt_ltsp1601_traduzido.csv
  cnes_lt_ltsp1602_traduzido.csv
  cnes_lt_ltsp1603_traduzido.csv
  cnes_lt_ltsp1604_traduzido.csv
  cnes_lt_ltsp1605_traduzido.csv
  cnes_lt_ltsp1606_traduzido.csv
  cnes_lt_ltsp1607_traduzido.csv
  cnes_lt_ltsp1608_traduzido.csv
  cnes_lt_ltsp1609_traduzido.csv
  cnes_lt_ltsp1610_traduzido.csv
  cnes_lt_ltsp1612_traduzido.csv
  cnes_lt_ltsp1701_traduzido.csv
  cnes_lt_ltsp1702_traduzido.csv
  cnes_lt_ltsp1703_traduzido.csv
  cnes_lt_ltsp1704_traduzido.csv
  cnes_lt_ltsp1705_traduzido.csv
  cnes_lt_ltsp1706_traduzido.csv
  cnes_lt_ltsp1707_traduzido.csv
  cnes_lt_ltsp1708_traduzido.csv
  cnes_lt_ltsp1709_traduzido.csv
  cnes_lt_ltsp1710_traduzido.csv
  cnes_lt_ltsp1712_traduzido.csv
  cnes_lt_ltsp1801_traduzido.csv
  cnes_lt_ltsp1802_traduzido.csv
  cnes_lt_ltsp1803_traduzido.csv
  cnes_lt_ltsp1804_traduzido.csv
  cnes_lt_ltsp1805_traduzido.csv
  cnes_lt_ltsp1806_traduzido.csv
  cnes_lt_ltsp1807_traduzido.csv
  cnes_lt_ltsp1808_traduzido.csv
  cnes_lt_ltsp1809_traduzido.csv
  cnes_lt_ltsp1810_traduzido.csv
  cnes_lt_ltsp1812_traduzido.csv
  cnes_lt_ltsp1901_traduzido.csv
  cnes_lt_ltsp1902_traduzido.csv
  cnes_lt_ltsp1903_traduzido.csv
  cnes_lt_ltsp1904_traduzido.csv
  cnes_lt_ltsp1905_traduzido.csv
  cnes_lt_ltsp1906_traduzido.csv
  cnes_lt_ltsp1907_traduzido.csv
  cnes_lt_ltsp1908_traduzido.csv
  cnes_lt_ltsp1909_traduzido.csv
  cnes_lt_ltsp1910_traduzido.csv
  cnes_lt_ltsp1912_traduzido.csv
  cnes_lt_ltsp2001_traduzido.csv
  cnes_lt_ltsp2002_traduzido.csv
  cnes_lt_ltsp2003_traduzido.csv
  cnes_lt_ltsp2004_traduzido.csv
  cnes_lt_ltsp2005_traduzido.csv
  cnes_lt_ltsp2006_traduzido.csv
  cnes_lt_ltsp2007_traduzido.csv
  cnes_lt_ltsp2008_traduzido.csv
  cnes_lt_ltsp2009_traduzido.csv
  cnes_lt_ltsp2010_traduzido.csv
  cnes_lt_ltsp2012_traduzido.csv
  cnes_lt_ltsp2101_traduzido.csv
  cnes_lt_ltsp2102_traduzido.csv
  cnes_lt_ltsp2103_traduzido.csv
  cnes_lt_ltsp2104_traduzido.csv
  cnes_lt_ltsp2105_traduzido.csv
  cnes_lt_ltsp2106_traduzido.csv
  cnes_lt_ltsp2107_traduzido.csv
  cnes_lt_ltsp2108_traduzido.csv
  cnes_lt_ltsp2109_traduzido.csv
  cnes_lt_ltsp2110_traduzido.csv
  cnes_lt_ltsp2112_traduzido.csv
  cnes_lt_ltsp2201_traduzido.csv
  cnes_lt_ltsp2202_traduzido.csv
  cnes_lt_ltsp2203_traduzido.csv
  cnes_lt_ltsp2204_traduzido.csv
  cnes_lt_ltsp2205_traduzido.csv
  cnes_lt_ltsp2206_traduzido.csv
  cnes_lt_ltsp2207_traduzido.csv
  cnes_lt_ltsp2208_traduzido.csv
  cnes_lt_ltsp2209_traduzido.csv
  cnes_lt_ltsp2210_traduzido.csv
  cnes_lt_ltsp2212_traduzido.csv
  cnes_lt_ltsp2301_traduzido.csv
  cnes_lt_ltsp2302_traduzido.csv
  cnes_lt_ltsp2303_traduzido.csv
  cnes_lt_ltsp2304_traduzido.csv
  cnes_lt_ltsp2305_traduzido.csv
  cnes_lt_ltsp2306_traduzido.csv
  cnes_lt_ltsp2307_traduzido.csv
  cnes_lt_ltsp2308_traduzido.csv
  cnes_lt_ltsp2309_traduzido.csv
  cnes_lt_ltsp2310_traduzido.csv
  cnes_lt_ltsp2312_traduzido.csv
  cnes_lt_ltsp2401_traduzido.csv
  cnes_lt_ltsp2402_traduzido.csv
  cnes_lt_ltsp2403_traduzido.csv
  cnes_lt_ltsp2404_traduzido.csv
  cnes_lt_ltsp2405_traduzido.csv
  cnes_lt_ltsp2406_traduzido.csv
  cnes_lt_ltsp2407_traduzido.csv
  cnes_lt_ltsp2408_traduzido.csv
  cnes_lt_ltsp2409_traduzido.csv
  cnes_lt_ltsp2410_traduzido.csv
  cnes_lt_ltsp2412_traduzido.csv
  cnes_lt_ltsp2501_traduzido.csv
  cnes_lt_ltsp2502_traduzido.csv
  cnes_lt_ltsp2503_traduzido.csv
  cnes_lt_ltsp2504_traduzido.csv
  cnes_lt_ltsp2505_traduzido.csv
  cnes_lt_ltsp2506_traduzido.csv
  cnes_lt_ltsp2507_traduzido.csv
  cnes_lt_ltsp2508_traduzido.csv
  cnes_lt_ltsp2509_traduzido.csv
  cnes_lt_ltsp2510_traduzido.csv
  cnes_lt_ltsp2512_traduzido.csv
  cnes_sr_srsp1501_traduzido.csv
  cnes_sr_srsp1502_traduzido.csv
  cnes_sr_srsp1503_traduzido.csv
  cnes_sr_srsp1504_traduzido.csv
  cnes_sr_srsp1505_traduzido.csv
  cnes_sr_srsp1506_traduzido.csv
  cnes_sr_srsp1507_traduzido.csv
  cnes_sr_srsp1508_traduzido.csv
  cnes_sr_srsp1509_traduzido.csv
  cnes_sr_srsp1510_traduzido.csv
  cnes_sr_srsp1512_traduzido.csv
  cnes_sr_srsp1601_traduzido.csv
  cnes_sr_srsp1602_traduzido.csv
  cnes_sr_srsp1603_traduzido.csv
  cnes_sr_srsp1604_traduzido.csv
  cnes_sr_srsp1605_traduzido.csv
  cnes_sr_srsp1606_traduzido.csv
  cnes_sr_srsp1607_traduzido.csv
  cnes_sr_srsp1608_traduzido.csv
  cnes_sr_srsp1609_traduzido.csv
  cnes_sr_srsp1610_traduzido.csv
  cnes_sr_srsp1612_traduzido.csv
  cnes_sr_srsp1701_traduzido.csv
  cnes_sr_srsp1702_traduzido.csv
  cnes_sr_srsp1703_traduzido.csv
  cnes_sr_srsp1704_traduzido.csv
  cnes_sr_srsp1705_traduzido.csv
  cnes_sr_srsp1706_traduzido.csv
  cnes_sr_srsp1707_traduzido.csv
  cnes_sr_srsp1708_traduzido.csv
  cnes_sr_srsp1709_traduzido.csv
  cnes_sr_srsp1710_traduzido.csv
  cnes_sr_srsp1712_traduzido.csv
  cnes_sr_srsp1801_traduzido.csv
  cnes_sr_srsp1802_traduzido.csv
  cnes_sr_srsp1803_traduzido.csv
  cnes_sr_srsp1804_traduzido.csv
  cnes_sr_srsp1805_traduzido.csv
  cnes_sr_srsp1806_traduzido.csv
  cnes_sr_srsp1807_traduzido.csv
  cnes_sr_srsp1808_traduzido.csv
  cnes_sr_srsp1809_traduzido.csv
  cnes_sr_srsp1810_traduzido.csv
  cnes_sr_srsp1812_traduzido.csv
  cnes_sr_srsp1901_traduzido.csv
  cnes_sr_srsp1902_traduzido.csv
  cnes_sr_srsp1903_traduzido.csv
  cnes_sr_srsp1904_traduzido.csv
  cnes_sr_srsp1905_traduzido.csv
  cnes_sr_srsp1906_traduzido.csv
  cnes_sr_srsp1907_traduzido.csv
  cnes_sr_srsp1908_traduzido.csv
  cnes_sr_srsp1909_traduzido.csv
  cnes_sr_srsp1910_traduzido.csv
  cnes_sr_srsp1912_traduzido.csv
  cnes_sr_srsp2001_traduzido.csv
  cnes_sr_srsp2002_traduzido.csv
  cnes_sr_srsp2003_traduzido.csv
  cnes_sr_srsp2004_traduzido.csv
  cnes_sr_srsp2005_traduzido.csv
  cnes_sr_srsp2006_traduzido.csv
  cnes_sr_srsp2007_traduzido.csv
  cnes_sr_srsp2008_traduzido.csv
  cnes_sr_srsp2009_traduzido.csv
  cnes_sr_srsp2010_traduzido.csv
  cnes_sr_srsp2012_traduzido.csv
  cnes_sr_srsp2101_traduzido.csv
  cnes_sr_srsp2102_traduzido.csv
  cnes_sr_srsp2103_traduzido.csv
  cnes_sr_srsp2104_traduzido.csv
  cnes_sr_srsp2105_traduzido.csv
  cnes_sr_srsp2106_traduzido.csv
  cnes_sr_srsp2107_traduzido.csv
  cnes_sr_srsp2108_traduzido.csv
  cnes_sr_srsp2109_traduzido.csv
  cnes_sr_srsp2110_traduzido.csv
  cnes_sr_srsp2112_traduzido.csv
  cnes_sr_srsp2201_traduzido.csv
  cnes_sr_srsp2202_traduzido.csv
  cnes_sr_srsp2203_traduzido.csv
  cnes_sr_srsp2204_traduzido.csv
  cnes_sr_srsp2205_traduzido.csv
  cnes_sr_srsp2206_traduzido.csv
  cnes_sr_srsp2207_traduzido.csv
  cnes_sr_srsp2208_traduzido.csv
  cnes_sr_srsp2209_traduzido.csv
  cnes_sr_srsp2210_traduzido.csv
  cnes_sr_srsp2212_traduzido.csv
  cnes_sr_srsp2301_traduzido.csv
  cnes_sr_srsp2302_traduzido.csv
  cnes_sr_srsp2303_traduzido.csv
  cnes_sr_srsp2304_traduzido.csv
  cnes_sr_srsp2305_traduzido.csv
  cnes_sr_srsp2306_traduzido.csv
  cnes_sr_srsp2307_traduzido.csv
  cnes_sr_srsp2308_traduzido.csv
  cnes_sr_srsp2309_traduzido.csv
  cnes_sr_srsp2310_traduzido.csv
  cnes_sr_srsp2312_traduzido.csv
  cnes_sr_srsp2401_traduzido.csv
  cnes_sr_srsp2402_traduzido.csv
  cnes_sr_srsp2403_traduzido.csv
  cnes_sr_srsp2404_traduzido.csv
  cnes_sr_srsp2405_traduzido.csv
  cnes_sr_srsp2406_traduzido.csv
  cnes_sr_srsp2407_traduzido.csv
  cnes_sr_srsp2408_traduzido.csv
  cnes_sr_srsp2409_traduzido.csv
  cnes_sr_srsp2410_traduzido.csv
  cnes_sr_srsp2412_traduzido.csv
  cnes_sr_srsp2501_traduzido.csv
  cnes_sr_srsp2502_traduzido.csv
  cnes_sr_srsp2503_traduzido.csv
  cnes_sr_srsp2504_traduzido.csv
  cnes_sr_srsp2505_traduzido.csv
  cnes_sr_srsp2506_traduzido.csv
  cnes_sr_srsp2507_traduzido.csv
  cnes_sr_srsp2508_traduzido.csv
  cnes_sr_srsp2509_traduzido.csv
  cnes_sr_srsp2510_traduzido.csv
  cnes_sr_srsp2512_traduzido.csv
  cnes_st_stsp1501_traduzido.csv
  cnes_st_stsp1502_traduzido.csv
  cnes_st_stsp1503_traduzido.csv
  cnes_st_stsp1504_traduzido.csv
  cnes_st_stsp1505_traduzido.csv
  cnes_st_stsp1506_traduzido.csv
  cnes_st_stsp1507_traduzido.csv
  cnes_st_stsp1508_traduzido.csv
  cnes_st_stsp1509_traduzido.csv
  cnes_st_stsp1510_traduzido.csv
  cnes_st_stsp1512_traduzido.csv
  cnes_st_stsp1601_traduzido.csv
  cnes_st_stsp1602_traduzido.csv
  cnes_st_stsp1603_traduzido.csv
  cnes_st_stsp1604_traduzido.csv
  cnes_st_stsp1605_traduzido.csv
  cnes_st_stsp1606_traduzido.csv
  cnes_st_stsp1607_traduzido.csv
  cnes_st_stsp1608_traduzido.csv
  cnes_st_stsp1609_traduzido.csv
  cnes_st_stsp1610_traduzido.csv
  cnes_st_stsp1612_traduzido.csv
  cnes_st_stsp1701_traduzido.csv
  cnes_st_stsp1702_traduzido.csv
  cnes_st_stsp1703_traduzido.csv
  cnes_st_stsp1704_traduzido.csv
  cnes_st_stsp1705_traduzido.csv
  cnes_st_stsp1706_traduzido.csv
  cnes_st_stsp1707_traduzido.csv
  cnes_st_stsp1708_traduzido.csv
  cnes_st_stsp1709_traduzido.csv
  cnes_st_stsp1710_traduzido.csv
  cnes_st_stsp1712_traduzido.csv
  cnes_st_stsp1801_traduzido.csv
  cnes_st_stsp1802_traduzido.csv
  cnes_st_stsp1803_traduzido.csv
  cnes_st_stsp1804_traduzido.csv
  cnes_st_stsp1805_traduzido.csv
  cnes_st_stsp1806_traduzido.csv
  cnes_st_stsp1807_traduzido.csv
  cnes_st_stsp1808_traduzido.csv
  cnes_st_stsp1809_traduzido.csv
  cnes_st_stsp1810_traduzido.csv
  cnes_st_stsp1812_traduzido.csv
  cnes_st_stsp1901_traduzido.csv
  cnes_st_stsp1902_traduzido.csv
  cnes_st_stsp1903_traduzido.csv
  cnes_st_stsp1904_traduzido.csv
  cnes_st_stsp1905_traduzido.csv
  cnes_st_stsp1906_traduzido.csv
  cnes_st_stsp1907_traduzido.csv
  cnes_st_stsp1908_traduzido.csv
  cnes_st_stsp1909_traduzido.csv
  cnes_st_stsp1910_traduzido.csv
  cnes_st_stsp2001_traduzido.csv
  cnes_st_stsp2002_traduzido.csv

In [5]:
def load_cnes_custom(tipo, arquivos_cnes):
    tipo = tipo.lower()

    # Localiza o arquivo traduzido com prefixo cnes_{tipo}_
    arq = next(
        (f for f in arquivos_cnes if f.name.lower().startswith(f'cnes_{tipo}_')),
        None
    )

    if arq is None:
        raise FileNotFoundError(
            f"Arquivo traduzido cnes_{tipo}_*_traduzido.csv não encontrado."
            f" Arquivos disponíveis: {[f.name for f in arquivos_cnes]}"
        )

    # Dicionário de renomeação de colunas (old_name → new_name)
    path_dict = Path(ROOT, 'data', 'external', f'dicionario_CNES_{tipo.upper()}.json')
    with open(path_dict, 'r', encoding='utf-8') as f:
        schema = json.load(f)

    rename_dict = {col["old_name"]: col["new_name"] for col in schema}

    df = pd.read_csv(arq, dtype=str, low_memory=False)

    # Renomeia as colunas originais; as colunas _DESC ficam com o nome gerado
    # automaticamente (ex: TP_LEITO_DESC → mantida como está)
    df = df.rename(columns=rename_dict)

    df['arquivo_origem'] = arq.name
    df['tipo_cnes'] = tipo.upper()

    return df

In [6]:
df_st = load_cnes_custom('st', arquivos_cnes)
df_lt = load_cnes_custom('lt', arquivos_cnes)
df_eq = load_cnes_custom('eq', arquivos_cnes)
df_sr = load_cnes_custom('sr', arquivos_cnes)
df_hb = load_cnes_custom('hb', arquivos_cnes)

print(f"\nRegistros carregados por tabela:")
print(f"  ST (Estabelecimentos) : {df_st.shape}")
print(f"  LT (Leitos)           : {df_lt.shape}")
print(f"  EQ (Equipamentos)     : {df_eq.shape}")
print(f"  SR (Serviços)         : {df_sr.shape}")
print(f"  HB (Habilitações)     : {df_hb.shape}")

Registros carregados por tabela:
  ST (Estabelecimentos) : (66140, 255)
  LT (Leitos)           : (7667, 41)
  EQ (Equipamentos)     : (164782, 43)
  SR (Serviços)         : (104764, 46)
  HB (Habilitações)     : (4494, 49)

### 2.1 pivot Tabelas CNES

#### Remoção de Duplicidades (ST)

In [7]:
# Garante uma linha por hospital — mantém o registro mais recente
n_antes = len(df_st)
df_st = df_st.drop_duplicates(subset=['codigo_cnes'], keep='last')
print(f"ST: {n_antes} → {len(df_st)} registros únicos (removidas {n_antes - len(df_st):,} duplicatas)")

ST: 66140 → 66140 registros únicos (removidas 0 duplicatas)

#### Agregação de Leitos (LT)

In [8]:
# Pivot de leitos por tipo
df_lt['quantidade_leitos_existentes'] = pd.to_numeric(
    df_lt['quantidade_leitos_existentes'],
    errors='coerce'
).fillna(0)

df_lt_pivot = df_lt.pivot_table(
    index='codigo_cnes',
    columns='tipo_leito',
    values='quantidade_leitos_existentes',
    aggfunc='sum',
    fill_value=0
)

df_lt_pivot.columns = [
    f'leitos_{col}'
    for col in df_lt_pivot.columns
]

df_lt_pivot = df_lt_pivot.reset_index()

#### Agregação de Equipamentos (EQ)

In [9]:
# Pivot de equipamentos
df_eq['quantidade_em_uso'] = pd.to_numeric(
    df_eq['quantidade_em_uso'],
    errors='coerce'
).fillna(0)

df_eq_pivot = df_eq.pivot_table(
    index='codigo_cnes',
    columns='codigo_equipamento',
    values='quantidade_em_uso',
    aggfunc='sum',
    fill_value=0
)

df_eq_pivot.columns = [
    f'equip_{col}'
    for col in df_eq_pivot.columns
]

df_eq_pivot = df_eq_pivot.reset_index()

#### Serviços Especializados (SR) e Habilitações (HB)

In [10]:
# Serviços especializados
df_sr['flag_servico'] = 1

df_sr_pivot = df_sr.pivot_table(
    index='codigo_cnes',
    columns='codigo_servico_especializado',
    values='flag_servico',
    aggfunc='max',
    fill_value=0
)

df_sr_pivot.columns = [
    f'servico_{col}'
    for col in df_sr_pivot.columns
]

df_sr_pivot = df_sr_pivot.reset_index()

In [11]:
# Habilitações
df_hb['flag_habilitacao'] = 1

df_hb_pivot = df_hb.pivot_table(
    index='codigo_cnes',
    columns='codigo_habilitacao',
    values='flag_habilitacao',
    aggfunc='max',
    fill_value=0
)

df_hb_pivot.columns = [
    f'habilitacao_{col}'
    for col in df_hb_pivot.columns
]

df_hb_pivot = df_hb_pivot.reset_index()

In [12]:
print(df_lt_pivot.shape)
print(df_eq_pivot.shape)
print(df_sr_pivot.shape)
print(df_hb_pivot.shape)

(1173, 8)
(35879, 82)
(28645, 66)
(1644, 147)

## 3 Salvar Base Mestre de Hospitais (Interim CNES)

In [29]:
# ── Merge das tabelas CNES em torno da ST (uma linha por hospital) ───────────
#
# ST  : tabela mestre — um registro por hospital (já deduplicada acima)
# LT  : leitos por tipo de leito  → pivotado em df_lt_pivot
# EQ  : equipamentos por código   → pivotado em df_eq_pivot
# SR  : serviços especializados   → pivotado em df_sr_pivot
# HB  : habilitações              → pivotado em df_hb_pivot
#
# Usamos left join para manter todos os hospitais da ST,
# mesmo que não possuam leitos, equipamentos, etc. registrados.

df_cnes_final = df_st.copy()

for df_pivot, nome in [
    (df_lt_pivot, 'LT — Leitos'),
    (df_eq_pivot, 'EQ — Equipamentos'),
    (df_sr_pivot, 'SR — Serviços Especializados'),
    (df_hb_pivot, 'HB — Habilitações'),
]:
    # Garante que a chave está no mesmo formato (string sem espaços)
    df_pivot['codigo_cnes'] = df_pivot['codigo_cnes'].astype(str).str.strip()
    df_cnes_final = pd.merge(df_cnes_final, df_pivot, on='codigo_cnes', how='left')
    print(f'  Após merge {nome}: {df_cnes_final.shape}')

# Preenche NaN nas colunas de contagem/flag com 0
# (hospitais sem leitos/equipamentos/serviços registrados ficam como 0, não NaN)
cols_pivot = (
    list(df_lt_pivot.columns.drop('codigo_cnes')) +
    list(df_eq_pivot.columns.drop('codigo_cnes')) +
    list(df_sr_pivot.columns.drop('codigo_cnes')) +
    list(df_hb_pivot.columns.drop('codigo_cnes'))
)
df_cnes_final[cols_pivot] = df_cnes_final[cols_pivot].fillna(0)

# Remove colunas auxiliares que vieram das tabelas secundárias e são redundantes
# (arquivo_origem e tipo_cnes existem em cada pivot — causam sufixos _x/_y)
cols_remover_aux = [c for c in df_cnes_final.columns if c.endswith(('_x', '_y'))]
if cols_remover_aux:
    df_cnes_final = df_cnes_final.drop(columns=cols_remover_aux)
    print(f'  Colunas auxiliares duplicadas removidas: {cols_remover_aux}')

print(f'\nBase CNES final: {df_cnes_final.shape[0]:,} hospitais × {df_cnes_final.shape[1]} colunas')

  Após merge LT — Leitos: (66140, 262)
  Após merge EQ — Equipamentos: (66140, 343)
  Após merge SR — Serviços Especializados: (66140, 408)
  Após merge HB — Habilitações: (66140, 554)

Base CNES final: 66,140 hospitais × 554 colunas

### 3.1 Limpeza de Colunas com Muitos Nulos

Assim como feito com o SIH, removemos colunas com alto percentual de valores ausentes.
Colunas com `> 70%` de nulos não carregam informação útil para a modelagem e apenas
adicionam ruído e custo computacional.

**Tipos de colunas que tendem a ser removidas:**
- Colunas `_DESC` sem dicionário `.cnv` mapeado (ficam 100% nulas)
- Campos de controle administrativo do CNES nunca preenchidos em SP
- Campos de contrato municipal/estadual que só existem em alguns estados

In [14]:
# ── Inspeção de nulos no CNES após merge ─────────────────────────────────────
pct_nulos_cnes = df_cnes_final.isnull().mean() * 100

# Distribuição por faixa
faixas = {
    '100%'  : (pct_nulos_cnes == 100).sum(),
    '70–99%': ((pct_nulos_cnes >= 70) & (pct_nulos_cnes < 100)).sum(),
    '50–69%': ((pct_nulos_cnes >= 50) & (pct_nulos_cnes < 70)).sum(),
    '1–49%' : ((pct_nulos_cnes > 0)  & (pct_nulos_cnes < 50)).sum(),
    '0%'    : (pct_nulos_cnes == 0).sum(),
}
print(f'Shape antes da limpeza: {df_cnes_final.shape}')
print('\nDistribuição de nulos por coluna:')
for faixa, qtd in faixas.items():
    print(f'  {faixa:8}: {qtd:>4} colunas')

print('\nTop 20 colunas com mais nulos:')
print(pct_nulos_cnes.sort_values(ascending=False).head(20).to_string())

Shape antes da limpeza: (66140, 554)

Distribuição de nulos por coluna:
  100%    :   21 colunas
  70–99%  :   37 colunas
  50–69%  :    0 colunas
  1–49%   :   14 colunas
  0%      :  482 colunas

Top 20 colunas com mais nulos:
data_publicacao_contrato_municipal   100.00
numero_contrato_estadual             100.00
data_publicacao_contrato_estadual    100.00
CLASAVAL_DESC                        100.00
data_avaliacao_pnass                 100.00
COMPETEN_DESC                        100.00
NAT_JUR_DESC                         100.00
GESPRG3E_DESC                        100.00
CODUFMUN_DESC                        100.00
numero_contrato_municipal            100.00
TPGESTAO_DESC                        100.00
RETENCAO_DESC                        100.00
NIV_HIER_DESC                        100.00
TP_PREST_DESC                        100.00
DT_PUBLM_DESC                        100.00
DT_PUBLE_DESC                        100.00
DT_EXPED_DESC                        100.00
ORGEXPED_DESC                        100.00
AV_ACRED_DESC                        100.00
COD_IR_DESC                          100.00

In [15]:
# ── Remoção de colunas com > 70% de nulos ────────────────────────────────────
LIMITE_NULOS = 70  # mesmo critério aplicado ao SIH

cols_remover_cnes = pct_nulos_cnes[pct_nulos_cnes > LIMITE_NULOS].index.tolist()

df_cnes_final = df_cnes_final.drop(columns=cols_remover_cnes)

print(f'Colunas removidas (> {LIMITE_NULOS}% nulos): {len(cols_remover_cnes)}')
print(f'Shape após limpeza: {df_cnes_final.shape}')
print()

# Resumo de completude após limpeza
nulls_cnes = pd.DataFrame({
    'qtd_nulos' : df_cnes_final.isnull().sum(),
    'perc_nulos': df_cnes_final.isnull().mean() * 100
}).sort_values('perc_nulos', ascending=False)

restantes_com_nulos = nulls_cnes[nulls_cnes['qtd_nulos'] > 0]
print(f'Colunas restantes com algum nulo: {len(restantes_com_nulos)}')
if not restantes_com_nulos.empty:
    display(restantes_com_nulos)

Colunas removidas (> 70% nulos): 58
Shape após limpeza: (66140, 496)

Colunas restantes com algum nulo: 14

                          qtd_nulos  perc_nulos
SERAP01P_DESC                 32952       49.82
RES_BIOL_DESC                 31420       47.51
codigo_regiao_saude           26063       39.41
NIV_DEP_DESC                  11148       16.86
data_expedicao_alvara          9302       14.06
numero_alvara                  8511       12.87
orgao_expedidor_alvara         8433       12.75
avaliado_pnass                 7464       11.29
avaliado_acreditacao           6451        9.75
codigo_nivel_hierarquia        6061        9.16
RES_COMU_DESC                  5838        8.83
TP_UNID_DESC                   2213        3.35
codigo_fluxo_clientela          791        1.20
codigo_turno_atendimento         32        0.05

In [16]:
path_cnes_interim = INTERIM / "cnes_hospitais.csv"
df_cnes_final.to_csv(path_cnes_interim, index=False)
print(f"CNES Interim salvo em: {path_cnes_interim}  ({len(df_cnes_final):,} hospitais)")

CNES Interim salvo em: /home/carolina/Documents/TCC Documentos/TCC/data/interim/cnes_hospitais.csv  (66,140 hospitais)

## 4. Fusão Global: SIH-IAM × CNES

Fazemos um *Left Join* das internações por IAM com a base mestre de hospitais.
A chave de junção é `codigo_cnes`, normalizada em ambos os lados para evitar
divergências por zeros à esquerda ou espaços.

In [30]:
# ── Padroniza a chave de merge nos dois DataFrames ──────────────────────────
# No SIH-IAM o campo foi salvo como 'cnes' (nome original do DATASUS);
# no CNES-final a coluna já foi renomeada para 'codigo_cnes' pelo dicionário.
if 'cnes' in df_iam.columns and 'codigo_cnes' not in df_iam.columns:
    df_iam = df_iam.rename(columns={'cnes': 'codigo_cnes'})

df_iam['codigo_cnes']        = df_iam['codigo_cnes'].astype(str).str.strip().str.zfill(7)
df_cnes_final['codigo_cnes'] = df_cnes_final['codigo_cnes'].astype(str).str.strip().str.zfill(7)

# ── Resolve conflitos de nome entre SIH e CNES antes do merge ────────────────
# Colunas que existem nos dois lados (exceto a chave) receberiam sufixo _x/_y.
# Estratégia: renomear as colunas do CNES adicionando prefixo 'cnes_' quando conflitam.
chave = 'codigo_cnes'
cols_sih  = set(df_iam.columns) - {chave}
cols_cnes = set(df_cnes_final.columns) - {chave}
conflitos = cols_sih & cols_cnes

if conflitos:
    print(f'Colunas em conflito renomeadas no CNES (prefixo cnes_): {sorted(conflitos)}')
    df_cnes_final = df_cnes_final.rename(
        columns={c: f'cnes_{c}' for c in conflitos}
    )

# ── Left Join: mantém todos os registros IAM ──────────────────────────────────
df_base_modelagem = pd.merge(df_iam, df_cnes_final, on=chave, how='left')

# ── Log de qualidade do merge ─────────────────────────────────────────────────
# Usa uma coluna que SÓ existe no CNES para medir o match rate
col_check = 'tipo_unidade'  # sempre vem do CNES-ST, nunca do SIH
n_sem_cnes = df_base_modelagem[col_check].isna().sum()

print(f'Total de internações IAM        : {len(df_base_modelagem):,}')
print(f'Sem correspondência no CNES     : {n_sem_cnes:,}  ({n_sem_cnes/len(df_base_modelagem)*100:.1f}%)')
print(f'Com dados hospitalares do CNES  : {len(df_base_modelagem) - n_sem_cnes:,}')
print(f'Número de features da base final: {df_base_modelagem.shape[1]}')

Colunas em conflito renomeadas no CNES (prefixo cnes_): ['cnpj_mantenedora', 'natureza_juridica', 'tipo_gestao']
Total de internações IAM        : 380,591
Sem correspondência no CNES     : 12,310  (3.2%)
Com dados hospitalares do CNES  : 368,281
Número de features da base final: 663

In [31]:
# Exporta base de modelagem final
path_base_final = PROCESSED / "base_modelagem.csv"
df_base_modelagem.to_csv(path_base_final, index=False)
print(f"Base de modelagem salva em: {path_base_final}")
df_base_modelagem.sample(3)

Base de modelagem salva em: /home/carolina/Documents/TCC Documentos/TCC/data/processed/base_modelagem.csv

,municipio_gestor,ano_competencia,mes_competencia,especialidade_leito,cnpj_hospital,numero_aih,tipo_aih,cep_paciente,municipio_residencia,data_nascimento,...,habilitacao_806,habilitacao_807,habilitacao_901,habilitacao_902,habilitacao_903,habilitacao_904,habilitacao_905,habilitacao_906,habilitacao_907,habilitacao_908
201551,350000,2021,8,1,NaN,3521102708508,1,13085712,350950,19510112,...,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
190461,350000,2021,4,1,53725560000170.0,3521101864654,1,2516010,355030,19621128,...,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
81009,350000,2017,12,1,60742616000160.0,3517128376850,1,8472285,355030,19470727,...,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [32]:
df_base_modelagem

,municipio_gestor,ano_competencia,mes_competencia,especialidade_leito,cnpj_hospital,numero_aih,tipo_aih,cep_paciente,municipio_residencia,data_nascimento,...,habilitacao_806,habilitacao_807,habilitacao_901,habilitacao_902,habilitacao_903,habilitacao_904,habilitacao_905,habilitacao_906,habilitacao_907,habilitacao_908
0,350000,2015,1,3,57740490000260.0,3514116185327,1,11713110,354100,19571124,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,350000,2015,1,3,46374500011390.0,3515100592289,1,2804050,355030,19520920,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,350000,2015,1,3,46374500011390.0,3514120847370,1,2832250,355030,19461225,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,350000,2015,1,3,46374500011390.0,3514121521405,1,2853000,355030,19460703,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,350000,2015,1,1,NaN,3514126947892,1,15460000,351980,19471208,...,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380586,355650,2025,12,3,NaN,3525111826830,1,13221601,355650,19681205,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
380587,355670,2025,12,3,72909179000105.0,3525123495091,1,13285220,355670,19460204,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
380588,355670,2025,12,3,72909179000105.0,3525123494981,1,13280460,355670,19610613,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
380589,355670,2025,12,3,72909179000105.0,3525123495950,1,13285536,355670,19770325,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
380590,355700,2025,12,3,NaN,3525134237262,1,18117254,355700,19551101,...,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00

---
## Resumo do Pipeline

| Etapa | Input | Output | Registros |
|-------|-------|--------|-----------|
| 1. Filtro IAM (SIH) | `data/input/SIH/*.csv` | `data/interim/sih_iam.csv` | ver acima |
| 2. Consolidação CNES | `data/input/CNES/*.csv` | `data/interim/cnes_hospitais.csv` | ver acima |
| 3. Fusão global | sih_iam + cnes_hospitais | `data/processed/base_modelagem.csv` | ver acima |

> **Próximos passos:** notebook `03_analise_exploratotia_visualizacao.ipynb` — análise exploratória e visualizações.